
# This file was generated by 'versioneer.py' (0.15) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json
import sys

version_json = '''
{
 "dirty": false,
 "error": null,
 "full-revisionid": "ae9277e117e582f06cd9d1eda067f0664a1403ad",
 "version": "1975"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
