# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-17 18:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edc_export', '0003_auto_20170817_1812'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalplan',
            name='lookups',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='plan',
            name='lookups',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='historicalplan',
            name='excluded_field_names',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='historicalplan',
            name='field_names',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='historicalplan',
            name='header_labels',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='historicalplan',
            name='model_type',
            field=models.CharField(choices=[('consent', 'Consent'), ('crf', 'CRF'), ('locator', 'Locator'), ('plain', 'Plain')], default='plain', max_length=25),
        ),
        migrations.AlterField(
            model_name='plan',
            name='excluded_field_names',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='plan',
            name='field_names',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='plan',
            name='header_labels',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='plan',
            name='model_type',
            field=models.CharField(choices=[('consent', 'Consent'), ('crf', 'CRF'), ('locator', 'Locator'), ('plain', 'Plain')], default='plain', max_length=25),
        ),
    ]
