---

- name: Manage network configuration using ifupdown
  hosts: [ 'debops_service_ifupdown' ]
  become: True

  environment: '{{ inventory__environment | d({})
                   | combine(inventory__group_environment | d({}))
                   | combine(inventory__host_environment  | d({})) }}'

  roles:

    - role: debops.ifupdown/env
      tags: [ 'role::ifupdown', 'role::kmod', 'role::ferm' ]

    - role: debops.kmod
      tags: [ 'role::kmod' ]
      kmod__dependent_load:
        - '{{ ifupdown__env_kmod__dependent_load }}'

    - role: debops.ferm
      tags: [ 'role::ferm' ]
      ferm__dependent_rules:
        - '{{ ifupdown__env_ferm__dependent_rules }}'

    - role: debops.ifupdown
      tags: [ 'role::ifupdown' ]
