---

- name: Generate Ansible redis-server dynamic configuration
  template:
    src: 'etc/redis/ansible-redis-dynamic.conf.j2'
    dest: '/etc/redis/ansible-redis-dynamic.conf'
    owner: 'root'
    group: '{{ redis__group }}'
    mode: '0750'
  register: redis__register_config_ansible_redis_dynamic

- name: Apply dynamic redis-server configuration
  command: /etc/redis/ansible-redis-dynamic.conf config
  when: redis__register_config_ansible_redis_dynamic is changed

- name: Generate Ansible redis-server static configuration
  template:
    src: 'etc/redis/ansible-redis-static.conf.j2'
    dest: '/etc/redis/ansible-redis-static.conf'
    owner: 'root'
    group: '{{ redis__group }}'
    mode: '0640'
  register: redis__register_config_ansible_redis_static

- name: Remove Ansible include line from redis.conf
  lineinfile:
    dest: '/etc/redis/redis.conf'
    regexp: '^include\s+/etc/redis/ansible-redis-static.conf'
    state: 'absent'
  when: redis__register_config_ansible_redis_static is changed

- name: Include Ansible configuration in redis.conf
  lineinfile:
    dest: '/etc/redis/redis.conf'
    regexp: '^include\s+/etc/redis/ansible-redis-static.conf'
    line: 'include /etc/redis/ansible-redis-static.conf'
    insertafter: 'EOF'
    state: 'present'
  register: redis__register_config_redis

- name: Restart redis-server if modified
  service:
    name: 'redis-server'
    state: 'restarted'
  register: redis__register_server_restart
  when: (redis__register_config_ansible_redis_static is changed or
         redis__register_config_redis is changed)

- name: Rewrite dynamic redis-server configuration
  command: /etc/redis/ansible-redis-dynamic.conf rewrite
  when: redis__register_server_restart is changed

- name: Set Redis instance as slave on first install
  redis:
    command: 'slave'
    master_host: '{{ redis__server_master_host }}'
    master_port: '{{ redis__server_master_port }}'
    login_port: '{{ redis__server_port }}'
    login_password: '{{ redis__auth_password | d(omit) }}'
  when: ((ansible_local is undefined or
          (ansible_local|d() and ansible_local.redis is undefined or
           (ansible_local.redis|d() and not ansible_local.redis.installed|bool))) and
         (redis__server_master_host|d() and
          (inventory_hostname != redis__inventory_master or redis__server_slave|bool)))
  no_log: True
