---

- name: Check if redis-sentinel unit file exists
  stat:
    path: '/lib/systemd/system/redis-sentinel.service'
  register: redis__register_sentinel_unit_file

- name: Install redis-sentinel unit file
  template:
    src: 'etc/systemd/system/redis-sentinel.service.j2'
    dest: '/etc/systemd/system/redis-sentinel.service'
    owner: 'root'
    group: 'root'
    mode: '0644'
  register: redis__register_sentinel_unit_install
  when: (ansible_service_mgr == 'systemd' and redis__register_sentinel_unit_file.stat|d() and
         not redis__register_sentinel_unit_file.stat.exists|bool)

- name: Reload systemd daemons
  command: systemctl daemon-reload
  when: redis__register_sentinel_unit_install is changed

- name: Start redis-sentinel service
  service:
    name: 'redis-sentinel'
    state: 'started'
    enabled: True
  when: redis__register_sentinel_unit_install is changed
