
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2018-07-28T12:16:28+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "587ca60058db3168da8ee38ac24a9570b710ff90",
 "version": "0.02.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
