- project:
    templates:
        - release-notes-jobs
        - publish-openstack-sphinx-docs
    check:
      jobs:
        - virtualbmc-tempest-dsvm-ironic-pxe_ipmitool-src
        - openstack-tox-lower-constraints
    gate:
      jobs:
        - virtualbmc-tempest-dsvm-ironic-pxe_ipmitool-src
        - openstack-tox-lower-constraints
