__title__ = 'pynga'
__description__ = 'Python implementation of NGA'
__url__ = 'http://github.com/icyblade/pynga'
__version__ = '2.1.4'
__author__ = 'Icyblade Dai'
__author_email__ = 'icyblade.aspx@gmail.com'
__license__ = 'MIT'
