# Generated by Django 2.0.6 on 2018-07-19 11:24

import djmoney.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_pain', '0009_auto_20180718_0416'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankpayment',
            name='objective_cs',
            field=models.TextField(blank=True, null=True, verbose_name='Objective'),
        ),
        migrations.AddField(
            model_name='bankpayment',
            name='objective_en',
            field=models.TextField(blank=True, null=True, verbose_name='Objective'),
        ),
        migrations.AlterField(
            model_name='bankaccount',
            name='currency',
            field=djmoney.models.fields.CurrencyField(default='CZK', max_length=3),
        ),
        migrations.AlterField(
            model_name='bankpayment',
            name='amount_currency',
            field=djmoney.models.fields.CurrencyField(choices=[('CZK', 'Czech Koruna'), ('EUR', 'Euro'), ('USD', 'US Dollar')], default='CZK', editable=False, max_length=3),
        ),
    ]
