---

- name: DebOps pre_tasks hook
  include: "{{ lookup('task_src', 'lxc/pre_main.yml') }}"

- name: Install required packages
  package:
    name: '{{ item }}'
    state: 'present'
  with_flattened:
    - '{{ lxc__base_packages }}'
    - '{{ lxc__packages }}'

- name: Install custom LXC helper scripts
  copy:
    src: 'usr/local/bin/'
    dest: '/usr/local/bin/'
    owner: 'root'
    group: 'root'
    mode: '0755'

- name: Remove LXC configuration if requested
  file:
    path: '/etc/lxc/{{ item.filename | d(item.name + ".conf") }}'
    state: 'absent'
  with_items: '{{ lxc__combined_configuration | parse_kv_items }}'
  when: item.name|d() and item.state|d('present') == 'absent'

- name: Generate LXC configuration
  template:
    src: 'etc/lxc/template.conf.j2'
    dest: '/etc/lxc/{{ item.filename | d(item.name + ".conf") }}'
    owner: 'root'
    group: 'root'
    mode: '0644'
  with_items: '{{ lxc__combined_configuration | parse_kv_items }}'
  when: item.name|d() and item.state|d('present') not in [ 'absent', 'ignore', 'init' ]

- name: Make sure that Ansible local facts directory exists
  file:
    path: '/etc/ansible/facts.d'
    state: 'directory'
    owner: 'root'
    group: 'root'
    mode: '0755'

- name: Save LXC local facts
  template:
    src: 'etc/ansible/facts.d/lxc.fact.j2'
    dest: '/etc/ansible/facts.d/lxc.fact'
    owner: 'root'
    group: 'root'
    mode: '0755'
  register: lxc__register_facts

- name: Update Ansible facts if they were modified
  action: setup
  when: lxc__register_facts is changed

- name: DebOps post_tasks hook
  include: "{{ lookup('task_src', 'lxc/post_main.yml') }}"
