
# This file was generated by 'versioneer.py' (0.17) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2018-07-23T02:46:32-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "ca721e772cfaf5246d165003af13cf28a33f0286",
 "version": "3.10.3"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
