language: cpp

compiler:
 - gcc
 - clang

env:
 - CPP11=OFF
 - CPP11=ON

before_install:
 - sudo add-apt-repository ppa:kubuntu-ppa/backports -y
 - sudo apt-get update -qq
 - sudo apt-get install -qq cmake=2.8.12.2-0ubuntu1~ubuntu12.04.1~ppa2

before_script:
 - cmake -DSNOWHOUSE_IS_CPP11=${CPP11} .

script:
 - make
