# coding: utf-8

"""
    Dash Auth API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: v1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import dash_auth
from dash_auth.api.login_api import LoginApi  # noqa: E501
from dash_auth.rest import ApiException


class TestLoginApi(unittest.TestCase):
    """LoginApi unit test stubs"""

    def setUp(self):
        self.api = dash_auth.api.login_api.LoginApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_api_login_auth_external_get(self):
        """Test case for api_login_auth_external_get

        """
        pass

    def test_api_login_post(self):
        """Test case for api_login_post

        """
        pass

    def test_api_login_providers_get(self):
        """Test case for api_login_providers_get

        """
        pass

    def test_api_login_request_external_get(self):
        """Test case for api_login_request_external_get

        """
        pass


if __name__ == '__main__':
    unittest.main()
