
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2018-08-07T11:14:12-0600",
 "dirty": false,
 "error": null,
 "full-revisionid": "d49c496b701cc3e042637ddbeb15668deedfaeac",
 "version": "V1.0.2"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
