
# This file was generated by 'versioneer.py' (0.15) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json
import sys

version_json = '''
{
 "dirty": false,
 "error": null,
 "full-revisionid": "6d40a3bb3f4aba2e3232fc4df23a55d2c36df253",
 "version": "0.5.18"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
