
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2018-08-03T10:19:43+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "45b9e4b4824465251cbf32cf89df206e77c3e935",
 "version": "3.0.22"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
