- project:
    check:
      jobs:
        - monasca-tempest-python-influxdb
        - monasca-tempest-java-influxdb
        - monasca-tempest-python-cassandra
        - monasca-tempest-java-cassandra
        - openstack-tox-lower-constraints
    gate:
      jobs:
        - monasca-tempest-python-influxdb
        - monasca-tempest-java-influxdb
        - monasca-tempest-python-cassandra
        - monasca-tempest-java-cassandra
        - openstack-tox-lower-constraints
