---

dhcpd_base_packages_map:
  'server':
    - 'isc-dhcp-server'
  'relay':
    - 'isc-dhcp-relay'
  'probe': []

dhcpd_services:
  'server':
    - 'isc-dhcp-server'
  'relay':
    - 'isc-dhcp-relay'
  'probe':
    - 'dhcp-probe'

dhcpd_templates:
  - 'etc/default/isc-dhcp-server'
  - 'etc/dhcp/dhcpd.conf'

# vim: set ts=2 sw=2:
