version: 2
jobs:
  flake8: &tox-template
    docker:
      - image: circleci/python:3
    environment:
      TOXENV: flake8
    steps:
      - checkout
      - run: pip install --user tox
      - run: /home/circleci/.local/bin/tox

  check_readme:
    <<: *tox-template
    docker:
      - image: circleci/python:3
    environment:
      TOXENV: check_readme

  build:
    docker:
      - image: circleci/python:3
    environment:
      TOXENV: build
    steps:
      - checkout
      - run: pip install --user tox
      - run: /home/circleci/.local/bin/tox
      - store_artifacts:
          path: dist
          destination: packages
      - persist_to_workspace:
          root: .
          paths:
            - dist

  deploy_pypi:
    docker:
      - image: circleci/python:3
    environment:
      TOXENV: deploy_pypi
    steps:
      - attach_workspace:
          at: /tmp/workspace
      - checkout
      - run: pip install --user tox
      - run: /home/circleci/.local/bin/tox -- '/tmp/workspace/dist/*'

  deploy_github:
    docker:
      - image: circleci/python:3
    environment:
      TOXENV: deploy_github
    steps:
      - attach_workspace:
          at: /tmp/workspace
      - checkout
      - run: pip install --user tox
      - run: |
          export GITHUB_RELEASE_CICD_REPO=$(python setup.py --name)
          export GITHUB_RELEASE_CICD_CREATE_TAG="v$(python setup.py --version)"
          export GITHUB_RELEASE_CICD_CREATE_MESSAGE=$(git show --no-patch --pretty=format:"%s%n%b" ${CIRCLE_SHA1})
          export GITHUB_RELEASE_CICD_CREATE_TARGET=${CIRCLE_SHA1}
          /home/circleci/.local/bin/tox -- '/tmp/workspace/dist/*'

workflows:
  version: 2
  test-and-build:
    jobs:
      - check_readme:
          filters:
            tags:
              only: /^v.*/
      - flake8:
          filters:
            tags:
              only: /^v.*/
      - build:
          requires:
            - check_readme
            - flake8
          filters:
            tags:
              only: /^v.*/
      - deploy_pypi:
          requires:
            - build
          filters:
            tags:
              only: /^v.*/
      - deploy_github:
          requires:
            - build
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v.*/
