---
- include: register.yml
  when: inventory_hostname in groups['mistral-api']

- include: config.yml
  when: inventory_hostname in groups['mistral-api'] or
        inventory_hostname in groups['mistral-engine'] or
        inventory_hostname in groups['mistral-executor']

- include: clone.yml
  when: mistral_dev_mode | bool

- include: bootstrap.yml
  when: inventory_hostname in groups['mistral-api']

- name: Flush handlers
  meta: flush_handlers
