- project:
    templates:
      - openstacksdk-functional-tips
      - openstacksdk-tox-tips
      - osc-tox-unit-tips
      - shade-functional-tips
      - shade-tox-tips
    check:
      jobs:
        - openstack-tox-lower-constraints
    gate:
      jobs:
        - openstack-tox-lower-constraints
