
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2018-07-20T17:29:33+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "122a38c89d5bb161ca6eb46c277588999e1572ad",
 "version": "2.5.4"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
