# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2018-07-21 12:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DBLogEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('NOTSET', 'NotSet'), ('INFO', 'Info'), ('WARNING', 'Warning'), ('DEBUG', 'Debug'), ('ERROR', 'Error'), ('FATAL', 'Fatal')], db_index=True, max_length=10)),
                ('message', models.TextField()),
                ('trace', models.TextField(blank=True, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('-created_on',),
            },
        ),
    ]
