
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2018-07-25T15:16:12-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "acdcd7822e93f8775936e2e38c5f8f6837017ba7",
 "version": "1.0a6"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
