- project:
    check:
      jobs:
        - ironicclient-dsvm-functional
        - ironicclient-tempest-dsvm-src
        - openstack-tox-lower-constraints
    gate:
      queue: ironic
      jobs:
        - ironicclient-dsvm-functional
        - ironicclient-tempest-dsvm-src
        - openstack-tox-lower-constraints
