# -*- coding: utf-8 -*-
#
# THIS FILE IS AUTOGENERATED FROM SETUP.PY. DO NOT EDIT.
#
public_version   = "0.0.2"
local_version    = "0.0.2+20180805T165247Z.4ba0faaaa683d15cf65962699f03f3ed07fc8ca2"
sem_version      = "0.0.2+buildtime.20180805T165247Z.git.4ba0faaaa683d15cf65962699f03f3ed07fc8ca2"

release_version  = "0.0.2"
__version__      = "0.0.2"
release          = True

vcs_tag          = "4ba0faaaa683d15cf65962699f03f3ed07fc8ca2"
vcs_clean        = True
build_time_posix = 1533487967
build_time_iso   = "20180805T165247Z"
