[package]
name = "urlquote"
version = "0.2.0"
authors = ["Blue Yonder <oss@blue-yonder.com>"]
publish = false

[lib]
crate-type = ['cdylib', 'rlib']

[dependencies]
percent-encoding = "1.0"

[profile.release]
panic = 'abort'