[build-system]
requires = ["flit"]
build-backend = "flit.buildapi"

[tool.flit.metadata]
module = "redis_relay"
dist-name = "redis-relay"
author = "Yingbo Gu"
author-email = "tensiongyb@gmail.com"
maintainer="Yingbo Gu"
maintainer-email="tensiongyb@gmail.com"
home-page = "https://github.com/guyingbo/redis-relay"
description-file = "README.md"
requires-python=">=3.5"
classifiers = [
    "License :: OSI Approved :: MIT License",
    "Framework :: AsyncIO",
    "Intended Audience :: Developers",
    "Programming Language :: Python :: 3.5",
    "Programming Language :: Python :: 3.6",
    "Programming Language :: Python :: 3.7",
]
requires = ["aioredis"]
dev-requires = ["pytest", "coverage", "pytest-cov", "pytest-asyncio"]
keywords = "aioredis pubsub"
