
# This file was generated by 'versioneer.py' (0.17) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2018-07-21T01:18:39-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "1681e339fe44d9480e90e98dabb3ee29f9b6ddae",
 "version": "3.11.4"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
