configuration:
  api_address: "https://hostname.tld"

executable:
  cmd: docker
  params:
    - run
    - "-v": '/dev/bus/usb:/dev/bus/usb'
    - "-v": '/dev:/dev'
    - "-v": '{job_config}:/some/dir/config.yaml'
    - "--net": 'host'
    - "--privileged"
    - "registry.hostname.tld/image_name"

  capabilities:
    host:
      - fqdn: 'netort-incredible-bdk.macbook'
    executor:
      - type: 'volta'
      - tag: ['volta-netort', 'macbook']
      - phone.model: some_phone_model
