ACTION = "/v1/action"
ACCOUNTING_CODE = "/v1/accounting-codes"
ACCOUNTING_PERIOD = "/v1/accounting-periods"
ACCOUNT_CRUD = "/v1/object/account"
ACCOUNT_SERVICE = "/v1/accounts"
AMENDMENT_CRUD = "/v1/object/amendment"
AMENDMENT_SERVICE = "/v1/amendments"
ATTACHMENT = "/v1/attachments"

BILL_RUN_CRUD = "/v1/object/bill-run"
BILL_RUN_SERVICE = "/v1/bill-runs"
BILLING_DOCUMENT = "/v1/billing-documents"
BILLING_PREVIEW_RUN = "/v1/billing-preview-runs"

CATALOG = "/v1/catalog/products"
CHARGE_REVENUE_SUMMARY = "/v1/charge-revenue-summaries"
COMMUNICATION_PROFILE = "/v1/object/communication-profile"
CONNECTIONS = "/v1/connections"
CONTACT = "/v1/object/contact"
CREDIT_BALANCE_ADJUSTMENT = "/v1/object/credit-balance-adjustment"
CREDIT_MEMO = "/v1/creditmemos"
CUSTOM_EXCHANGE_RATE = "/v1/custom-exchange-rates"
DEBIT_MEMO = "/v1/debitmemos"
DESCRIBE = "/v1/describe"
ENTITY = "/v1/entities"
ENTITY_CONNECTION = "/v1/entity-connections"
EVENT_TRIGGER = "/events/event-triggers"
EXPORT = "/v1/object/export"

FEATURE = "/v1/object/feature"
FILE = "/v1/files"

HMAC_SIGNATURE = "/v1/hmac-signatures"
HOSTED_PAGE = "/v1/hostedpages"

IMPORT = "/v1/object/import"
INVOICE_ADJUSTMENT = "/v1/object/invoice-adjustment"
INVOICE_ITEM_ADJUSTMENT = "/v1/object/invoice-item-adjustment"
INVOICE_ITEM = "/v1/object/invoice-item"
INVOICE_PAYMENT = "/v1/object/invoice-payment"
INVOICE_SPLIT_ITEM = "/v1/object/invoice-split-item"
INVOICE_SPLIT = "/v1/object/invoice-split"
INVOICE_CRUD = "/v1/object/invoice"
INVOICE_SERVICE = "/v1/invoices"

JOURNAL_RUN = "/v1/journal-runs"

MASS_UPDATER = "/v1/bulk"
NOTIFICATION = "/notifications"
NOTIFICATION_HISTORY = "/v1/notification-history"

OAUTH = "/oauth/token"
OPERATION = "/v1/operations"
ORDER = "/v1/orders"

PAYMENT_GATEWAY = "/v1/paymentgateways"
PAYMENT_METHOD_SNAPSHOT = "/v1/object/payment-method-snapshot"
PAYMENT_METHOD_TRANSACTION_LOG = "/v1/object/payment-method-transaction-log"
PAYMENT_METHOD_CRUD = "/v1/object/payment-method"
PAYMENT_METHOD_SERVICE = "/v1/payment-methods"
PAYMENT_RUN = "/v1/payment-runs"
PAYMENT_TRANSACTION_LOG = "/v1/object/payment-transaction-log"
PAYMENT_CRUD = "/v1/object/payment"
PAYMENT_SERVICE = "/v1/payments"
PRODUCT_FEATURE = "/v1/object/product-feature"
PRODUCT_RATE_PLAN_CHARGE_TIER = "/v1/object/product-rate-plan-charge-tier"
PRODUCT_RATE_PLAN_CHARGE = "/v1/object/product-rate-plan-charge"
PRODUCT_RATE_PLAN = "/v1/object/product-rate-plan"
PRODUCT = "/v1/object/product"

QUOTE_DOCUMENT = "/v1/quotes/document"

RATE_PLAN_CHARGE_TIER = "/v1/object/rate-plan-charge-tier"
RATE_PLAN_CHARGE = "/v1/object/rate-plan-charge"
RATE_PLAN = "/v1/object/rate-plan"
REFUND_INVOICE_PAYMENT = "/v1/object/refund-invoice-payment"
REFUND_TRANSACTION_LOG = "/v1/object/refund-transaction-log"
REFUND_CRUD = "/v1/object/refund"
REFUND_SERVICE = "/v1/refunds"
REVENUE_EVENT = "/v1/revenue-events"
REVENUE_ITEM = "/v1/revenue-items"
REVENUE_RULE = "/v1/revenue-recognition-rules"
REVENUE_SCHEDULE = "/v1/revenue-schedules"
RSA_SIGNATURE = "/v1/rsa-signatures"

SETTING = "/v1/settings"
SUBSCRIPTION_PRODUCT_FEATURE = "/v1/object/subscription-product-feature"
SUBSCRIPTION_CRUD = "/v1/object/subscription"
SUBSCRIPTION_SERVICE = "/v1/subscriptions"
SUMMARY_JOURNAL_ENTRY = "/v1/journal-entries"

TAXATION_ITEM_CRUD = "/v1/object/taxation-item"
TAXATION_ITEM_SERVICE = "/v1/taxationitems"
TRANSACTION = "/v1/transactions"

UNIT_OF_MEASURE = "/v1/object/unit-of-measure"
USAGE_CRUD = "/v1/usage"
USAGE_SERVICE = "/v1/object/usage"
USER = "/v1/users"