
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2018-08-03T09:27:56+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "b7f15317eb014e313610556b42b8f075c2261f64",
 "version": "3.0.19"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
