# -*- coding: utf-8 -*-

from .action import ACTION_MAPPING
from .batch import BATCH_MAPPING
from .board import BOARD_MAPPING
from .card import CARD_MAPPING
from .checklist import CHECKLIST_MAPPING
from .custom_field import CUSTOM_FIELD_MAPPING
from .enterprise import ENTERPRISE_MAPPING
from .label import LABEL_MAPPING
from .lane import LANE_MAPPING
from .member import MEMBER_MAPPING
from .notification import NOTIFICATION_MAPPING
from .organization import ORGANIZATION_MAPPING
from .search import SEARCH_MAPPING
from .token import TOKEN_MAPPING
from .webhook import WEBHOOK_MAPPING

RESOURCE_MAPPING = {}
RESOURCE_MAPPING.update(ACTION_MAPPING)
RESOURCE_MAPPING.update(BATCH_MAPPING)
RESOURCE_MAPPING.update(BOARD_MAPPING)
RESOURCE_MAPPING.update(CARD_MAPPING)
RESOURCE_MAPPING.update(CHECKLIST_MAPPING)
RESOURCE_MAPPING.update(CUSTOM_FIELD_MAPPING)
RESOURCE_MAPPING.update(ENTERPRISE_MAPPING)
RESOURCE_MAPPING.update(LABEL_MAPPING)
RESOURCE_MAPPING.update(LANE_MAPPING)
RESOURCE_MAPPING.update(MEMBER_MAPPING)
RESOURCE_MAPPING.update(NOTIFICATION_MAPPING)
RESOURCE_MAPPING.update(ORGANIZATION_MAPPING)
RESOURCE_MAPPING.update(SEARCH_MAPPING)
RESOURCE_MAPPING.update(TOKEN_MAPPING)
RESOURCE_MAPPING.update(WEBHOOK_MAPPING)
