---
# .. vim: foldmarker=[[[,]]]:foldmethod=marker

# debops.root_account default variables [[[
# =========================================

# .. contents:: Sections
#    :local:
#
# .. include:: ../../../includes/global.rst


# General configuration [[[
# -------------------------

# .. envvar:: root_account__enabled [[[
#
# Whether to manage the root account.
root_account__enabled: True

                                                                   # ]]]
# .. envvar:: root_account__base_packages [[[
#
# List of APT packages required by the role.
root_account__base_packages: [ 'openssh-client' ]

                                                                   # ]]]
# .. envvar:: root_account__packages [[[
#
# List of additional APT packages to install for root account support.
root_account__packages: []

                                                                   # ]]]
# .. envvar:: root_account__password [[[
#
# Password set on root account, saved in secrets
root_account__password: '{{ lookup("password", secret
                            + "/credentials/" + inventory_hostname
                            + "/root_account/password encrypt=sha512_crypt length="
                            + root_account__password_length) }}'

                                                                   # ]]]
# .. envvar:: root_account__password_length [[[
#
# Length of the root password.
root_account__password_length: '32'

                                                                   # ]]]
# .. envvar:: root_account__password_update [[[
#
# This variable controls if the role should update the ``root`` account
# password on each run. By default it will be updated only the first time the
# role is executed. If you want to update the password on each run, set this
# variable to ``True``.
root_account__password_update: '{{ False
                                   if (ansible_local|d() and ansible_local.root_account|d() and
                                       ansible_local.root_account.configured|d())
                                   else True }}'

                                                                   # ]]]
# .. envvar:: root_account__generate_ssh_key [[[
#
# Whether to generate a SSH key pair for root.
root_account__generate_ssh_key: True

                                                                   # ]]]
# .. envvar:: root_account__ssh_key_type [[[
#
# Specify the SSH private key type to use. By default role will generate
# ED25519 keys if they are supported by the remote host, otherwise RSA keys
# will be generated.
root_account__ssh_key_type: '{{ "ed25519"
                                if ("ssh-ed25519" in root_account__register_key_types.stdout_lines)
                                else "rsa" }}'

                                                                   # ]]]
# .. envvar:: root_account__ssh_key_file [[[
#
# Absolute path to the SSH private key to manage.
root_account__ssh_key_file: '/root/.ssh/id_{{ root_account__ssh_key_type }}'

                                                                   # ]]]
# .. envvar:: root_account__ssh_key_comment [[[
#
# Custom comment added to the generated SSH public key.
root_account__ssh_key_comment: 'root@{{ ansible_hostname }} generated by Ansible'

                                                                   # ]]]
# .. envvar:: root_account__ssh_key_bits [[[
#
# Specifies the number of bits in the key to create, only relevant for RSA
# keys.
root_account__ssh_key_bits: '4096'

                                                                   # ]]]
# .. envvar:: root_account__shell [[[
#
# Default root shell, set to empty string to not change the shell.
root_account__shell: ''

                                                                   # ]]]
# .. envvar:: root_account__fix_no_tty [[[
#
# When enabled, the role will ensure that the :command:`mesg n` command located
# in the :file:`/root/.profile` file will be run only when TTY is present. This
# fixes the "mesg: ttyname failed: Inappropriate ioctl for device" error message.
# See also: https://bugs.debian.org/794727, https://superuser.com/a/1253889
root_account__fix_no_tty: True
                                                                   # ]]]
                                                                   # ]]]
                                                                   # ]]]
