sudo: false
language: python
dist: xenial

matrix:
  include:
    - python: 2.7
      env: TOXENV=py27
    - python: 3.4
      env: TOXENV=py34
    - python: 3.5
      env: TOXENV=py35
    - python: 3.6
      env: TOXENV=py36
    - python: 3.7-dev
      env: TOXENV=py37
    - python: 3.6
      env: TOXENV=docs

install:
  - pip install tox

script:
  - tox

deploy:
  - provider: pypi
    user: ikalnytskyi
    password: $PYPI_PASSWORD
    on:
      tags: true
      distributions: sdist
