
# This file was generated by 'versioneer.py' (0.16) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json
import sys

version_json = '''
{
 "dirty": false,
 "error": null,
 "full-revisionid": "27c4a5c94dd1edb4df708067677e94dd474b2be4",
 "version": "2.0a4"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
