  acceptors:
  - name: artemis
    url: tcp://0.0.0.0:61616
    properties:
    - tcpSendBufferSize: 1048576
    - tcpReceiveBufferSize: 1048576
    - protocols: CORE,AMQP,STOMP,HORNETQ,MQTT,OPENWIRE
    - useEpoll: true
    - amqpCredits: 1000
    - amqpLowCredits: 300
  - name: amqp
    url: tcp://0.0.0.0:5672
    properties:
    - tcpSendBufferSize: 1048576
    - tcpReceiveBufferSize: 1048576
    - protocols: AMQP
    - useEpoll: true
    - amqpCredits: 1000
    - amqpLowCredits: 300
  - name: stomp
    url: tcp://0.0.0.0:61613
    properties:
    - tcpSendBufferSize: 1048576
    - tcpReceiveBufferSize: 1048576
    - protocols: STOMP
    - useEpoll: true
  - name: hornetq
    url: tcp://0.0.0.0:5445
    properties:
    - anycastPrefix: jms.queue.
    - multicastPrefix: jms.topic.
    - protocols: HORNETQ,STOMP
    - useEpoll: true
  - name: mqtt
    url: tcp://0.0.0.0:1883
    properties:
    - tcpSendBufferSize: 1048576
    - tcpReceiveBufferSize: 1048576
    - protocols: MQTT
    - useEpoll: true
