[tool.poetry]
name = "django-waitress"
version = "0.1.0"
description = "Run a production-ready server from manage.py"
authors = ["Adam Brenecki"]
license = "CC0-1.0"
readme = "README.rst"

[tool.poetry.dependencies]
python = "*"
waitress = "^1.1"

[tool.poetry.dev-dependencies]
