# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-08-07 18:00
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import filer.fields.image


class Migration(migrations.Migration):

    dependencies = [
        ('djangocms_partners', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='partner',
            options={'verbose_name': 'partenaire', 'verbose_name_plural': 'Partenaires'},
        ),
        migrations.AddField(
            model_name='partner',
            name='link',
            field=models.URLField(blank=True, null=True, verbose_name='Website link'),
        ),
        migrations.AddField(
            model_name='partner',
            name='order',
            field=models.IntegerField(default=0, verbose_name='Ordre'),
        ),
        migrations.AlterField(
            model_name='partner',
            name='logo',
            field=filer.fields.image.FilerImageField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parnter_logo', to=settings.FILER_IMAGE_MODEL, verbose_name='logo'),
        ),
    ]
