
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2018-08-10T18:02:51+0300",
 "dirty": false,
 "error": null,
 "full-revisionid": "de0fd17f543d1117d4dd213263b56d7543c6da9f",
 "version": "0.2.13"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
