# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'qtpad/gui_preferences.ui'
#
# Created by: PyQt5 UI code generator 5.11.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(640, 409)
        self.gridLayout_8 = QtWidgets.QGridLayout(Dialog)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.sideMenuList = QtWidgets.QListWidget(Dialog)
        self.sideMenuList.setMinimumSize(QtCore.QSize(150, 0))
        self.sideMenuList.setMaximumSize(QtCore.QSize(150, 16777215))
        self.sideMenuList.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.sideMenuList.setObjectName("sideMenuList")
        item = QtWidgets.QListWidgetItem()
        self.sideMenuList.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.sideMenuList.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.sideMenuList.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.sideMenuList.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.sideMenuList.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.sideMenuList.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.sideMenuList.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.sideMenuList.addItem(item)
        self.gridLayout.addWidget(self.sideMenuList, 0, 0, 1, 2)
        self.buttonBox = QtWidgets.QDialogButtonBox(Dialog)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.gridLayout.addWidget(self.buttonBox, 1, 0, 1, 3)
        self.stackedWidget = QtWidgets.QStackedWidget(Dialog)
        self.stackedWidget.setObjectName("stackedWidget")
        self.page = QtWidgets.QWidget()
        self.page.setObjectName("page")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.page)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.label_19 = QtWidgets.QLabel(self.page)
        font = QtGui.QFont()
        font.setUnderline(True)
        self.label_19.setFont(font)
        self.label_19.setTextFormat(QtCore.Qt.PlainText)
        self.label_19.setObjectName("label_19")
        self.gridLayout_3.addWidget(self.label_19, 0, 0, 1, 1)
        self.minimizeBox = QtWidgets.QCheckBox(self.page)
        self.minimizeBox.setObjectName("minimizeBox")
        self.gridLayout_3.addWidget(self.minimizeBox, 1, 0, 1, 2)
        self.resetButton = QtWidgets.QPushButton(self.page)
        self.resetButton.setMaximumSize(QtCore.QSize(120, 16777215))
        self.resetButton.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.resetButton.setCheckable(False)
        self.resetButton.setObjectName("resetButton")
        self.gridLayout_3.addWidget(self.resetButton, 1, 2, 1, 1)
        self.deleteEmptyNotesBox = QtWidgets.QCheckBox(self.page)
        self.deleteEmptyNotesBox.setObjectName("deleteEmptyNotesBox")
        self.gridLayout_3.addWidget(self.deleteEmptyNotesBox, 2, 0, 1, 2)
        self.label_8 = QtWidgets.QLabel(self.page)
        self.label_8.setObjectName("label_8")
        self.gridLayout_3.addWidget(self.label_8, 5, 0, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_3.addItem(spacerItem, 6, 0, 1, 1)
        self.label_18 = QtWidgets.QLabel(self.page)
        font = QtGui.QFont()
        font.setUnderline(True)
        self.label_18.setFont(font)
        self.label_18.setObjectName("label_18")
        self.gridLayout_3.addWidget(self.label_18, 7, 0, 1, 1)
        self.fetchUrlBox = QtWidgets.QCheckBox(self.page)
        self.fetchUrlBox.setObjectName("fetchUrlBox")
        self.gridLayout_3.addWidget(self.fetchUrlBox, 8, 0, 1, 3)
        self.fetchFileBox = QtWidgets.QCheckBox(self.page)
        self.fetchFileBox.setObjectName("fetchFileBox")
        self.gridLayout_3.addWidget(self.fetchFileBox, 9, 0, 1, 2)
        self.fetchTxtBox = QtWidgets.QCheckBox(self.page)
        self.fetchTxtBox.setObjectName("fetchTxtBox")
        self.gridLayout_3.addWidget(self.fetchTxtBox, 10, 0, 1, 2)
        self.fetchClearBox = QtWidgets.QCheckBox(self.page)
        self.fetchClearBox.setObjectName("fetchClearBox")
        self.gridLayout_3.addWidget(self.fetchClearBox, 11, 0, 1, 2)
        self.fetchIconBox = QtWidgets.QCheckBox(self.page)
        self.fetchIconBox.setObjectName("fetchIconBox")
        self.gridLayout_3.addWidget(self.fetchIconBox, 12, 0, 1, 2)
        self.notesDbLine = QtWidgets.QLineEdit(self.page)
        self.notesDbLine.setObjectName("notesDbLine")
        self.gridLayout_3.addWidget(self.notesDbLine, 5, 2, 1, 1)
        self.autoIndentBox = QtWidgets.QCheckBox(self.page)
        self.autoIndentBox.setObjectName("autoIndentBox")
        self.gridLayout_3.addWidget(self.autoIndentBox, 4, 0, 1, 1)
        self.safeDeleteBox = QtWidgets.QCheckBox(self.page)
        self.safeDeleteBox.setObjectName("safeDeleteBox")
        self.gridLayout_3.addWidget(self.safeDeleteBox, 3, 0, 1, 3)
        self.stackedWidget.addWidget(self.page)
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setObjectName("page_2")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.page_2)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.label = QtWidgets.QLabel(self.page_2)
        self.label.setMaximumSize(QtCore.QSize(135, 16777215))
        self.label.setObjectName("label")
        self.gridLayout_4.addWidget(self.label, 0, 0, 1, 1)
        self.leftClickCombo = QtWidgets.QComboBox(self.page_2)
        self.leftClickCombo.setObjectName("leftClickCombo")
        self.gridLayout_4.addWidget(self.leftClickCombo, 0, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.page_2)
        self.label_2.setObjectName("label_2")
        self.gridLayout_4.addWidget(self.label_2, 3, 0, 1, 1)
        self.middleClickCombo = QtWidgets.QComboBox(self.page_2)
        self.middleClickCombo.setObjectName("middleClickCombo")
        self.gridLayout_4.addWidget(self.middleClickCombo, 3, 1, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.page_2)
        self.label_3.setObjectName("label_3")
        self.gridLayout_4.addWidget(self.label_3, 6, 0, 1, 1)
        self.startupCombo = QtWidgets.QComboBox(self.page_2)
        self.startupCombo.setObjectName("startupCombo")
        self.gridLayout_4.addWidget(self.startupCombo, 6, 1, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(20, 94, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_4.addItem(spacerItem1, 8, 0, 1, 1)
        self.cmdStartupLabel = QtWidgets.QLabel(self.page_2)
        self.cmdStartupLabel.setObjectName("cmdStartupLabel")
        self.gridLayout_4.addWidget(self.cmdStartupLabel, 7, 0, 1, 1)
        self.cmdLeftLabel = QtWidgets.QLabel(self.page_2)
        self.cmdLeftLabel.setObjectName("cmdLeftLabel")
        self.gridLayout_4.addWidget(self.cmdLeftLabel, 1, 0, 1, 1)
        self.cmdMiddleLine = QtWidgets.QLineEdit(self.page_2)
        self.cmdMiddleLine.setObjectName("cmdMiddleLine")
        self.gridLayout_4.addWidget(self.cmdMiddleLine, 4, 1, 1, 1)
        self.cmdLeftLine = QtWidgets.QLineEdit(self.page_2)
        self.cmdLeftLine.setObjectName("cmdLeftLine")
        self.gridLayout_4.addWidget(self.cmdLeftLine, 1, 1, 1, 1)
        self.cmdMiddleLabel = QtWidgets.QLabel(self.page_2)
        self.cmdMiddleLabel.setObjectName("cmdMiddleLabel")
        self.gridLayout_4.addWidget(self.cmdMiddleLabel, 4, 0, 1, 1)
        self.cmdStartupLine = QtWidgets.QLineEdit(self.page_2)
        self.cmdStartupLine.setObjectName("cmdStartupLine")
        self.gridLayout_4.addWidget(self.cmdStartupLine, 7, 1, 1, 1)
        self.cmdLeftLine1 = QtWidgets.QFrame(self.page_2)
        self.cmdLeftLine1.setFrameShape(QtWidgets.QFrame.HLine)
        self.cmdLeftLine1.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.cmdLeftLine1.setObjectName("cmdLeftLine1")
        self.gridLayout_4.addWidget(self.cmdLeftLine1, 2, 0, 1, 2)
        self.cmdMiddleLine1 = QtWidgets.QFrame(self.page_2)
        self.cmdMiddleLine1.setFrameShape(QtWidgets.QFrame.HLine)
        self.cmdMiddleLine1.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.cmdMiddleLine1.setObjectName("cmdMiddleLine1")
        self.gridLayout_4.addWidget(self.cmdMiddleLine1, 5, 0, 1, 2)
        self.stackedWidget.addWidget(self.page_2)
        self.page_5 = QtWidgets.QWidget()
        self.page_5.setObjectName("page_5")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.page_5)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.hotkeyBox = QtWidgets.QCheckBox(self.page_5)
        self.hotkeyBox.setObjectName("hotkeyBox")
        self.gridLayout_7.addWidget(self.hotkeyBox, 0, 0, 1, 2)
        self.hotkeyTable = QtWidgets.QTableWidget(self.page_5)
        self.hotkeyTable.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustIgnored)
        self.hotkeyTable.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.hotkeyTable.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.hotkeyTable.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.hotkeyTable.setShowGrid(True)
        self.hotkeyTable.setCornerButtonEnabled(False)
        self.hotkeyTable.setObjectName("hotkeyTable")
        self.hotkeyTable.setColumnCount(2)
        self.hotkeyTable.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.hotkeyTable.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.hotkeyTable.setHorizontalHeaderItem(1, item)
        self.hotkeyTable.horizontalHeader().setDefaultSectionSize(150)
        self.hotkeyTable.horizontalHeader().setHighlightSections(False)
        self.hotkeyTable.horizontalHeader().setSortIndicatorShown(False)
        self.hotkeyTable.horizontalHeader().setStretchLastSection(True)
        self.hotkeyTable.verticalHeader().setVisible(False)
        self.hotkeyTable.verticalHeader().setHighlightSections(False)
        self.hotkeyTable.verticalHeader().setStretchLastSection(False)
        self.gridLayout_7.addWidget(self.hotkeyTable, 1, 0, 1, 4)
        self.label_7 = QtWidgets.QLabel(self.page_5)
        self.label_7.setObjectName("label_7")
        self.gridLayout_7.addWidget(self.label_7, 2, 0, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.page_5)
        self.label_6.setObjectName("label_6")
        self.gridLayout_7.addWidget(self.label_6, 3, 0, 1, 1)
        self.hotkeyKeyLine = QtWidgets.QLineEdit(self.page_5)
        self.hotkeyKeyLine.setObjectName("hotkeyKeyLine")
        self.gridLayout_7.addWidget(self.hotkeyKeyLine, 3, 1, 1, 1)
        self.hotkeyAddButton = QtWidgets.QPushButton(self.page_5)
        self.hotkeyAddButton.setMaximumSize(QtCore.QSize(60, 16777215))
        self.hotkeyAddButton.setObjectName("hotkeyAddButton")
        self.gridLayout_7.addWidget(self.hotkeyAddButton, 3, 2, 1, 1)
        self.hotkeyDeleteButton = QtWidgets.QPushButton(self.page_5)
        self.hotkeyDeleteButton.setMaximumSize(QtCore.QSize(60, 16777215))
        self.hotkeyDeleteButton.setObjectName("hotkeyDeleteButton")
        self.gridLayout_7.addWidget(self.hotkeyDeleteButton, 3, 3, 1, 1)
        self.hotkeyActionCombo = QtWidgets.QComboBox(self.page_5)
        self.hotkeyActionCombo.setObjectName("hotkeyActionCombo")
        self.gridLayout_7.addWidget(self.hotkeyActionCombo, 2, 1, 1, 3)
        self.stackedWidget.addWidget(self.page_5)
        self.page_4 = QtWidgets.QWidget()
        self.page_4.setObjectName("page_4")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.page_4)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.label_9 = QtWidgets.QLabel(self.page_4)
        self.label_9.setObjectName("label_9")
        self.gridLayout_6.addWidget(self.label_9, 2, 0, 1, 1)
        self.presetForegroundButton = QtWidgets.QToolButton(self.page_4)
        self.presetForegroundButton.setObjectName("presetForegroundButton")
        self.gridLayout_6.addWidget(self.presetForegroundButton, 4, 1, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.page_4)
        self.label_10.setObjectName("label_10")
        self.gridLayout_6.addWidget(self.label_10, 4, 0, 1, 1)
        self.label_11 = QtWidgets.QLabel(self.page_4)
        self.label_11.setObjectName("label_11")
        self.gridLayout_6.addWidget(self.label_11, 4, 2, 1, 1)
        self.presetBackgroundButton = QtWidgets.QToolButton(self.page_4)
        self.presetBackgroundButton.setObjectName("presetBackgroundButton")
        self.gridLayout_6.addWidget(self.presetBackgroundButton, 4, 3, 1, 1)
        self.presetTable = QtWidgets.QTableWidget(self.page_4)
        self.presetTable.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustIgnored)
        self.presetTable.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.presetTable.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.presetTable.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.presetTable.setShowGrid(True)
        self.presetTable.setCornerButtonEnabled(False)
        self.presetTable.setObjectName("presetTable")
        self.presetTable.setColumnCount(3)
        self.presetTable.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.presetTable.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.presetTable.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.presetTable.setHorizontalHeaderItem(2, item)
        self.presetTable.horizontalHeader().setDefaultSectionSize(140)
        self.presetTable.horizontalHeader().setHighlightSections(False)
        self.presetTable.horizontalHeader().setSortIndicatorShown(False)
        self.presetTable.horizontalHeader().setStretchLastSection(True)
        self.presetTable.verticalHeader().setVisible(False)
        self.presetTable.verticalHeader().setHighlightSections(False)
        self.presetTable.verticalHeader().setStretchLastSection(False)
        self.gridLayout_6.addWidget(self.presetTable, 0, 0, 1, 9)
        self.presetNewButton = QtWidgets.QPushButton(self.page_4)
        self.presetNewButton.setObjectName("presetNewButton")
        self.gridLayout_6.addWidget(self.presetNewButton, 4, 8, 1, 1)
        self.presetDeleteButton = QtWidgets.QPushButton(self.page_4)
        self.presetDeleteButton.setObjectName("presetDeleteButton")
        self.gridLayout_6.addWidget(self.presetDeleteButton, 4, 7, 1, 1)
        self.presetNameLine = QtWidgets.QLineEdit(self.page_4)
        self.presetNameLine.setObjectName("presetNameLine")
        self.gridLayout_6.addWidget(self.presetNameLine, 2, 1, 1, 8)
        self.stackedWidget.addWidget(self.page_4)
        self.page_6 = QtWidgets.QWidget()
        self.page_6.setObjectName("page_6")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.page_6)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_14 = QtWidgets.QLabel(self.page_6)
        self.label_14.setMinimumSize(QtCore.QSize(0, 30))
        self.label_14.setObjectName("label_14")
        self.gridLayout_2.addWidget(self.label_14, 0, 0, 1, 1)
        self.styleHeightBox = QtWidgets.QSpinBox(self.page_6)
        self.styleHeightBox.setMinimumSize(QtCore.QSize(70, 0))
        self.styleHeightBox.setMaximumSize(QtCore.QSize(70, 16777215))
        self.styleHeightBox.setMinimum(100)
        self.styleHeightBox.setMaximum(9999)
        self.styleHeightBox.setSingleStep(25)
        self.styleHeightBox.setObjectName("styleHeightBox")
        self.gridLayout_2.addWidget(self.styleHeightBox, 1, 1, 1, 1)
        self.label_13 = QtWidgets.QLabel(self.page_6)
        self.label_13.setMinimumSize(QtCore.QSize(0, 30))
        self.label_13.setObjectName("label_13")
        self.gridLayout_2.addWidget(self.label_13, 1, 3, 1, 1)
        self.styleAllBox = QtWidgets.QCheckBox(self.page_6)
        self.styleAllBox.setObjectName("styleAllBox")
        self.gridLayout_2.addWidget(self.styleAllBox, 2, 3, 1, 2)
        self.label_5 = QtWidgets.QLabel(self.page_6)
        self.label_5.setObjectName("label_5")
        self.gridLayout_2.addWidget(self.label_5, 9, 0, 1, 2)
        self.styleFontFamilyCombo = QtWidgets.QFontComboBox(self.page_6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.styleFontFamilyCombo.sizePolicy().hasHeightForWidth())
        self.styleFontFamilyCombo.setSizePolicy(sizePolicy)
        self.styleFontFamilyCombo.setMaximumSize(QtCore.QSize(150, 16777215))
        self.styleFontFamilyCombo.setObjectName("styleFontFamilyCombo")
        self.gridLayout_2.addWidget(self.styleFontFamilyCombo, 0, 4, 1, 1)
        self.framelessBox = QtWidgets.QCheckBox(self.page_6)
        self.framelessBox.setObjectName("framelessBox")
        self.gridLayout_2.addWidget(self.framelessBox, 10, 3, 1, 2)
        self.styleBackgroundButton = QtWidgets.QToolButton(self.page_6)
        self.styleBackgroundButton.setObjectName("styleBackgroundButton")
        self.gridLayout_2.addWidget(self.styleBackgroundButton, 2, 1, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.page_6)
        self.label_4.setObjectName("label_4")
        self.gridLayout_2.addWidget(self.label_4, 8, 0, 1, 2)
        self.label_15 = QtWidgets.QLabel(self.page_6)
        self.label_15.setObjectName("label_15")
        self.gridLayout_2.addWidget(self.label_15, 2, 0, 1, 1)
        self.stylePreviewTextEdit = QtWidgets.QPlainTextEdit(self.page_6)
        self.stylePreviewTextEdit.setObjectName("stylePreviewTextEdit")
        self.gridLayout_2.addWidget(self.stylePreviewTextEdit, 5, 0, 1, 5)
        self.styleForegroundButton = QtWidgets.QToolButton(self.page_6)
        self.styleForegroundButton.setObjectName("styleForegroundButton")
        self.gridLayout_2.addWidget(self.styleForegroundButton, 3, 1, 1, 1)
        self.label_16 = QtWidgets.QLabel(self.page_6)
        self.label_16.setObjectName("label_16")
        self.gridLayout_2.addWidget(self.label_16, 3, 0, 1, 1)
        self.line = QtWidgets.QFrame(self.page_6)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.gridLayout_2.addWidget(self.line, 7, 0, 1, 5)
        self.styleFontSizeBox = QtWidgets.QSpinBox(self.page_6)
        self.styleFontSizeBox.setMaximumSize(QtCore.QSize(70, 16777215))
        self.styleFontSizeBox.setMinimum(7)
        self.styleFontSizeBox.setObjectName("styleFontSizeBox")
        self.gridLayout_2.addWidget(self.styleFontSizeBox, 1, 4, 1, 1)
        self.nameImageLine = QtWidgets.QLineEdit(self.page_6)
        self.nameImageLine.setObjectName("nameImageLine")
        self.gridLayout_2.addWidget(self.nameImageLine, 9, 3, 1, 2)
        self.styleDefaultBox = QtWidgets.QCheckBox(self.page_6)
        self.styleDefaultBox.setObjectName("styleDefaultBox")
        self.gridLayout_2.addWidget(self.styleDefaultBox, 3, 3, 1, 2)
        self.styleSizegripBox = QtWidgets.QCheckBox(self.page_6)
        self.styleSizegripBox.setObjectName("styleSizegripBox")
        self.gridLayout_2.addWidget(self.styleSizegripBox, 10, 0, 1, 2)
        self.label_17 = QtWidgets.QLabel(self.page_6)
        self.label_17.setObjectName("label_17")
        self.gridLayout_2.addWidget(self.label_17, 0, 3, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem2, 0, 2, 1, 1)
        self.nameTextLine = QtWidgets.QLineEdit(self.page_6)
        self.nameTextLine.setObjectName("nameTextLine")
        self.gridLayout_2.addWidget(self.nameTextLine, 8, 3, 1, 2)
        self.stylePinBox = QtWidgets.QCheckBox(self.page_6)
        self.stylePinBox.setObjectName("stylePinBox")
        self.gridLayout_2.addWidget(self.stylePinBox, 11, 0, 1, 2)
        self.label_12 = QtWidgets.QLabel(self.page_6)
        self.label_12.setMinimumSize(QtCore.QSize(0, 30))
        self.label_12.setObjectName("label_12")
        self.gridLayout_2.addWidget(self.label_12, 1, 0, 1, 1)
        self.styleWidthBox = QtWidgets.QSpinBox(self.page_6)
        self.styleWidthBox.setMinimumSize(QtCore.QSize(70, 0))
        self.styleWidthBox.setMaximumSize(QtCore.QSize(70, 16777215))
        self.styleWidthBox.setMinimum(100)
        self.styleWidthBox.setMaximum(9999)
        self.styleWidthBox.setSingleStep(25)
        self.styleWidthBox.setObjectName("styleWidthBox")
        self.gridLayout_2.addWidget(self.styleWidthBox, 0, 1, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(20, 5, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout_2.addItem(spacerItem3, 4, 0, 1, 1)
        spacerItem4 = QtWidgets.QSpacerItem(20, 5, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout_2.addItem(spacerItem4, 6, 0, 1, 1)
        self.stackedWidget.addWidget(self.page_6)
        self.page_9 = QtWidgets.QWidget()
        self.page_9.setObjectName("page_9")
        self.gridLayout_10 = QtWidgets.QGridLayout(self.page_9)
        self.gridLayout_10.setObjectName("gridLayout_10")
        self.label_24 = QtWidgets.QLabel(self.page_9)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_24.sizePolicy().hasHeightForWidth())
        self.label_24.setSizePolicy(sizePolicy)
        self.label_24.setObjectName("label_24")
        self.gridLayout_10.addWidget(self.label_24, 0, 0, 1, 1)
        self.cssCombo = QtWidgets.QComboBox(self.page_9)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(3)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cssCombo.sizePolicy().hasHeightForWidth())
        self.cssCombo.setSizePolicy(sizePolicy)
        self.cssCombo.setObjectName("cssCombo")
        self.gridLayout_10.addWidget(self.cssCombo, 0, 1, 1, 1)
        self.cssRefreshButton = QtWidgets.QToolButton(self.page_9)
        self.cssRefreshButton.setObjectName("cssRefreshButton")
        self.gridLayout_10.addWidget(self.cssRefreshButton, 0, 2, 1, 1)
        self.cssTextEdit = QtWidgets.QPlainTextEdit(self.page_9)
        self.cssTextEdit.setObjectName("cssTextEdit")
        self.gridLayout_10.addWidget(self.cssTextEdit, 1, 0, 1, 3)
        self.stackedWidget.addWidget(self.page_9)
        self.page_3 = QtWidgets.QWidget()
        self.page_3.setObjectName("page_3")
        self.gridLayout_9 = QtWidgets.QGridLayout(self.page_3)
        self.gridLayout_9.setObjectName("gridLayout_9")
        spacerItem5 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_9.addItem(spacerItem5, 3, 1, 1, 1)
        self.label_20 = QtWidgets.QLabel(self.page_3)
        self.label_20.setObjectName("label_20")
        self.gridLayout_9.addWidget(self.label_20, 0, 0, 1, 1)
        self.menuMotherAvailableList = QtWidgets.QListWidget(self.page_3)
        self.menuMotherAvailableList.setObjectName("menuMotherAvailableList")
        self.gridLayout_9.addWidget(self.menuMotherAvailableList, 1, 0, 3, 1)
        self.menuMotherSelectedList = QtWidgets.QListWidget(self.page_3)
        self.menuMotherSelectedList.setDragDropMode(QtWidgets.QAbstractItemView.InternalMove)
        self.menuMotherSelectedList.setObjectName("menuMotherSelectedList")
        self.gridLayout_9.addWidget(self.menuMotherSelectedList, 1, 2, 3, 1)
        self.label_22 = QtWidgets.QLabel(self.page_3)
        self.label_22.setObjectName("label_22")
        self.gridLayout_9.addWidget(self.label_22, 0, 2, 1, 1)
        self.menuMotherAddButton = QtWidgets.QToolButton(self.page_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.menuMotherAddButton.sizePolicy().hasHeightForWidth())
        self.menuMotherAddButton.setSizePolicy(sizePolicy)
        self.menuMotherAddButton.setMaximumSize(QtCore.QSize(50, 16777215))
        self.menuMotherAddButton.setArrowType(QtCore.Qt.RightArrow)
        self.menuMotherAddButton.setObjectName("menuMotherAddButton")
        self.gridLayout_9.addWidget(self.menuMotherAddButton, 1, 1, 1, 1)
        self.menuMotherRemoveButton = QtWidgets.QToolButton(self.page_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.menuMotherRemoveButton.sizePolicy().hasHeightForWidth())
        self.menuMotherRemoveButton.setSizePolicy(sizePolicy)
        self.menuMotherRemoveButton.setMaximumSize(QtCore.QSize(50, 16777215))
        self.menuMotherRemoveButton.setArrowType(QtCore.Qt.LeftArrow)
        self.menuMotherRemoveButton.setObjectName("menuMotherRemoveButton")
        self.gridLayout_9.addWidget(self.menuMotherRemoveButton, 2, 1, 1, 1)
        self.stackedWidget.addWidget(self.page_3)
        self.page_7 = QtWidgets.QWidget()
        self.page_7.setObjectName("page_7")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.page_7)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.label_21 = QtWidgets.QLabel(self.page_7)
        self.label_21.setObjectName("label_21")
        self.gridLayout_5.addWidget(self.label_21, 0, 0, 1, 1)
        self.menuChildAvailableList = QtWidgets.QListWidget(self.page_7)
        self.menuChildAvailableList.setObjectName("menuChildAvailableList")
        self.gridLayout_5.addWidget(self.menuChildAvailableList, 1, 0, 3, 1)
        self.menuChildSelectedList = QtWidgets.QListWidget(self.page_7)
        self.menuChildSelectedList.setDragDropMode(QtWidgets.QAbstractItemView.InternalMove)
        self.menuChildSelectedList.setObjectName("menuChildSelectedList")
        self.gridLayout_5.addWidget(self.menuChildSelectedList, 1, 2, 3, 1)
        spacerItem6 = QtWidgets.QSpacerItem(20, 250, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_5.addItem(spacerItem6, 3, 1, 1, 1)
        self.label_23 = QtWidgets.QLabel(self.page_7)
        self.label_23.setObjectName("label_23")
        self.gridLayout_5.addWidget(self.label_23, 0, 2, 1, 1)
        self.menuChildAddButton = QtWidgets.QToolButton(self.page_7)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.menuChildAddButton.sizePolicy().hasHeightForWidth())
        self.menuChildAddButton.setSizePolicy(sizePolicy)
        self.menuChildAddButton.setMaximumSize(QtCore.QSize(50, 16777215))
        self.menuChildAddButton.setArrowType(QtCore.Qt.RightArrow)
        self.menuChildAddButton.setObjectName("menuChildAddButton")
        self.gridLayout_5.addWidget(self.menuChildAddButton, 1, 1, 1, 1)
        self.menuChildRemoveButton = QtWidgets.QToolButton(self.page_7)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.menuChildRemoveButton.sizePolicy().hasHeightForWidth())
        self.menuChildRemoveButton.setSizePolicy(sizePolicy)
        self.menuChildRemoveButton.setMaximumSize(QtCore.QSize(50, 16777215))
        self.menuChildRemoveButton.setArrowType(QtCore.Qt.LeftArrow)
        self.menuChildRemoveButton.setObjectName("menuChildRemoveButton")
        self.gridLayout_5.addWidget(self.menuChildRemoveButton, 2, 1, 1, 1)
        self.stackedWidget.addWidget(self.page_7)
        self.gridLayout.addWidget(self.stackedWidget, 0, 2, 1, 1)
        self.gridLayout_8.addLayout(self.gridLayout, 0, 0, 1, 1)

        self.retranslateUi(Dialog)
        self.stackedWidget.setCurrentIndex(0)
        self.buttonBox.accepted.connect(Dialog.accept)
        self.buttonBox.rejected.connect(Dialog.reject)
        QtCore.QMetaObject.connectSlotsByName(Dialog)
        Dialog.setTabOrder(self.minimizeBox, self.resetButton)
        Dialog.setTabOrder(self.resetButton, self.deleteEmptyNotesBox)
        Dialog.setTabOrder(self.deleteEmptyNotesBox, self.safeDeleteBox)
        Dialog.setTabOrder(self.safeDeleteBox, self.fetchUrlBox)
        Dialog.setTabOrder(self.fetchUrlBox, self.fetchFileBox)
        Dialog.setTabOrder(self.fetchFileBox, self.fetchTxtBox)
        Dialog.setTabOrder(self.fetchTxtBox, self.fetchClearBox)
        Dialog.setTabOrder(self.fetchClearBox, self.fetchIconBox)
        Dialog.setTabOrder(self.fetchIconBox, self.notesDbLine)
        Dialog.setTabOrder(self.notesDbLine, self.autoIndentBox)
        Dialog.setTabOrder(self.autoIndentBox, self.leftClickCombo)
        Dialog.setTabOrder(self.leftClickCombo, self.middleClickCombo)
        Dialog.setTabOrder(self.middleClickCombo, self.startupCombo)
        Dialog.setTabOrder(self.startupCombo, self.cmdMiddleLine)
        Dialog.setTabOrder(self.cmdMiddleLine, self.cmdLeftLine)
        Dialog.setTabOrder(self.cmdLeftLine, self.cmdStartupLine)
        Dialog.setTabOrder(self.cmdStartupLine, self.hotkeyBox)
        Dialog.setTabOrder(self.hotkeyBox, self.hotkeyTable)
        Dialog.setTabOrder(self.hotkeyTable, self.hotkeyKeyLine)
        Dialog.setTabOrder(self.hotkeyKeyLine, self.hotkeyAddButton)
        Dialog.setTabOrder(self.hotkeyAddButton, self.hotkeyDeleteButton)
        Dialog.setTabOrder(self.hotkeyDeleteButton, self.hotkeyActionCombo)
        Dialog.setTabOrder(self.hotkeyActionCombo, self.presetForegroundButton)
        Dialog.setTabOrder(self.presetForegroundButton, self.presetBackgroundButton)
        Dialog.setTabOrder(self.presetBackgroundButton, self.presetTable)
        Dialog.setTabOrder(self.presetTable, self.presetNewButton)
        Dialog.setTabOrder(self.presetNewButton, self.presetDeleteButton)
        Dialog.setTabOrder(self.presetDeleteButton, self.presetNameLine)
        Dialog.setTabOrder(self.presetNameLine, self.styleWidthBox)
        Dialog.setTabOrder(self.styleWidthBox, self.styleFontFamilyCombo)
        Dialog.setTabOrder(self.styleFontFamilyCombo, self.styleHeightBox)
        Dialog.setTabOrder(self.styleHeightBox, self.styleFontSizeBox)
        Dialog.setTabOrder(self.styleFontSizeBox, self.styleBackgroundButton)
        Dialog.setTabOrder(self.styleBackgroundButton, self.styleForegroundButton)
        Dialog.setTabOrder(self.styleForegroundButton, self.nameTextLine)
        Dialog.setTabOrder(self.nameTextLine, self.sideMenuList)
        Dialog.setTabOrder(self.sideMenuList, self.nameImageLine)
        Dialog.setTabOrder(self.nameImageLine, self.styleSizegripBox)
        Dialog.setTabOrder(self.styleSizegripBox, self.framelessBox)
        Dialog.setTabOrder(self.framelessBox, self.stylePinBox)
        Dialog.setTabOrder(self.stylePinBox, self.styleAllBox)
        Dialog.setTabOrder(self.styleAllBox, self.styleDefaultBox)
        Dialog.setTabOrder(self.styleDefaultBox, self.menuMotherAvailableList)
        Dialog.setTabOrder(self.menuMotherAvailableList, self.menuMotherAddButton)
        Dialog.setTabOrder(self.menuMotherAddButton, self.menuMotherSelectedList)
        Dialog.setTabOrder(self.menuMotherSelectedList, self.menuMotherRemoveButton)
        Dialog.setTabOrder(self.menuMotherRemoveButton, self.menuChildAvailableList)
        Dialog.setTabOrder(self.menuChildAvailableList, self.menuChildAddButton)
        Dialog.setTabOrder(self.menuChildAddButton, self.menuChildSelectedList)
        Dialog.setTabOrder(self.menuChildSelectedList, self.menuChildRemoveButton)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Preferences"))
        __sortingEnabled = self.sideMenuList.isSortingEnabled()
        self.sideMenuList.setSortingEnabled(False)
        item = self.sideMenuList.item(0)
        item.setText(_translate("Dialog", "General settings"))
        item = self.sideMenuList.item(1)
        item.setText(_translate("Dialog", "Tray icon actions"))
        item = self.sideMenuList.item(2)
        item.setText(_translate("Dialog", "Hotkeys"))
        item = self.sideMenuList.item(3)
        item.setText(_translate("Dialog", "Style presets"))
        item = self.sideMenuList.item(4)
        item.setText(_translate("Dialog", "Style default"))
        item = self.sideMenuList.item(5)
        item.setText(_translate("Dialog", "Style sheets"))
        item = self.sideMenuList.item(6)
        item.setText(_translate("Dialog", "Main context menu"))
        item = self.sideMenuList.item(7)
        item.setText(_translate("Dialog", "Note context menu"))
        self.sideMenuList.setSortingEnabled(__sortingEnabled)
        self.label_19.setText(_translate("Dialog", "General"))
        self.minimizeBox.setText(_translate("Dialog", "Minimize on startup"))
        self.resetButton.setText(_translate("Dialog", "Reset to default"))
        self.deleteEmptyNotesBox.setText(_translate("Dialog", "Delete empty notes"))
        self.label_8.setText(_translate("Dialog", "Notes database location"))
        self.label_18.setText(_translate("Dialog", "Fetch options"))
        self.fetchUrlBox.setText(_translate("Dialog", "Fetch image from URL (cause slow downs)"))
        self.fetchFileBox.setText(_translate("Dialog", "Fetch image from file"))
        self.fetchTxtBox.setText(_translate("Dialog", "Fetch text from file (*.txt)"))
        self.fetchClearBox.setText(_translate("Dialog", "Clear clipboard after fetch"))
        self.fetchIconBox.setText(_translate("Dialog", "Show fetch icon in context menu"))
        self.autoIndentBox.setText(_translate("Dialog", "Enable automatic indenting"))
        self.safeDeleteBox.setText(_translate("Dialog", "Enable safe delete (move to trash)"))
        self.label.setText(_translate("Dialog", "Left click action"))
        self.label_2.setText(_translate("Dialog", "Middle click action"))
        self.label_3.setText(_translate("Dialog", "Startup action"))
        self.cmdStartupLabel.setText(_translate("Dialog", "Command:"))
        self.cmdLeftLabel.setText(_translate("Dialog", "Command:"))
        self.cmdMiddleLabel.setText(_translate("Dialog", "Command:"))
        self.hotkeyBox.setText(_translate("Dialog", "Enable hotkeys"))
        self.hotkeyTable.setSortingEnabled(False)
        item = self.hotkeyTable.horizontalHeaderItem(0)
        item.setText(_translate("Dialog", "Hotkey"))
        item = self.hotkeyTable.horizontalHeaderItem(1)
        item.setText(_translate("Dialog", "Action"))
        self.label_7.setText(_translate("Dialog", "Action"))
        self.label_6.setText(_translate("Dialog", "Key"))
        self.hotkeyAddButton.setText(_translate("Dialog", "Add"))
        self.hotkeyDeleteButton.setText(_translate("Dialog", "Delete"))
        self.label_9.setText(_translate("Dialog", "Name"))
        self.presetForegroundButton.setText(_translate("Dialog", "..."))
        self.label_10.setText(_translate("Dialog", "Foreground"))
        self.label_11.setText(_translate("Dialog", "Background"))
        self.presetBackgroundButton.setText(_translate("Dialog", "..."))
        self.presetTable.setSortingEnabled(False)
        item = self.presetTable.horizontalHeaderItem(0)
        item.setText(_translate("Dialog", "Name"))
        item = self.presetTable.horizontalHeaderItem(1)
        item.setText(_translate("Dialog", "Foreground"))
        item = self.presetTable.horizontalHeaderItem(2)
        item.setText(_translate("Dialog", "Background"))
        self.presetNewButton.setText(_translate("Dialog", "New"))
        self.presetDeleteButton.setText(_translate("Dialog", "Delete"))
        self.label_14.setText(_translate("Dialog", "Width"))
        self.label_13.setText(_translate("Dialog", "Font size"))
        self.styleAllBox.setText(_translate("Dialog", "Apply to all"))
        self.label_5.setText(_translate("Dialog", "Default image name"))
        self.framelessBox.setText(_translate("Dialog", "Replace native window frame"))
        self.styleBackgroundButton.setText(_translate("Dialog", "..."))
        self.label_4.setText(_translate("Dialog", "Default text name"))
        self.label_15.setText(_translate("Dialog", "Background"))
        self.stylePreviewTextEdit.setPlainText(_translate("Dialog", "Beautiful is better than ugly, explicit is better than implicit, simple is better than complex, complex is better than complicated"))
        self.styleForegroundButton.setText(_translate("Dialog", "..."))
        self.label_16.setText(_translate("Dialog", "Foreground"))
        self.styleDefaultBox.setText(_translate("Dialog", "Set as default"))
        self.styleSizegripBox.setText(_translate("Dialog", "Enable size grip"))
        self.label_17.setText(_translate("Dialog", "Font family"))
        self.stylePinBox.setText(_translate("Dialog", "Enable pin"))
        self.label_12.setText(_translate("Dialog", "Height"))
        self.label_24.setText(_translate("Dialog", "Current file :"))
        self.cssRefreshButton.setText(_translate("Dialog", "..."))
        self.label_20.setText(_translate("Dialog", "Available elements"))
        self.label_22.setText(_translate("Dialog", "Selected elements"))
        self.label_21.setText(_translate("Dialog", "Available elements"))
        self.label_23.setText(_translate("Dialog", "Selected elements"))

