resource_registry:
# Create the registry only for roles with the word "Compute" in it. Like ComputeOvsDpdk, ComputeSriov, etc.,
{%- for role in roles -%}
{% if "Compute" in role.name %}
  OS::TripleO::{{role.name}}::PreNetworkConfig: ../extraconfig/pre_network/{{role.name.lower()}}-host_config_and_reboot.yaml
{%- endif -%}
{% endfor %}

#parameter_defaults:
  # Sample parameters for Compute and ComputeOvsDpdk roles
  #ComputeKernelArgs: ""
  #ComputeTunedProfileName: ""
  #ComputeHostCpuList: ""
  #ComputeOvsDpdkKernelArgs: ""
  #ComputeOvsDpdkTunedProfileName: ""
  #ComputeOvsDpdkHostCpuList: ""
