heat_template_version: ocata

description: Create networks to split out Overcloud traffic

resources:

  ExternalNetwork:
    type: OS::TripleO::Network::External

  InternalNetwork:
    type: OS::TripleO::Network::InternalApi

  StorageMgmtNetwork:
    type: OS::TripleO::Network::StorageMgmt

  StorageNetwork:
    type: OS::TripleO::Network::Storage

  TenantNetwork:
    type: OS::TripleO::Network::Tenant

  ManagementNetwork:
    type: OS::TripleO::Network::Management

  NetworkExtraConfig:
    type: OS::TripleO::Network::ExtraConfig
