
from setuptools import setup
setup(**{'author': 'puntonim',
 'author_email': 'foo@gmail.com',
 'classifiers': ['Development Status :: 3 - Alpha',
                 'Environment :: Web Environment',
                 'Intended Audience :: Developers',
                 'Operating System :: OS Independent',
                 'Programming Language :: Python',
                 'Programming Language :: Python :: 2',
                 'Programming Language :: Python :: 2.7',
                 'Programming Language :: Python :: 3',
                 'Programming Language :: Python :: 3.6',
                 'Topic :: Internet :: WWW/HTTP'],
 'description': 'ORCID service client',
 'include_package_data': True,
 'install_requires': ['pkgsettings<1.0.0,>=0.12.0'],
 'long_description': '# Inspire ORCID service client\n\nThis package is service client for ORCID API used in inspire-next.\n\n## Client usage\n\nTODO\n\n## Development\n\n```bash\n# Create a venv and install the requirements:\n$ make venv\n\n# Run isort and lint:\n$ make isort\n$ make lint\n\n# Run all the tests:\n$ make test  # tox against Python27 and Python36.\n$ tox -e py27  # tox against a specific Python version.\n$ pytest  # pytest against the active venv.\n\n# Run a specific test:\n$ make test/tests/test_orcid.py  # tox against Python27 and Python36.\n$ tox -e py27 -- tests/test_orcid.py  # tox against a specific Python version.\n$ pytest tests/test_orcid.py  # pytest against the active venv.\n```\n\nTo publish on PyPi:\n\n```bash\n# Edit .pypirc:\n$ cat $HOME/.pypirc\n[pypi]\nusername: myuser\npassword: mypass\n\n# Edit the version in `setup_gen.py`.\n\n# Finally compile and publish:\n$ make publish\n```\n',
 'name': 'inspire-service-orcid',
 'packages': ['inspire_services', 'inspire_services.orcid'],
 'tests_require': ['tox'],
 'url': 'https://github.com/puntonim/inspire-service-orcid',
 'version': '0.0.1a4',
 'zip_safe': False})
