
# This file was generated by 'versioneer.py' (0.15) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json
import sys

version_json = '''
{
 "dirty": false,
 "error": null,
 "full-revisionid": "6ff9b23ecb9cfaa7c24b779e88355257643e1550",
 "version": "0.12"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
