
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2018-07-31T01:33:39+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "6db80a59cb228ace84a251922a139fe3c3692e22",
 "version": "0.2"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
