#!/usr/bin/env python
# setup.py generated by flit for tools that don't yet use PEP 517

from distutils.core import setup

install_requires = \
['plotly>=3.0.0', 'numpy', 'pandas>=0.23.0']

setup(name='plotlywrapper',
      version='0.1.0',
      description='Plotlywrapper: to make easy plots easy to make.',
      author='Jacques Kvam',
      author_email='jwkvam+pypi@gmail.com',
      url='https://github.com/jwkvam/plotlywrapper',
      py_modules=['plotlywrapper'],
      install_requires=install_requires,
      python_requires='>=3.5',
     )
