
# This file was generated by 'versioneer.py' (0.15) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json
import sys

version_json = '''
{
 "dirty": false,
 "error": null,
 "full-revisionid": "1a563cc0a4329d81efbbbbca71e51553fa5d0d84",
 "version": "v0.1.1-alpha.post.dev88"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
