---
- include: register.yml
  when: inventory_hostname in groups['senlin-api']

- include: config.yml
  when: inventory_hostname in groups['senlin-api'] or
        inventory_hostname in groups['senlin-engine']

- include: clone.yml
  when: senlin_dev_mode | bool

- include: bootstrap.yml
  when: inventory_hostname in groups['senlin-api']

- name: Flush handlers
  meta: flush_handlers
