# This file is part of dataget.
# https://github.com/cgarciae/dataget

# Licensed under the MIT license:
# http://www.opensource.org/licenses/MIT-license
# Copyright (c) 2017, cgarciae <cgarcia.e88@gmail.com>

language: python

python:
    - "2.7"
    - "3.4"
    - "pypy"

install:
    # install python requirements
    - make setup

script:
    # run tests
    - make test
