
# This file was generated by 'versioneer.py' (0.17) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2018-07-22T02:01:09-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "092701d314a53ccddede0e5e3aaa2ab7dda1a626",
 "version": "3.11.4"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
