# coding: utf-8

"""
    Dash API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: v1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import dash_api
from dash_api.api.event_type_api import EventTypeApi  # noqa: E501
from dash_api.rest import ApiException


class TestEventTypeApi(unittest.TestCase):
    """EventTypeApi unit test stubs"""

    def setUp(self):
        self.api = dash_api.api.event_type_api.EventTypeApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_api_events_types_get(self):
        """Test case for api_events_types_get

        """
        pass


if __name__ == '__main__':
    unittest.main()
