# coding: utf-8

"""
    Dash API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: v1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import dash_api
from dash_api.api.environment_api import EnvironmentApi  # noqa: E501
from dash_api.rest import ApiException


class TestEnvironmentApi(unittest.TestCase):
    """EnvironmentApi unit test stubs"""

    def setUp(self):
        self.api = dash_api.api.environment_api.EnvironmentApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_api_environment_get(self):
        """Test case for api_environment_get

        """
        pass


if __name__ == '__main__':
    unittest.main()
