sudo: required

services:
  - docker

language: python

matrix:
  include:
    - python: 2.7
      env: TOXENV=py27
    - python: 3.5
      env: TOXENV=py35

cache:
  directories:
    - .tox/py27
    - .tox/py35

install:
  - pip install tox

script:
  tox

deploy:
  provider: script
  script: ./deploy
  on:
    tags: true
    all_branches: true
    condition: "(\"$TOXENV\" = \"py35\") && (\"$TRAVIS_TAG\" = \"v$(python setup.py --version)\")"
