- project:
    check:
      jobs:
        - monasca-tempest-python-influxdb:
            voting: false
        - monasca-tempest-java-influxdb:
            voting: false
        - openstack-tox-lower-constraints
    gate:
      jobs:
        - openstack-tox-lower-constraints
