
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2018-07-19T15:39:47-0500",
 "dirty": false,
 "error": null,
 "full-revisionid": "94d5f63f0df834cd408b761967b1c51bc648888e",
 "version": "0.0.23"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
