# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'messenger.ui'
#
# Created by: PyQt5 UI code generator 5.11.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(640, 691)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.ContactsContLabel = QtWidgets.QLabel(self.centralwidget)
        self.ContactsContLabel.setGeometry(QtCore.QRect(324, 106, 81, 20))
        self.ContactsContLabel.setObjectName("ContactsContLabel")
        self.sendMessagePushButton = QtWidgets.QPushButton(self.centralwidget)
        self.sendMessagePushButton.setGeometry(QtCore.QRect(480, 557, 101, 31))
        self.sendMessagePushButton.setObjectName("sendMessagePushButton")
        self.contactsListWidget = QtWidgets.QListWidget(self.centralwidget)
        self.contactsListWidget.setGeometry(QtCore.QRect(320, 130, 261, 361))
        self.contactsListWidget.setObjectName("contactsListWidget")
        self.deleteContactPushBotton = QtWidgets.QPushButton(self.centralwidget)
        self.deleteContactPushBotton.setGeometry(QtCore.QRect(320, 500, 261, 28))
        self.deleteContactPushBotton.setObjectName("deleteContactPushBotton")
        self.messageTextEdit = QtWidgets.QTextEdit(self.centralwidget)
        self.messageTextEdit.setGeometry(QtCore.QRect(33, 546, 431, 51))
        self.messageTextEdit.setObjectName("messageTextEdit")
        self.addContactTextEdit = QtWidgets.QTextEdit(self.centralwidget)
        self.addContactTextEdit.setGeometry(QtCore.QRect(320, 70, 201, 31))
        self.addContactTextEdit.setObjectName("addContactTextEdit")
        self.ChatBrowser = QtWidgets.QTextBrowser(self.centralwidget)
        self.ChatBrowser.setGeometry(QtCore.QRect(35, 100, 261, 421))
        self.ChatBrowser.setObjectName("ChatBrowser")
        self.addContactPushBotton = QtWidgets.QPushButton(self.centralwidget)
        self.addContactPushBotton.setGeometry(QtCore.QRect(530, 70, 51, 31))
        self.addContactPushBotton.setObjectName("addContactPushBotton")
        self.userNameLabel = QtWidgets.QLabel(self.centralwidget)
        self.userNameLabel.setGeometry(QtCore.QRect(160, 10, 321, 20))
        self.userNameLabel.setTextFormat(QtCore.Qt.AutoText)
        self.userNameLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.userNameLabel.setObjectName("userNameLabel")
        self.chatTextLabel = QtWidgets.QLabel(self.centralwidget)
        self.chatTextLabel.setGeometry(QtCore.QRect(40, 70, 251, 20))
        self.chatTextLabel.setObjectName("chatTextLabel")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 640, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Messenger"))
        self.ContactsContLabel.setText(_translate("MainWindow", "Total: "))
        self.sendMessagePushButton.setText(_translate("MainWindow", "Send Message"))
        self.deleteContactPushBotton.setText(_translate("MainWindow", "Delete"))
        self.messageTextEdit.setPlaceholderText(_translate("MainWindow", "type message here"))
        self.addContactTextEdit.setPlaceholderText(_translate("MainWindow", "contact name to add"))
        self.addContactPushBotton.setText(_translate("MainWindow", "Add"))
        self.userNameLabel.setText(_translate("MainWindow", "Self"))
        self.chatTextLabel.setText(_translate("MainWindow", "Chat With:"))


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.setWindowModality(QtCore.Qt.NonModal)
        Dialog.resize(336, 595)
        Dialog.setFocusPolicy(QtCore.Qt.TabFocus)
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(70, 120, 195, 16))
        self.label.setObjectName("label")
        self.widget = QtWidgets.QWidget(Dialog)
        self.widget.setGeometry(QtCore.QRect(60, 190, 208, 375))
        self.widget.setObjectName("widget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setObjectName("formLayout")
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.formLayout.setItem(0, QtWidgets.QFormLayout.FieldRole, spacerItem)
        self.loginTextEdit = QtWidgets.QLineEdit(self.widget)
        self.loginTextEdit.setObjectName("loginTextEdit")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.loginTextEdit)
        self.passwordLabel = QtWidgets.QLabel(self.widget)
        self.passwordLabel.setObjectName("passwordLabel")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.passwordLabel)
        self.passwordTextEdit = QtWidgets.QLineEdit(self.widget)
        self.passwordTextEdit.setEchoMode(QtWidgets.QLineEdit.Password)
        self.passwordTextEdit.setPlaceholderText("")
        self.passwordTextEdit.setObjectName("passwordTextEdit")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.passwordTextEdit)
        self.loginLabel = QtWidgets.QLabel(self.widget)
        self.loginLabel.setObjectName("loginLabel")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.loginLabel)
        self.verticalLayout.addLayout(self.formLayout)
        self.formLayout_2 = QtWidgets.QFormLayout()
        self.formLayout_2.setObjectName("formLayout_2")
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.formLayout_2.setItem(0, QtWidgets.QFormLayout.FieldRole, spacerItem1)
        self.loginPushButton = QtWidgets.QPushButton(self.widget)
        self.loginPushButton.setObjectName("loginPushButton")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.loginPushButton)
        self.joinPushButton = QtWidgets.QPushButton(self.widget)
        self.joinPushButton.setObjectName("joinPushButton")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.joinPushButton)
        self.cancelPushButton = QtWidgets.QPushButton(self.widget)
        self.cancelPushButton.setObjectName("cancelPushButton")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.SpanningRole, self.cancelPushButton)
        self.verticalLayout.addLayout(self.formLayout_2)
        self.formLayout_3 = QtWidgets.QFormLayout()
        self.formLayout_3.setObjectName("formLayout_3")
        self.hostLabel = QtWidgets.QLabel(self.widget)
        self.hostLabel.setObjectName("hostLabel")
        self.formLayout_3.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.hostLabel)
        self.portLabel = QtWidgets.QLabel(self.widget)
        self.portLabel.setObjectName("portLabel")
        self.formLayout_3.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.portLabel)
        self.hostTextEdit = QtWidgets.QLineEdit(self.widget)
        self.hostTextEdit.setObjectName("hostTextEdit")
        self.formLayout_3.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.hostTextEdit)
        self.portTextEdit = QtWidgets.QLineEdit(self.widget)
        self.portTextEdit.setObjectName("portTextEdit")
        self.formLayout_3.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.portTextEdit)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.formLayout_3.setItem(0, QtWidgets.QFormLayout.FieldRole, spacerItem2)
        self.verticalLayout.addLayout(self.formLayout_3)
        self.label.raise_()
        self.loginLabel.raise_()
        self.passwordLabel.raise_()

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)
        Dialog.setTabOrder(self.joinPushButton, self.loginPushButton)
        Dialog.setTabOrder(self.loginPushButton, self.cancelPushButton)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Welcome"))
        self.label.setText(_translate("Dialog", "here will be some picture... I gess"))
        self.passwordLabel.setText(_translate("Dialog", "Password:"))
        self.loginLabel.setText(_translate("Dialog", "Login:"))
        self.loginPushButton.setText(_translate("Dialog", "Login"))
        self.joinPushButton.setText(_translate("Dialog", "Join"))
        self.cancelPushButton.setText(_translate("Dialog", "Cancel"))
        self.hostLabel.setText(_translate("Dialog", "host: "))
        self.portLabel.setText(_translate("Dialog", "port:"))

