
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2018-07-20T19:02:09-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "dc03db6f3d1c455828fcdb68f857c70e220288c3",
 "version": "0.4.8.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
