
# This file was generated by 'versioneer.py' (0.15) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json
import sys

version_json = '''
{
 "dirty": false,
 "error": null,
 "full-revisionid": "f73a31cce738c242e4f88ad4b3923d0ad9168a3e",
 "version": "1971"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
