
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2018-08-07T14:20:24-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "f97d5fd0f46c1f4884db3a1ea0c1c6c5cee31f74",
 "version": "0.6.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
