##############################################################################
#  I prefer if you do not use this file, it exists for convenience
#  the better should be to export sensitive data as environment variables
#  ex:
#  $ export QUOKKA_SECRET_KEY='5a105457-3e3e-4d2e-ba7c-4c8c31be1bc5'
#  $ export QUOKKA_DB__PASSWORD='my-password'
#  $ export QUOKKA_DB__USERNAME='admin'
#  QUOKKA_ = Prefix for any quokka settings
#  DB = The `DB` settings variable used by quokka
#  __USERNAME = username value (note the __ double underline)
#
##############################################################################
# ONLY IF EXPORTING ENV VARS IS NOT USEFUL FOR YOU, DEFINE INFO BELOW
# Important! this file must be in .gitignore to avoid pushing to repo
##############################################################################

QUOKKA:
  SECRET_KEY: 'secret-key-here'
