
anycsv:
  NO_SNIFF_LINES: 100
  MAX_FILE_SIZE: -1 # disabled by default, value in bytes

  SKIP_GUESS_ENCODING: False

  DEFAULT_ENCODING: utf-8

  ENC_PRIORITY:
    - lib_chardet
    - header
    - default

pyyacp:
  BATCH_SIZE: 100

  DEFAULT_STRUCTURE_DETECTOR: pyyacp.table_structure_helper.AdvanceStructureDetector


  DEFAULT_PROFILERS:
    - pyyacp.profiler.column_stats_profiler.ColumnStatsProfiler
    - pyyacp.profiler.colum_pattern_profiler.ColumnPatternProfiler
    - pyyacp.profiler.data_type_detection.DataTypeDetection
    - pyyacp.profiler.datatype_interpretation.DataTypeInterpretation
    - pyyacp.profiler.distributions.CharacterDistributionProfiler
    - pyyacp.profiler.distributions.BenfordsLawDistribution
    - pyyacp.profiler.cset_detection.CharacterSetProfiler
    - pyyacp.profiler.fdprofiler.FDProfiler

  MAX_TABLES: 2
  RAISE_ERROR: true
