# Generated by Django 2.0.7 on 2018-07-18 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tokenservice', '0003_auto_20180718_1316'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tokenapp',
            name='token',
            field=models.SlugField(editable=False, max_length=30, unique=True),
        ),
    ]
