
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2018-08-04T18:15:14+0300",
 "dirty": false,
 "error": null,
 "full-revisionid": "588167af990fcc385e473962f678a42596073c19",
 "version": "0.0.66"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
