heat_template_version: ocata

description: >
  OpenStack Glance Registry service, disabled since ocata

parameters:
  ServiceNetMap:
    default: {}
    description: Mapping of service_name -> network name. Typically set
                 via parameter_defaults in the resource registry.  This
                 mapping overrides those in ServiceNetMapDefaults.
    type: json
  DefaultPasswords:
    default: {}
    type: json
  EndpointMap:
    default: {}
    description: Mapping of service endpoint -> protocol. Typically set
                 via parameter_defaults in the resource registry.
    type: json

outputs:
  role_data:
    description: Role data for the disabled Glance Registry role.
    value:
      service_name: glance_registry
      upgrade_tasks:
        - name: Stop and disable glance_registry service on upgrade
          tags: step1
          service: name=openstack-glance-registry state=stopped enabled=no
