---

dependencies:

  - role: debops.secret

galaxy_info:

  role_name: 'redis'
  author: 'Nick Janetakis, Maciej Delmanowski'
  description: 'Install and manage Redis cluster'
  company: 'DebOps'
  license: 'GPL-3.0'
  min_ansible_version: '2.2.0'
  platforms:
    - name: Ubuntu
      versions:
        - precise
        - quantal
        - raring
        - saucy
        - trusty
    - name: Debian
      versions:
        - wheezy
        - jessie
  galaxy_tags:
    - 'database'
    - 'nosql'
    - 'system'
    - 'redis'
    - 'sentinel'
