# coding: utf-8

# flake8: noqa

"""
    Dyspatch API

    # Introduction  The Dyspatch API is based on the REST paradigm, and features resource based URLs with standard HTTP response codes to indicate errors. We use standard HTTP authentication and request verbs, and all responses are JSON formatted. See our [Implementation Guide](https://docs.dyspatch.io/development/implementing_dyspatch/) for more details on how to implement Dyspatch.   # noqa: E501

    OpenAPI spec version: 2018.02
    Contact: support@dyspatch.io
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

# import apis into sdk package
from swagger_client.api.localizations_api import LocalizationsApi
from swagger_client.api.templates_api import TemplatesApi

# import ApiClient
from swagger_client.api_client import ApiClient
from swagger_client.configuration import Configuration
# import models into sdk package
from swagger_client.models.api_error import APIError
from swagger_client.models.compiled_read import CompiledRead
from swagger_client.models.created_at import CreatedAt
from swagger_client.models.cursor import Cursor
from swagger_client.models.language_id import LanguageId
from swagger_client.models.localization_draft_meta_read import LocalizationDraftMetaRead
from swagger_client.models.localization_draft_read import LocalizationDraftRead
from swagger_client.models.localization_draft_url import LocalizationDraftUrl
from swagger_client.models.localization_id import LocalizationId
from swagger_client.models.localization_meta_read import LocalizationMetaRead
from swagger_client.models.localization_name import LocalizationName
from swagger_client.models.localization_read import LocalizationRead
from swagger_client.models.localization_url import LocalizationUrl
from swagger_client.models.template_description import TemplateDescription
from swagger_client.models.template_draft_id import TemplateDraftId
from swagger_client.models.template_draft_meta_read import TemplateDraftMetaRead
from swagger_client.models.template_draft_read import TemplateDraftRead
from swagger_client.models.template_draft_url import TemplateDraftUrl
from swagger_client.models.template_drafts_read import TemplateDraftsRead
from swagger_client.models.template_id import TemplateId
from swagger_client.models.template_meta_read import TemplateMetaRead
from swagger_client.models.template_name import TemplateName
from swagger_client.models.template_read import TemplateRead
from swagger_client.models.template_url import TemplateUrl
from swagger_client.models.templates_read import TemplatesRead
from swagger_client.models.updated_at import UpdatedAt
