
anycsv:
  NO_SNIFF_LINES: 100
  MAX_FILE_SIZE: -1 # disabled by default, value in bytes

  SKIP_GUESS_ENCODING: False

  DEFAULT_ENCODING: utf-8

  ENC_PRIORITY:
    - lib_chardet
    - header
    - default
