repos:
  - repo: https://github.com/ambv/black
    rev: stable
    hooks:
      - id: black
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v1.4.0
    hooks:
      - id: check-merge-conflict
      - id: debug-statements
      - id: end-of-file-fixer
      - id: flake8
        language_version: python2.7
      - id: trailing-whitespace
  - repo: https://notabug.org/mjakob/pre-commit-check-manifest
    rev: v0.1.0
    hooks:
      - id: check-manifest
