
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2018-07-19T14:47:05-0700",
 "dirty": false,
 "error": null,
 "full-revisionid": "fed18e2e51c459d4927221ca2f2c7607eefdb22b",
 "version": "0.1.0-alpha.1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
