__title__ = 'Flask-ADFS'
__description__ = 'User session management for Flask'
__url__ = 'https://github.com/johnpickerill/flask-login'
__version_info__ = ('0', '1', '19')
__version__ = '.'.join(__version_info__)
__author__ = 'John Pickerill'
__author_email__ = 'john.pickerill@landregistry.gov.uk'
__maintainer__ = 'Land Registry'
__license__ = 'MIT'
__copyright__ = '(c) 2017, 2018 by John Pickerill'
