# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\programming\projects\randovania\randovania/gui\iso_management_window.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_ISOManagementWindow(object):
    def setupUi(self, ISOManagementWindow):
        ISOManagementWindow.setObjectName("ISOManagementWindow")
        ISOManagementWindow.resize(852, 607)
        self.centralWidget = QtWidgets.QWidget(ISOManagementWindow)
        self.centralWidget.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.centralWidget.setObjectName("centralWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralWidget)
        self.gridLayout.setContentsMargins(11, 11, 11, 11)
        self.gridLayout.setSpacing(6)
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtWidgets.QLabel(self.centralWidget)
        self.label.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.isoBox = QtWidgets.QGroupBox(self.centralWidget)
        self.isoBox.setMaximumSize(QtCore.QSize(16777215, 120))
        self.isoBox.setObjectName("isoBox")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.isoBox)
        self.gridLayout_4.setContentsMargins(11, 11, 11, 11)
        self.gridLayout_4.setSpacing(6)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.loadIsoButton = QtWidgets.QPushButton(self.isoBox)
        self.loadIsoButton.setObjectName("loadIsoButton")
        self.gridLayout_4.addWidget(self.loadIsoButton, 0, 0, 1, 1)
        self.packageIsoButton = QtWidgets.QPushButton(self.isoBox)
        self.packageIsoButton.setObjectName("packageIsoButton")
        self.gridLayout_4.addWidget(self.packageIsoButton, 0, 1, 1, 1)
        self.gridLayout.addWidget(self.isoBox, 4, 0, 1, 2)
        self.filesBox = QtWidgets.QGroupBox(self.centralWidget)
        self.filesBox.setMaximumSize(QtCore.QSize(16777215, 80))
        self.filesBox.setObjectName("filesBox")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.filesBox)
        self.gridLayout_3.setContentsMargins(11, 11, 11, 11)
        self.gridLayout_3.setSpacing(6)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.changeFilesLocationButton = QtWidgets.QPushButton(self.filesBox)
        self.changeFilesLocationButton.setObjectName("changeFilesLocationButton")
        self.gridLayout_3.addWidget(self.changeFilesLocationButton, 1, 0, 1, 1)
        self.deleteFilesButton = QtWidgets.QPushButton(self.filesBox)
        self.deleteFilesButton.setObjectName("deleteFilesButton")
        self.gridLayout_3.addWidget(self.deleteFilesButton, 1, 2, 1, 1)
        self.resetFilesLocationButton = QtWidgets.QPushButton(self.filesBox)
        self.resetFilesLocationButton.setObjectName("resetFilesLocationButton")
        self.gridLayout_3.addWidget(self.resetFilesLocationButton, 1, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.filesBox)
        self.label_2.setEnabled(True)
        self.label_2.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.label_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_2.setObjectName("label_2")
        self.gridLayout_3.addWidget(self.label_2, 0, 0, 1, 1)
        self.filesLocation = QtWidgets.QLabel(self.filesBox)
        self.filesLocation.setObjectName("filesLocation")
        self.gridLayout_3.addWidget(self.filesLocation, 0, 1, 1, 2)
        self.gridLayout.addWidget(self.filesBox, 2, 0, 1, 2)
        self.progress_box = QtWidgets.QGroupBox(self.centralWidget)
        self.progress_box.setObjectName("progress_box")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.progress_box)
        self.gridLayout_2.setContentsMargins(11, 11, 11, 11)
        self.gridLayout_2.setSpacing(6)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.progressBar = QtWidgets.QProgressBar(self.progress_box)
        self.progressBar.setProperty("value", 0)
        self.progressBar.setInvertedAppearance(False)
        self.progressBar.setObjectName("progressBar")
        self.gridLayout_2.addWidget(self.progressBar, 0, 0, 1, 2)
        self.progressLabel = QtWidgets.QLabel(self.progress_box)
        self.progressLabel.setMaximumSize(QtCore.QSize(16777215, 20))
        self.progressLabel.setText("")
        self.progressLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.progressLabel.setObjectName("progressLabel")
        self.gridLayout_2.addWidget(self.progressLabel, 1, 1, 1, 1)
        self.stopBackgroundProcessButton = QtWidgets.QPushButton(self.progress_box)
        self.stopBackgroundProcessButton.setEnabled(False)
        self.stopBackgroundProcessButton.setCheckable(False)
        self.stopBackgroundProcessButton.setFlat(False)
        self.stopBackgroundProcessButton.setObjectName("stopBackgroundProcessButton")
        self.gridLayout_2.addWidget(self.stopBackgroundProcessButton, 1, 0, 1, 1)
        self.gridLayout.addWidget(self.progress_box, 6, 0, 1, 2)
        self.randomizer_box = QtWidgets.QGroupBox(self.centralWidget)
        self.randomizer_box.setObjectName("randomizer_box")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.randomizer_box)
        self.gridLayout_5.setContentsMargins(11, 11, 11, 11)
        self.gridLayout_5.setSpacing(6)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.layout_identifier_label = QtWidgets.QLabel(self.randomizer_box)
        self.layout_identifier_label.setObjectName("layout_identifier_label")
        self.gridLayout_5.addWidget(self.layout_identifier_label, 0, 0, 1, 1)
        self.apply_layout_button = QtWidgets.QPushButton(self.randomizer_box)
        self.apply_layout_button.setObjectName("apply_layout_button")
        self.gridLayout_5.addWidget(self.apply_layout_button, 0, 1, 1, 1)
        self.current_seed_edit = QtWidgets.QLineEdit(self.randomizer_box)
        self.current_seed_edit.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.current_seed_edit.setInputMethodHints(QtCore.Qt.ImhDigitsOnly|QtCore.Qt.ImhPreferNumbers)
        self.current_seed_edit.setObjectName("current_seed_edit")
        self.gridLayout_5.addWidget(self.current_seed_edit, 1, 0, 1, 1)
        self.apply_seed_button = QtWidgets.QPushButton(self.randomizer_box)
        self.apply_seed_button.setObjectName("apply_seed_button")
        self.gridLayout_5.addWidget(self.apply_seed_button, 1, 1, 1, 1)
        self.remove_hud_popup = QtWidgets.QCheckBox(self.randomizer_box)
        self.remove_hud_popup.setObjectName("remove_hud_popup")
        self.gridLayout_5.addWidget(self.remove_hud_popup, 2, 0, 1, 1)
        self.gridLayout.addWidget(self.randomizer_box, 1, 0, 1, 2)
        ISOManagementWindow.setCentralWidget(self.centralWidget)
        self.menuBar = QtWidgets.QMenuBar(ISOManagementWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 852, 21))
        self.menuBar.setObjectName("menuBar")
        ISOManagementWindow.setMenuBar(self.menuBar)

        self.retranslateUi(ISOManagementWindow)
        QtCore.QMetaObject.connectSlotsByName(ISOManagementWindow)

    def retranslateUi(self, ISOManagementWindow):
        _translate = QtCore.QCoreApplication.translate
        ISOManagementWindow.setWindowTitle(_translate("ISOManagementWindow", "Hello, world!"))
        self.label.setText(_translate("ISOManagementWindow", "<html><head/><body><p>In order to be able to modify the contents of a Metroid Prime 2 ISO, it must be on an extracted format.</p><p>By default, Randovania utilizes a system provided application directory but you can customize that.</p></body></html>"))
        self.isoBox.setTitle(_translate("ISOManagementWindow", "ISO Operations"))
        self.loadIsoButton.setToolTip(_translate("ISOManagementWindow", "Extracts an Game ISO to the current files location"))
        self.loadIsoButton.setText(_translate("ISOManagementWindow", "Load ISO"))
        self.packageIsoButton.setToolTip(_translate("ISOManagementWindow", "Creates an ISO based on the contents of the current files location"))
        self.packageIsoButton.setText(_translate("ISOManagementWindow", "Package as ISO"))
        self.filesBox.setTitle(_translate("ISOManagementWindow", "File Location"))
        self.changeFilesLocationButton.setText(_translate("ISOManagementWindow", "Change"))
        self.deleteFilesButton.setText(_translate("ISOManagementWindow", "Delete contents"))
        self.resetFilesLocationButton.setText(_translate("ISOManagementWindow", "Use Default Location"))
        self.label_2.setText(_translate("ISOManagementWindow", "Current Files Location:"))
        self.filesLocation.setText(_translate("ISOManagementWindow", "<CHANGE ME>"))
        self.progress_box.setTitle(_translate("ISOManagementWindow", "Progress"))
        self.stopBackgroundProcessButton.setText(_translate("ISOManagementWindow", "Stop"))
        self.randomizer_box.setTitle(_translate("ISOManagementWindow", "Game Patching"))
        self.layout_identifier_label.setText(_translate("ISOManagementWindow", "No layout has been selected. Please select one in the `History` tab."))
        self.apply_layout_button.setText(_translate("ISOManagementWindow", "Randomize game files with layout"))
        self.current_seed_edit.setPlaceholderText(_translate("ISOManagementWindow", "Seed number. For item loss / elevator randomization, check the Configuration tab"))
        self.apply_seed_button.setText(_translate("ISOManagementWindow", "Randomize game files with seed"))
        self.remove_hud_popup.setToolTip(_translate("ISOManagementWindow", "The \"HUD Popup\" is the popup that appears after you collect an item"))
        self.remove_hud_popup.setText(_translate("ISOManagementWindow", "Remove HUD popup"))

