# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\programming\projects\randovania\randovania/gui\manage_game_window.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_ManageGameWindow(object):
    def setupUi(self, ManageGameWindow):
        ManageGameWindow.setObjectName("ManageGameWindow")
        ManageGameWindow.resize(852, 607)
        self.centralWidget = QtWidgets.QWidget(ManageGameWindow)
        self.centralWidget.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.centralWidget.setObjectName("centralWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralWidget)
        self.gridLayout.setContentsMargins(11, 11, 11, 11)
        self.gridLayout.setSpacing(6)
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtWidgets.QLabel(self.centralWidget)
        self.label.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.randomizerBox = QtWidgets.QGroupBox(self.centralWidget)
        self.randomizerBox.setObjectName("randomizerBox")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.randomizerBox)
        self.gridLayout_5.setContentsMargins(11, 11, 11, 11)
        self.gridLayout_5.setSpacing(6)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.currentSeedEdit = QtWidgets.QLineEdit(self.randomizerBox)
        self.currentSeedEdit.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.currentSeedEdit.setInputMethodHints(QtCore.Qt.ImhDigitsOnly|QtCore.Qt.ImhPreferNumbers)
        self.currentSeedEdit.setObjectName("currentSeedEdit")
        self.gridLayout_5.addWidget(self.currentSeedEdit, 2, 1, 1, 1)
        self.applyLayoutButton = QtWidgets.QPushButton(self.randomizerBox)
        self.applyLayoutButton.setObjectName("applyLayoutButton")
        self.gridLayout_5.addWidget(self.applyLayoutButton, 2, 2, 1, 1)
        self.generateLayoutButton = QtWidgets.QPushButton(self.randomizerBox)
        self.generateLayoutButton.setObjectName("generateLayoutButton")
        self.gridLayout_5.addWidget(self.generateLayoutButton, 1, 1, 1, 2)
        self.gridLayout.addWidget(self.randomizerBox, 2, 0, 1, 1)
        self.isoBox = QtWidgets.QGroupBox(self.centralWidget)
        self.isoBox.setMaximumSize(QtCore.QSize(16777215, 120))
        self.isoBox.setObjectName("isoBox")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.isoBox)
        self.gridLayout_4.setContentsMargins(11, 11, 11, 11)
        self.gridLayout_4.setSpacing(6)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.loadIsoButton = QtWidgets.QPushButton(self.isoBox)
        self.loadIsoButton.setObjectName("loadIsoButton")
        self.gridLayout_4.addWidget(self.loadIsoButton, 0, 0, 1, 1)
        self.packageIsoButton = QtWidgets.QPushButton(self.isoBox)
        self.packageIsoButton.setObjectName("packageIsoButton")
        self.gridLayout_4.addWidget(self.packageIsoButton, 1, 0, 1, 1)
        self.gridLayout.addWidget(self.isoBox, 3, 0, 1, 1)
        self.seedGenerationBox = QtWidgets.QGroupBox(self.centralWidget)
        self.seedGenerationBox.setObjectName("seedGenerationBox")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.seedGenerationBox)
        self.gridLayout_2.setContentsMargins(11, 11, 11, 11)
        self.gridLayout_2.setSpacing(6)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.progressBar = QtWidgets.QProgressBar(self.seedGenerationBox)
        self.progressBar.setProperty("value", 0)
        self.progressBar.setInvertedAppearance(False)
        self.progressBar.setObjectName("progressBar")
        self.gridLayout_2.addWidget(self.progressBar, 0, 0, 1, 2)
        self.stopBackgroundProcessButton = QtWidgets.QPushButton(self.seedGenerationBox)
        self.stopBackgroundProcessButton.setEnabled(False)
        self.stopBackgroundProcessButton.setCheckable(False)
        self.stopBackgroundProcessButton.setFlat(False)
        self.stopBackgroundProcessButton.setObjectName("stopBackgroundProcessButton")
        self.gridLayout_2.addWidget(self.stopBackgroundProcessButton, 1, 0, 1, 1)
        self.progressLabel = QtWidgets.QLabel(self.seedGenerationBox)
        self.progressLabel.setMaximumSize(QtCore.QSize(16777215, 20))
        self.progressLabel.setText("")
        self.progressLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.progressLabel.setObjectName("progressLabel")
        self.gridLayout_2.addWidget(self.progressLabel, 1, 1, 1, 1)
        self.gridLayout.addWidget(self.seedGenerationBox, 5, 0, 1, 2)
        self.filesBox = QtWidgets.QGroupBox(self.centralWidget)
        self.filesBox.setMaximumSize(QtCore.QSize(16777215, 80))
        self.filesBox.setObjectName("filesBox")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.filesBox)
        self.gridLayout_3.setContentsMargins(11, 11, 11, 11)
        self.gridLayout_3.setSpacing(6)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.changeFilesLocationButton = QtWidgets.QPushButton(self.filesBox)
        self.changeFilesLocationButton.setObjectName("changeFilesLocationButton")
        self.gridLayout_3.addWidget(self.changeFilesLocationButton, 1, 0, 1, 1)
        self.resetFilesLocationButton = QtWidgets.QPushButton(self.filesBox)
        self.resetFilesLocationButton.setObjectName("resetFilesLocationButton")
        self.gridLayout_3.addWidget(self.resetFilesLocationButton, 1, 1, 1, 1)
        self.deleteFilesButton = QtWidgets.QPushButton(self.filesBox)
        self.deleteFilesButton.setObjectName("deleteFilesButton")
        self.gridLayout_3.addWidget(self.deleteFilesButton, 1, 2, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.filesBox)
        self.label_2.setEnabled(True)
        self.label_2.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.label_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_2.setObjectName("label_2")
        self.gridLayout_3.addWidget(self.label_2, 0, 0, 1, 1)
        self.filesLocation = QtWidgets.QLabel(self.filesBox)
        self.filesLocation.setObjectName("filesLocation")
        self.gridLayout_3.addWidget(self.filesLocation, 0, 1, 1, 2)
        self.gridLayout.addWidget(self.filesBox, 1, 0, 1, 2)
        ManageGameWindow.setCentralWidget(self.centralWidget)
        self.menuBar = QtWidgets.QMenuBar(ManageGameWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 852, 21))
        self.menuBar.setObjectName("menuBar")
        ManageGameWindow.setMenuBar(self.menuBar)

        self.retranslateUi(ManageGameWindow)
        QtCore.QMetaObject.connectSlotsByName(ManageGameWindow)

    def retranslateUi(self, ManageGameWindow):
        _translate = QtCore.QCoreApplication.translate
        ManageGameWindow.setWindowTitle(_translate("ManageGameWindow", "Hello, world!"))
        self.label.setText(_translate("ManageGameWindow", "<html><head/><body><p>In order to be able to modify the contents of a Metroid Prime 2 ISO, it must be on an extracted format.</p><p>By default, Randovania utilizes a system provided application directory but you can customize that.</p></body></html>"))
        self.randomizerBox.setTitle(_translate("ManageGameWindow", "Randomizer"))
        self.applyLayoutButton.setText(_translate("ManageGameWindow", "Apply"))
        self.generateLayoutButton.setText(_translate("ManageGameWindow", "Generate new layout"))
        self.isoBox.setTitle(_translate("ManageGameWindow", "ISO Operations"))
        self.loadIsoButton.setToolTip(_translate("ManageGameWindow", "Extracts an Game ISO to the current files location"))
        self.loadIsoButton.setText(_translate("ManageGameWindow", "Load ISO"))
        self.packageIsoButton.setToolTip(_translate("ManageGameWindow", "Creates an ISO based on the contents of the current files location"))
        self.packageIsoButton.setText(_translate("ManageGameWindow", "Package as ISO"))
        self.seedGenerationBox.setTitle(_translate("ManageGameWindow", "Progress"))
        self.stopBackgroundProcessButton.setText(_translate("ManageGameWindow", "Stop"))
        self.filesBox.setTitle(_translate("ManageGameWindow", "File Location"))
        self.changeFilesLocationButton.setText(_translate("ManageGameWindow", "Change"))
        self.resetFilesLocationButton.setText(_translate("ManageGameWindow", "Use Default Location"))
        self.deleteFilesButton.setText(_translate("ManageGameWindow", "Delete contents"))
        self.label_2.setText(_translate("ManageGameWindow", "Current Files Location:"))
        self.filesLocation.setText(_translate("ManageGameWindow", "<CHANGE ME>"))

