# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\programming\projects\randovania\randovania/gui\seed_searcher_window.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_SeedSearcherWindow(object):
    def setupUi(self, SeedSearcherWindow):
        SeedSearcherWindow.setObjectName("SeedSearcherWindow")
        SeedSearcherWindow.resize(852, 607)
        self.centralWidget = QtWidgets.QWidget(SeedSearcherWindow)
        self.centralWidget.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.centralWidget.setObjectName("centralWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralWidget)
        self.gridLayout.setContentsMargins(11, 11, 11, 11)
        self.gridLayout.setSpacing(6)
        self.gridLayout.setObjectName("gridLayout")
        self.excludedPickupsBox = QtWidgets.QGroupBox(self.centralWidget)
        self.excludedPickupsBox.setObjectName("excludedPickupsBox")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.excludedPickupsBox)
        self.gridLayout_4.setContentsMargins(11, 11, 11, 11)
        self.gridLayout_4.setSpacing(6)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.filterPickupsEdit = QtWidgets.QLineEdit(self.excludedPickupsBox)
        self.filterPickupsEdit.setStatusTip("")
        self.filterPickupsEdit.setInputMethodHints(QtCore.Qt.ImhNone)
        self.filterPickupsEdit.setObjectName("filterPickupsEdit")
        self.gridLayout_4.addWidget(self.filterPickupsEdit, 1, 1, 1, 1)
        self.clearExcludedPickups = QtWidgets.QPushButton(self.excludedPickupsBox)
        self.clearExcludedPickups.setObjectName("clearExcludedPickups")
        self.gridLayout_4.addWidget(self.clearExcludedPickups, 1, 2, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.excludedPickupsBox)
        self.label_3.setObjectName("label_3")
        self.gridLayout_4.addWidget(self.label_3, 1, 0, 1, 1)
        self.excludedItemsScrollArea = QtWidgets.QScrollArea(self.excludedPickupsBox)
        self.excludedItemsScrollArea.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.excludedItemsScrollArea.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContents)
        self.excludedItemsScrollArea.setWidgetResizable(True)
        self.excludedItemsScrollArea.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.excludedItemsScrollArea.setObjectName("excludedItemsScrollArea")
        self.excludedItemsContents = QtWidgets.QWidget()
        self.excludedItemsContents.setGeometry(QtCore.QRect(0, 0, 794, 332))
        self.excludedItemsContents.setObjectName("excludedItemsContents")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.excludedItemsContents)
        self.verticalLayout_2.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout_2.setSpacing(6)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.excludedItemsContentLayout = QtWidgets.QVBoxLayout()
        self.excludedItemsContentLayout.setSpacing(6)
        self.excludedItemsContentLayout.setObjectName("excludedItemsContentLayout")
        self.verticalLayout_2.addLayout(self.excludedItemsContentLayout)
        self.excludedItemsScrollArea.setWidget(self.excludedItemsContents)
        self.gridLayout_4.addWidget(self.excludedItemsScrollArea, 3, 0, 1, 3)
        self.gridLayout.addWidget(self.excludedPickupsBox, 4, 0, 1, 2)
        self.cpuUsageBox = QtWidgets.QGroupBox(self.centralWidget)
        self.cpuUsageBox.setObjectName("cpuUsageBox")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.cpuUsageBox)
        self.verticalLayout.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout.setSpacing(6)
        self.verticalLayout.setObjectName("verticalLayout")
        self.maxUsageRadio = QtWidgets.QRadioButton(self.cpuUsageBox)
        self.maxUsageRadio.setObjectName("maxUsageRadio")
        self.verticalLayout.addWidget(self.maxUsageRadio)
        self.highUsageRadio = QtWidgets.QRadioButton(self.cpuUsageBox)
        self.highUsageRadio.setObjectName("highUsageRadio")
        self.verticalLayout.addWidget(self.highUsageRadio)
        self.balancedUsageRadio = QtWidgets.QRadioButton(self.cpuUsageBox)
        self.balancedUsageRadio.setObjectName("balancedUsageRadio")
        self.verticalLayout.addWidget(self.balancedUsageRadio)
        self.minialUsageRadio = QtWidgets.QRadioButton(self.cpuUsageBox)
        self.minialUsageRadio.setObjectName("minialUsageRadio")
        self.verticalLayout.addWidget(self.minialUsageRadio)
        self.gridLayout.addWidget(self.cpuUsageBox, 1, 1, 2, 1)
        self.seedBox = QtWidgets.QGroupBox(self.centralWidget)
        self.seedBox.setObjectName("seedBox")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.seedBox)
        self.gridLayout_5.setContentsMargins(11, 11, 11, 11)
        self.gridLayout_5.setSpacing(6)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.applySeedButton = QtWidgets.QPushButton(self.seedBox)
        self.applySeedButton.setObjectName("applySeedButton")
        self.gridLayout_5.addWidget(self.applySeedButton, 2, 2, 1, 1)
        self.statusLabel = QtWidgets.QLabel(self.seedBox)
        self.statusLabel.setText("")
        self.statusLabel.setObjectName("statusLabel")
        self.gridLayout_5.addWidget(self.statusLabel, 3, 1, 1, 2)
        self.generateSeedButton = QtWidgets.QPushButton(self.seedBox)
        self.generateSeedButton.setObjectName("generateSeedButton")
        self.gridLayout_5.addWidget(self.generateSeedButton, 1, 1, 1, 1)
        self.stopBackgroundProcessButton = QtWidgets.QPushButton(self.seedBox)
        self.stopBackgroundProcessButton.setEnabled(False)
        self.stopBackgroundProcessButton.setObjectName("stopBackgroundProcessButton")
        self.gridLayout_5.addWidget(self.stopBackgroundProcessButton, 1, 2, 1, 1)
        self.last_seed_label = QtWidgets.QLabel(self.seedBox)
        self.last_seed_label.setText("")
        self.last_seed_label.setAlignment(QtCore.Qt.AlignCenter)
        self.last_seed_label.setObjectName("last_seed_label")
        self.gridLayout_5.addWidget(self.last_seed_label, 2, 1, 1, 1)
        self.gridLayout.addWidget(self.seedBox, 1, 0, 2, 1)
        self.label = QtWidgets.QLabel(self.centralWidget)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 2)
        SeedSearcherWindow.setCentralWidget(self.centralWidget)
        self.menuBar = QtWidgets.QMenuBar(SeedSearcherWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 852, 21))
        self.menuBar.setObjectName("menuBar")
        SeedSearcherWindow.setMenuBar(self.menuBar)

        self.retranslateUi(SeedSearcherWindow)
        QtCore.QMetaObject.connectSlotsByName(SeedSearcherWindow)

    def retranslateUi(self, SeedSearcherWindow):
        _translate = QtCore.QCoreApplication.translate
        SeedSearcherWindow.setWindowTitle(_translate("SeedSearcherWindow", "Hello, world!"))
        self.excludedPickupsBox.setTitle(_translate("SeedSearcherWindow", "Excluded Pickups"))
        self.clearExcludedPickups.setText(_translate("SeedSearcherWindow", "Deselect all"))
        self.label_3.setToolTip(_translate("SeedSearcherWindow", "Enter text to the right to filter the list below"))
        self.label_3.setText(_translate("SeedSearcherWindow", "Filter:"))
        self.cpuUsageBox.setToolTip(_translate("SeedSearcherWindow", "<html><head/><body><p>Configure how many CPU cores the generation will use.</p><p>Certain options may be disabled based on the CPU count of your system.</p></body></html>"))
        self.cpuUsageBox.setTitle(_translate("SeedSearcherWindow", "CPU Usage"))
        self.maxUsageRadio.setText(_translate("SeedSearcherWindow", "100% - Fastest, but disrupts all usage"))
        self.highUsageRadio.setText(_translate("SeedSearcherWindow", "High - Shouldn\'t disrupt basic system usage"))
        self.balancedUsageRadio.setText(_translate("SeedSearcherWindow", "Balanced - Should have low impact on other applications"))
        self.minialUsageRadio.setText(_translate("SeedSearcherWindow", "Minimal - Slowest, but has almost no disruption to usage"))
        self.seedBox.setTitle(_translate("SeedSearcherWindow", "Seed"))
        self.applySeedButton.setText(_translate("SeedSearcherWindow", "Apply to an ISO"))
        self.generateSeedButton.setText(_translate("SeedSearcherWindow", "Generate new Seed"))
        self.stopBackgroundProcessButton.setText(_translate("SeedSearcherWindow", "Stop"))
        self.label.setText(_translate("SeedSearcherWindow", "<html><head/><body><p>On this tab you can brute force search for beatable seeds.</p></body></html>"))

