
# This file was generated by 'versioneer.py' (0.15) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json
import sys

version_json = '''
{
 "dirty": false,
 "error": null,
 "full-revisionid": "71f49f8e0948e0e3cb058e995a5a54ce5e35059b",
 "version": "v0.1.1-alpha.post.dev91"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
