
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2018-07-18T13:49:22+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "316691909f96c238d93ae64e19548da9627d428b",
 "version": "0.4a19"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
