dist: trusty
sudo: required
language: python
python:
- '3.5'
- '3.6'
before-install:
- apt-get update -y
- apt-get install -y software-properties-common
- wget -qO - 'https://packages.confluent.io/deb/4.0/archive.key' | apt-key add -
- add-apt-repository "deb [arch=amd64] https://packages.confluent.io/deb/4.0 stable
  main"
- apt-get install -y librdkafka-dev librdkafka1
install:
- pip install tox-travis
script:
- tox
deploy:
  provider: pypi
  user: mazzafish
  password:
    secure: yS9TU6D7PjcR49D58x1dvktMD3qhUYtGkYsYM8o7nsjKdZlbTJdX8PStm1eQyLaOyo+c/AGOpoX2KTcxbo9UvMeZSRP+I6KwyliF1T7HQcWgbVDYnfL/fBrNkX3Kg32O2CyJkGaW8nWm4/tCCa1ujQbfEpr9bu57drmV1DKfqIh41WAzfuBLDCgwGGd7IOerDut2wrSHD4Pd5phrUZaQ7aHZXkKxmUd7MBVdBPbW0xlYj9/9O0v4YVLdNuLOy38DjF1cIeHpaaqqzmTzXR5wKboU/c/Xora7RAXwluqUAPuxQJpNSozoYNn4K5ayxdMx6OnwVDxzAzbxDW25blabH23pnBNqqDuEMr0mZ+dD+UKjkmgEw/sZ7lnRJWj2JjseEPeWPvCc/pY2TWs4cHL6wH01fZe86juN1968ifPHApj+tN1T/xwbzBwaQtVExMrD89VN6knrMz1KSWLgc/f3TdG9kvD1AqColt5jRsmoHH/5MPoqOfeu8vOXIKpGf4donBYy5aYFC4VoDCQDPVsTZ2cJ0Etritolz+qE7MVOo4fTyRIdOtzKvdvbnRrJ0Nmyf2AhlQ+tPTLGTVxFsZyq178sRFYp7/nit115T+VzRpoULwVtJT1c3MT0SvhNBgO4e0H36EyWD59B4EQ/Fv69h278IPvG8qexaafZ/NIktSA=
  distributions: sdist bdist_wheel
  true:
    tags: true
    branch: master
