# coding: utf-8

"""
    Dash Auth API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: v1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import dash_auth
from dash_auth.api.password_api import PasswordApi  # noqa: E501
from dash_auth.rest import ApiException


class TestPasswordApi(unittest.TestCase):
    """PasswordApi unit test stubs"""

    def setUp(self):
        self.api = dash_auth.api.password_api.PasswordApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_api_account_password_post(self):
        """Test case for api_account_password_post

        """
        pass

    def test_api_account_password_put(self):
        """Test case for api_account_password_put

        """
        pass


if __name__ == '__main__':
    unittest.main()
