# coding: utf-8

"""
    Dash Auth API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: v1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import dash_auth
from dash_auth.models.authentication_scheme import AuthenticationScheme  # noqa: E501
from dash_auth.rest import ApiException


class TestAuthenticationScheme(unittest.TestCase):
    """AuthenticationScheme unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testAuthenticationScheme(self):
        """Test AuthenticationScheme"""
        # FIXME: construct object with mandatory attributes with example values
        # model = dash_auth.models.authentication_scheme.AuthenticationScheme()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
