#!/usr/bin/env python
# setup.py generated by flit for tools that don't yet use PEP 517

from distutils.core import setup

packages = \
['pypexels', 'pypexels.src']

package_data = \
{'': ['*'], 'pypexels': ['examples/*']}

install_requires = \
['requests~=2.19', 'future']

setup(name='pypexels_l5',
      version='1.0.0b4',
      description='A simple wrapper around the Pexels API',
      author='Josh Klar',
      author_email='josh@lumen5.com',
      url='https://github.com/Lumen5/pypexels_l5',
      packages=packages,
      package_data=package_data,
      install_requires=install_requires,
     )
