sudo: false
language: python
services:
  # For Gnocchi
  - docker
install:
      - |
        if [ "$TOXENV" == "gnocchi" ]; then
            docker pull gnocchixyz/ci-tools:latest
        else
            pip install tox
        fi
script:
      - |
        case "$TOXENV" in
            gnocchi)
              docker run -v ~/.cache/pip:/home/tester/.cache/pip -v $(pwd):/home/tester/src gnocchixyz/ci-tools:latest tox -e ${TOXENV}
              ;;
            *)
              tox
              ;;
        esac
matrix:
    include:
        - env: TOXENV=py27
        - env: TOXENV=pep8
        - env: TOXENV=py27-pytest
        - env: TOXENV=gnocchi
        - env: TOXENV=placement
        - python: 3.4
          env: TOXENV=py34
        - python: pypy
          env: TOXENV=pypy
        - python: pypy3
          env: TOXENV=pypy3
        - python: 3.5
          env: TOXENV=py35
        - python: 3.5
          env: TOXENV=py35-pytest
        - python: 3.6
          env: TOXENV=py36-failskip
        - python: 3.6
          env: TOXENV=py36-limit
        - python: 3.6
          env: TOXENV=py36-prefix
        - python: 3.6
          env: TOXENV=py36
        - python: 3.6
          env: TOXENV=py36-pytest

notifications:
      irc: "chat.freenode.net#gabbi"
