# This file was automatically generated by SWIG (http://www.swig.org).
# Version 3.0.12
#
# Do not make changes to this file unless you know what you are doing--modify
# the SWIG interface file instead.

from sys import version_info as _swig_python_version_info
if _swig_python_version_info >= (2, 7, 0):
    def swig_import_helper():
        import importlib
        pkg = __name__.rpartition('.')[0]
        mname = '.'.join((pkg, '_measuresToolkit')).lstrip('.')
        try:
            return importlib.import_module(mname)
        except ImportError:
            return importlib.import_module('_measuresToolkit')
    _measuresToolkit = swig_import_helper()
    del swig_import_helper
elif _swig_python_version_info >= (2, 6, 0):
    def swig_import_helper():
        from os.path import dirname
        import imp
        fp = None
        try:
            fp, pathname, description = imp.find_module('_measuresToolkit', [dirname(__file__)])
        except ImportError:
            import _measuresToolkit
            return _measuresToolkit
        try:
            _mod = imp.load_module('_measuresToolkit', fp, pathname, description)
        finally:
            if fp is not None:
                fp.close()
        return _mod
    _measuresToolkit = swig_import_helper()
    del swig_import_helper
else:
    import _measuresToolkit
del _swig_python_version_info

try:
    _swig_property = property
except NameError:
    pass  # Python < 2.2 doesn't have 'property'.

try:
    import builtins as __builtin__
except ImportError:
    import __builtin__

def _swig_setattr_nondynamic(self, class_type, name, value, static=1):
    if (name == "thisown"):
        return self.this.own(value)
    if (name == "this"):
        if type(value).__name__ == 'SwigPyObject':
            self.__dict__[name] = value
            return
    method = class_type.__swig_setmethods__.get(name, None)
    if method:
        return method(self, value)
    if (not static):
        if _newclass:
            object.__setattr__(self, name, value)
        else:
            self.__dict__[name] = value
    else:
        raise AttributeError("You cannot add attributes to %s" % self)


def _swig_setattr(self, class_type, name, value):
    return _swig_setattr_nondynamic(self, class_type, name, value, 0)


def _swig_getattr(self, class_type, name):
    if (name == "thisown"):
        return self.this.own()
    method = class_type.__swig_getmethods__.get(name, None)
    if method:
        return method(self)
    raise AttributeError("'%s' object has no attribute '%s'" % (class_type.__name__, name))


def _swig_repr(self):
    try:
        strthis = "proxy of " + self.this.__repr__()
    except __builtin__.Exception:
        strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)

try:
    _object = object
    _newclass = 1
except __builtin__.Exception:
    class _object:
        pass
    _newclass = 0

class SwigPyIterator(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, SwigPyIterator, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, SwigPyIterator, name)

    def __init__(self, *args, **kwargs):
        raise AttributeError("No constructor defined - class is abstract")
    __repr__ = _swig_repr
    __swig_destroy__ = _measuresToolkit.delete_SwigPyIterator
    __del__ = lambda self: None

    def value(self):
        return _measuresToolkit.SwigPyIterator_value(self)

    def incr(self, n=1):
        return _measuresToolkit.SwigPyIterator_incr(self, n)

    def decr(self, n=1):
        return _measuresToolkit.SwigPyIterator_decr(self, n)

    def distance(self, x):
        return _measuresToolkit.SwigPyIterator_distance(self, x)

    def equal(self, x):
        return _measuresToolkit.SwigPyIterator_equal(self, x)

    def copy(self):
        return _measuresToolkit.SwigPyIterator_copy(self)

    def next(self):
        return _measuresToolkit.SwigPyIterator_next(self)

    def __next__(self):
        return _measuresToolkit.SwigPyIterator___next__(self)

    def previous(self):
        return _measuresToolkit.SwigPyIterator_previous(self)

    def advance(self, n):
        return _measuresToolkit.SwigPyIterator_advance(self, n)

    def __eq__(self, x):
        return _measuresToolkit.SwigPyIterator___eq__(self, x)

    def __ne__(self, x):
        return _measuresToolkit.SwigPyIterator___ne__(self, x)

    def __iadd__(self, n):
        return _measuresToolkit.SwigPyIterator___iadd__(self, n)

    def __isub__(self, n):
        return _measuresToolkit.SwigPyIterator___isub__(self, n)

    def __add__(self, n):
        return _measuresToolkit.SwigPyIterator___add__(self, n)

    def __sub__(self, *args):
        return _measuresToolkit.SwigPyIterator___sub__(self, *args)
    def __iter__(self):
        return self
SwigPyIterator_swigregister = _measuresToolkit.SwigPyIterator_swigregister
SwigPyIterator_swigregister(SwigPyIterator)

class VectorFloat(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, VectorFloat, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, VectorFloat, name)
    __repr__ = _swig_repr

    def iterator(self):
        return _measuresToolkit.VectorFloat_iterator(self)
    def __iter__(self):
        return self.iterator()

    def __nonzero__(self):
        return _measuresToolkit.VectorFloat___nonzero__(self)

    def __bool__(self):
        return _measuresToolkit.VectorFloat___bool__(self)

    def __len__(self):
        return _measuresToolkit.VectorFloat___len__(self)

    def __getslice__(self, i, j):
        return _measuresToolkit.VectorFloat___getslice__(self, i, j)

    def __setslice__(self, *args):
        return _measuresToolkit.VectorFloat___setslice__(self, *args)

    def __delslice__(self, i, j):
        return _measuresToolkit.VectorFloat___delslice__(self, i, j)

    def __delitem__(self, *args):
        return _measuresToolkit.VectorFloat___delitem__(self, *args)

    def __getitem__(self, *args):
        return _measuresToolkit.VectorFloat___getitem__(self, *args)

    def __setitem__(self, *args):
        return _measuresToolkit.VectorFloat___setitem__(self, *args)

    def pop(self):
        return _measuresToolkit.VectorFloat_pop(self)

    def append(self, x):
        return _measuresToolkit.VectorFloat_append(self, x)

    def empty(self):
        return _measuresToolkit.VectorFloat_empty(self)

    def size(self):
        return _measuresToolkit.VectorFloat_size(self)

    def swap(self, v):
        return _measuresToolkit.VectorFloat_swap(self, v)

    def begin(self):
        return _measuresToolkit.VectorFloat_begin(self)

    def end(self):
        return _measuresToolkit.VectorFloat_end(self)

    def rbegin(self):
        return _measuresToolkit.VectorFloat_rbegin(self)

    def rend(self):
        return _measuresToolkit.VectorFloat_rend(self)

    def clear(self):
        return _measuresToolkit.VectorFloat_clear(self)

    def get_allocator(self):
        return _measuresToolkit.VectorFloat_get_allocator(self)

    def pop_back(self):
        return _measuresToolkit.VectorFloat_pop_back(self)

    def erase(self, *args):
        return _measuresToolkit.VectorFloat_erase(self, *args)

    def __init__(self, *args):
        this = _measuresToolkit.new_VectorFloat(*args)
        try:
            self.this.append(this)
        except __builtin__.Exception:
            self.this = this

    def push_back(self, x):
        return _measuresToolkit.VectorFloat_push_back(self, x)

    def front(self):
        return _measuresToolkit.VectorFloat_front(self)

    def back(self):
        return _measuresToolkit.VectorFloat_back(self)

    def assign(self, n, x):
        return _measuresToolkit.VectorFloat_assign(self, n, x)

    def resize(self, *args):
        return _measuresToolkit.VectorFloat_resize(self, *args)

    def insert(self, *args):
        return _measuresToolkit.VectorFloat_insert(self, *args)

    def reserve(self, n):
        return _measuresToolkit.VectorFloat_reserve(self, n)

    def capacity(self):
        return _measuresToolkit.VectorFloat_capacity(self)
    __swig_destroy__ = _measuresToolkit.delete_VectorFloat
    __del__ = lambda self: None
VectorFloat_swigregister = _measuresToolkit.VectorFloat_swigregister
VectorFloat_swigregister(VectorFloat)

class VectorVectorFloat(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, VectorVectorFloat, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, VectorVectorFloat, name)
    __repr__ = _swig_repr

    def iterator(self):
        return _measuresToolkit.VectorVectorFloat_iterator(self)
    def __iter__(self):
        return self.iterator()

    def __nonzero__(self):
        return _measuresToolkit.VectorVectorFloat___nonzero__(self)

    def __bool__(self):
        return _measuresToolkit.VectorVectorFloat___bool__(self)

    def __len__(self):
        return _measuresToolkit.VectorVectorFloat___len__(self)

    def __getslice__(self, i, j):
        return _measuresToolkit.VectorVectorFloat___getslice__(self, i, j)

    def __setslice__(self, *args):
        return _measuresToolkit.VectorVectorFloat___setslice__(self, *args)

    def __delslice__(self, i, j):
        return _measuresToolkit.VectorVectorFloat___delslice__(self, i, j)

    def __delitem__(self, *args):
        return _measuresToolkit.VectorVectorFloat___delitem__(self, *args)

    def __getitem__(self, *args):
        return _measuresToolkit.VectorVectorFloat___getitem__(self, *args)

    def __setitem__(self, *args):
        return _measuresToolkit.VectorVectorFloat___setitem__(self, *args)

    def pop(self):
        return _measuresToolkit.VectorVectorFloat_pop(self)

    def append(self, x):
        return _measuresToolkit.VectorVectorFloat_append(self, x)

    def empty(self):
        return _measuresToolkit.VectorVectorFloat_empty(self)

    def size(self):
        return _measuresToolkit.VectorVectorFloat_size(self)

    def swap(self, v):
        return _measuresToolkit.VectorVectorFloat_swap(self, v)

    def begin(self):
        return _measuresToolkit.VectorVectorFloat_begin(self)

    def end(self):
        return _measuresToolkit.VectorVectorFloat_end(self)

    def rbegin(self):
        return _measuresToolkit.VectorVectorFloat_rbegin(self)

    def rend(self):
        return _measuresToolkit.VectorVectorFloat_rend(self)

    def clear(self):
        return _measuresToolkit.VectorVectorFloat_clear(self)

    def get_allocator(self):
        return _measuresToolkit.VectorVectorFloat_get_allocator(self)

    def pop_back(self):
        return _measuresToolkit.VectorVectorFloat_pop_back(self)

    def erase(self, *args):
        return _measuresToolkit.VectorVectorFloat_erase(self, *args)

    def __init__(self, *args):
        this = _measuresToolkit.new_VectorVectorFloat(*args)
        try:
            self.this.append(this)
        except __builtin__.Exception:
            self.this = this

    def push_back(self, x):
        return _measuresToolkit.VectorVectorFloat_push_back(self, x)

    def front(self):
        return _measuresToolkit.VectorVectorFloat_front(self)

    def back(self):
        return _measuresToolkit.VectorVectorFloat_back(self)

    def assign(self, n, x):
        return _measuresToolkit.VectorVectorFloat_assign(self, n, x)

    def resize(self, *args):
        return _measuresToolkit.VectorVectorFloat_resize(self, *args)

    def insert(self, *args):
        return _measuresToolkit.VectorVectorFloat_insert(self, *args)

    def reserve(self, n):
        return _measuresToolkit.VectorVectorFloat_reserve(self, n)

    def capacity(self):
        return _measuresToolkit.VectorVectorFloat_capacity(self)
    __swig_destroy__ = _measuresToolkit.delete_VectorVectorFloat
    __del__ = lambda self: None
VectorVectorFloat_swigregister = _measuresToolkit.VectorVectorFloat_swigregister
VectorVectorFloat_swigregister(VectorVectorFloat)

class VectorDouble(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, VectorDouble, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, VectorDouble, name)
    __repr__ = _swig_repr

    def iterator(self):
        return _measuresToolkit.VectorDouble_iterator(self)
    def __iter__(self):
        return self.iterator()

    def __nonzero__(self):
        return _measuresToolkit.VectorDouble___nonzero__(self)

    def __bool__(self):
        return _measuresToolkit.VectorDouble___bool__(self)

    def __len__(self):
        return _measuresToolkit.VectorDouble___len__(self)

    def __getslice__(self, i, j):
        return _measuresToolkit.VectorDouble___getslice__(self, i, j)

    def __setslice__(self, *args):
        return _measuresToolkit.VectorDouble___setslice__(self, *args)

    def __delslice__(self, i, j):
        return _measuresToolkit.VectorDouble___delslice__(self, i, j)

    def __delitem__(self, *args):
        return _measuresToolkit.VectorDouble___delitem__(self, *args)

    def __getitem__(self, *args):
        return _measuresToolkit.VectorDouble___getitem__(self, *args)

    def __setitem__(self, *args):
        return _measuresToolkit.VectorDouble___setitem__(self, *args)

    def pop(self):
        return _measuresToolkit.VectorDouble_pop(self)

    def append(self, x):
        return _measuresToolkit.VectorDouble_append(self, x)

    def empty(self):
        return _measuresToolkit.VectorDouble_empty(self)

    def size(self):
        return _measuresToolkit.VectorDouble_size(self)

    def swap(self, v):
        return _measuresToolkit.VectorDouble_swap(self, v)

    def begin(self):
        return _measuresToolkit.VectorDouble_begin(self)

    def end(self):
        return _measuresToolkit.VectorDouble_end(self)

    def rbegin(self):
        return _measuresToolkit.VectorDouble_rbegin(self)

    def rend(self):
        return _measuresToolkit.VectorDouble_rend(self)

    def clear(self):
        return _measuresToolkit.VectorDouble_clear(self)

    def get_allocator(self):
        return _measuresToolkit.VectorDouble_get_allocator(self)

    def pop_back(self):
        return _measuresToolkit.VectorDouble_pop_back(self)

    def erase(self, *args):
        return _measuresToolkit.VectorDouble_erase(self, *args)

    def __init__(self, *args):
        this = _measuresToolkit.new_VectorDouble(*args)
        try:
            self.this.append(this)
        except __builtin__.Exception:
            self.this = this

    def push_back(self, x):
        return _measuresToolkit.VectorDouble_push_back(self, x)

    def front(self):
        return _measuresToolkit.VectorDouble_front(self)

    def back(self):
        return _measuresToolkit.VectorDouble_back(self)

    def assign(self, n, x):
        return _measuresToolkit.VectorDouble_assign(self, n, x)

    def resize(self, *args):
        return _measuresToolkit.VectorDouble_resize(self, *args)

    def insert(self, *args):
        return _measuresToolkit.VectorDouble_insert(self, *args)

    def reserve(self, n):
        return _measuresToolkit.VectorDouble_reserve(self, n)

    def capacity(self):
        return _measuresToolkit.VectorDouble_capacity(self)
    __swig_destroy__ = _measuresToolkit.delete_VectorDouble
    __del__ = lambda self: None
VectorDouble_swigregister = _measuresToolkit.VectorDouble_swigregister
VectorDouble_swigregister(VectorDouble)

class VectorVectorDouble(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, VectorVectorDouble, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, VectorVectorDouble, name)
    __repr__ = _swig_repr

    def iterator(self):
        return _measuresToolkit.VectorVectorDouble_iterator(self)
    def __iter__(self):
        return self.iterator()

    def __nonzero__(self):
        return _measuresToolkit.VectorVectorDouble___nonzero__(self)

    def __bool__(self):
        return _measuresToolkit.VectorVectorDouble___bool__(self)

    def __len__(self):
        return _measuresToolkit.VectorVectorDouble___len__(self)

    def __getslice__(self, i, j):
        return _measuresToolkit.VectorVectorDouble___getslice__(self, i, j)

    def __setslice__(self, *args):
        return _measuresToolkit.VectorVectorDouble___setslice__(self, *args)

    def __delslice__(self, i, j):
        return _measuresToolkit.VectorVectorDouble___delslice__(self, i, j)

    def __delitem__(self, *args):
        return _measuresToolkit.VectorVectorDouble___delitem__(self, *args)

    def __getitem__(self, *args):
        return _measuresToolkit.VectorVectorDouble___getitem__(self, *args)

    def __setitem__(self, *args):
        return _measuresToolkit.VectorVectorDouble___setitem__(self, *args)

    def pop(self):
        return _measuresToolkit.VectorVectorDouble_pop(self)

    def append(self, x):
        return _measuresToolkit.VectorVectorDouble_append(self, x)

    def empty(self):
        return _measuresToolkit.VectorVectorDouble_empty(self)

    def size(self):
        return _measuresToolkit.VectorVectorDouble_size(self)

    def swap(self, v):
        return _measuresToolkit.VectorVectorDouble_swap(self, v)

    def begin(self):
        return _measuresToolkit.VectorVectorDouble_begin(self)

    def end(self):
        return _measuresToolkit.VectorVectorDouble_end(self)

    def rbegin(self):
        return _measuresToolkit.VectorVectorDouble_rbegin(self)

    def rend(self):
        return _measuresToolkit.VectorVectorDouble_rend(self)

    def clear(self):
        return _measuresToolkit.VectorVectorDouble_clear(self)

    def get_allocator(self):
        return _measuresToolkit.VectorVectorDouble_get_allocator(self)

    def pop_back(self):
        return _measuresToolkit.VectorVectorDouble_pop_back(self)

    def erase(self, *args):
        return _measuresToolkit.VectorVectorDouble_erase(self, *args)

    def __init__(self, *args):
        this = _measuresToolkit.new_VectorVectorDouble(*args)
        try:
            self.this.append(this)
        except __builtin__.Exception:
            self.this = this

    def push_back(self, x):
        return _measuresToolkit.VectorVectorDouble_push_back(self, x)

    def front(self):
        return _measuresToolkit.VectorVectorDouble_front(self)

    def back(self):
        return _measuresToolkit.VectorVectorDouble_back(self)

    def assign(self, n, x):
        return _measuresToolkit.VectorVectorDouble_assign(self, n, x)

    def resize(self, *args):
        return _measuresToolkit.VectorVectorDouble_resize(self, *args)

    def insert(self, *args):
        return _measuresToolkit.VectorVectorDouble_insert(self, *args)

    def reserve(self, n):
        return _measuresToolkit.VectorVectorDouble_reserve(self, n)

    def capacity(self):
        return _measuresToolkit.VectorVectorDouble_capacity(self)
    __swig_destroy__ = _measuresToolkit.delete_VectorVectorDouble
    __del__ = lambda self: None
VectorVectorDouble_swigregister = _measuresToolkit.VectorVectorDouble_swigregister
VectorVectorDouble_swigregister(VectorVectorDouble)

class VectorUnsigned(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, VectorUnsigned, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, VectorUnsigned, name)
    __repr__ = _swig_repr

    def iterator(self):
        return _measuresToolkit.VectorUnsigned_iterator(self)
    def __iter__(self):
        return self.iterator()

    def __nonzero__(self):
        return _measuresToolkit.VectorUnsigned___nonzero__(self)

    def __bool__(self):
        return _measuresToolkit.VectorUnsigned___bool__(self)

    def __len__(self):
        return _measuresToolkit.VectorUnsigned___len__(self)

    def __getslice__(self, i, j):
        return _measuresToolkit.VectorUnsigned___getslice__(self, i, j)

    def __setslice__(self, *args):
        return _measuresToolkit.VectorUnsigned___setslice__(self, *args)

    def __delslice__(self, i, j):
        return _measuresToolkit.VectorUnsigned___delslice__(self, i, j)

    def __delitem__(self, *args):
        return _measuresToolkit.VectorUnsigned___delitem__(self, *args)

    def __getitem__(self, *args):
        return _measuresToolkit.VectorUnsigned___getitem__(self, *args)

    def __setitem__(self, *args):
        return _measuresToolkit.VectorUnsigned___setitem__(self, *args)

    def pop(self):
        return _measuresToolkit.VectorUnsigned_pop(self)

    def append(self, x):
        return _measuresToolkit.VectorUnsigned_append(self, x)

    def empty(self):
        return _measuresToolkit.VectorUnsigned_empty(self)

    def size(self):
        return _measuresToolkit.VectorUnsigned_size(self)

    def swap(self, v):
        return _measuresToolkit.VectorUnsigned_swap(self, v)

    def begin(self):
        return _measuresToolkit.VectorUnsigned_begin(self)

    def end(self):
        return _measuresToolkit.VectorUnsigned_end(self)

    def rbegin(self):
        return _measuresToolkit.VectorUnsigned_rbegin(self)

    def rend(self):
        return _measuresToolkit.VectorUnsigned_rend(self)

    def clear(self):
        return _measuresToolkit.VectorUnsigned_clear(self)

    def get_allocator(self):
        return _measuresToolkit.VectorUnsigned_get_allocator(self)

    def pop_back(self):
        return _measuresToolkit.VectorUnsigned_pop_back(self)

    def erase(self, *args):
        return _measuresToolkit.VectorUnsigned_erase(self, *args)

    def __init__(self, *args):
        this = _measuresToolkit.new_VectorUnsigned(*args)
        try:
            self.this.append(this)
        except __builtin__.Exception:
            self.this = this

    def push_back(self, x):
        return _measuresToolkit.VectorUnsigned_push_back(self, x)

    def front(self):
        return _measuresToolkit.VectorUnsigned_front(self)

    def back(self):
        return _measuresToolkit.VectorUnsigned_back(self)

    def assign(self, n, x):
        return _measuresToolkit.VectorUnsigned_assign(self, n, x)

    def resize(self, *args):
        return _measuresToolkit.VectorUnsigned_resize(self, *args)

    def insert(self, *args):
        return _measuresToolkit.VectorUnsigned_insert(self, *args)

    def reserve(self, n):
        return _measuresToolkit.VectorUnsigned_reserve(self, n)

    def capacity(self):
        return _measuresToolkit.VectorUnsigned_capacity(self)
    __swig_destroy__ = _measuresToolkit.delete_VectorUnsigned
    __del__ = lambda self: None
VectorUnsigned_swigregister = _measuresToolkit.VectorUnsigned_swigregister
VectorUnsigned_swigregister(VectorUnsigned)

class VectorVectorUnsigned(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, VectorVectorUnsigned, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, VectorVectorUnsigned, name)
    __repr__ = _swig_repr

    def iterator(self):
        return _measuresToolkit.VectorVectorUnsigned_iterator(self)
    def __iter__(self):
        return self.iterator()

    def __nonzero__(self):
        return _measuresToolkit.VectorVectorUnsigned___nonzero__(self)

    def __bool__(self):
        return _measuresToolkit.VectorVectorUnsigned___bool__(self)

    def __len__(self):
        return _measuresToolkit.VectorVectorUnsigned___len__(self)

    def __getslice__(self, i, j):
        return _measuresToolkit.VectorVectorUnsigned___getslice__(self, i, j)

    def __setslice__(self, *args):
        return _measuresToolkit.VectorVectorUnsigned___setslice__(self, *args)

    def __delslice__(self, i, j):
        return _measuresToolkit.VectorVectorUnsigned___delslice__(self, i, j)

    def __delitem__(self, *args):
        return _measuresToolkit.VectorVectorUnsigned___delitem__(self, *args)

    def __getitem__(self, *args):
        return _measuresToolkit.VectorVectorUnsigned___getitem__(self, *args)

    def __setitem__(self, *args):
        return _measuresToolkit.VectorVectorUnsigned___setitem__(self, *args)

    def pop(self):
        return _measuresToolkit.VectorVectorUnsigned_pop(self)

    def append(self, x):
        return _measuresToolkit.VectorVectorUnsigned_append(self, x)

    def empty(self):
        return _measuresToolkit.VectorVectorUnsigned_empty(self)

    def size(self):
        return _measuresToolkit.VectorVectorUnsigned_size(self)

    def swap(self, v):
        return _measuresToolkit.VectorVectorUnsigned_swap(self, v)

    def begin(self):
        return _measuresToolkit.VectorVectorUnsigned_begin(self)

    def end(self):
        return _measuresToolkit.VectorVectorUnsigned_end(self)

    def rbegin(self):
        return _measuresToolkit.VectorVectorUnsigned_rbegin(self)

    def rend(self):
        return _measuresToolkit.VectorVectorUnsigned_rend(self)

    def clear(self):
        return _measuresToolkit.VectorVectorUnsigned_clear(self)

    def get_allocator(self):
        return _measuresToolkit.VectorVectorUnsigned_get_allocator(self)

    def pop_back(self):
        return _measuresToolkit.VectorVectorUnsigned_pop_back(self)

    def erase(self, *args):
        return _measuresToolkit.VectorVectorUnsigned_erase(self, *args)

    def __init__(self, *args):
        this = _measuresToolkit.new_VectorVectorUnsigned(*args)
        try:
            self.this.append(this)
        except __builtin__.Exception:
            self.this = this

    def push_back(self, x):
        return _measuresToolkit.VectorVectorUnsigned_push_back(self, x)

    def front(self):
        return _measuresToolkit.VectorVectorUnsigned_front(self)

    def back(self):
        return _measuresToolkit.VectorVectorUnsigned_back(self)

    def assign(self, n, x):
        return _measuresToolkit.VectorVectorUnsigned_assign(self, n, x)

    def resize(self, *args):
        return _measuresToolkit.VectorVectorUnsigned_resize(self, *args)

    def insert(self, *args):
        return _measuresToolkit.VectorVectorUnsigned_insert(self, *args)

    def reserve(self, n):
        return _measuresToolkit.VectorVectorUnsigned_reserve(self, n)

    def capacity(self):
        return _measuresToolkit.VectorVectorUnsigned_capacity(self)
    __swig_destroy__ = _measuresToolkit.delete_VectorVectorUnsigned
    __del__ = lambda self: None
VectorVectorUnsigned_swigregister = _measuresToolkit.VectorVectorUnsigned_swigregister
VectorVectorUnsigned_swigregister(VectorVectorUnsigned)


def computeCorrelationFunction(vol, output, stepCentre, nthreads):
    return _measuresToolkit.computeCorrelationFunction(vol, output, stepCentre, nthreads)
computeCorrelationFunction = _measuresToolkit.computeCorrelationFunction

def porosityFieldBinary(porosityFieldBinaryVolSizeZ, porosityFieldBinaryN, porosityFieldBinaryNtwo, porosityFieldBinaryNthree):
    return _measuresToolkit.porosityFieldBinary(porosityFieldBinaryVolSizeZ, porosityFieldBinaryN, porosityFieldBinaryNtwo, porosityFieldBinaryNthree)
porosityFieldBinary = _measuresToolkit.porosityFieldBinary

def computeCurvatures(faces, verts):
    return _measuresToolkit.computeCurvatures(faces, verts)
computeCurvatures = _measuresToolkit.computeCurvatures
# This file is compatible with both classic and new-style classes.


