
# This file was generated by 'versioneer.py' (0.16) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json
import sys

version_json = '''
{
 "dirty": false,
 "error": null,
 "full-revisionid": "20762807097a8afa43b66f72c50ca2377e2668b5",
 "version": "3.0.0rc4"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
