
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2018-06-14T14:26:00-0700",
 "dirty": false,
 "error": null,
 "full-revisionid": "eaa09d83a746ecbf1a3c8f1a7ac895e4360910df",
 "version": "1.0.3.3"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
