SENTENCES = (
    "Took longer than I expected.",
    "Awesome product! Will buy this again.",
    "My son loves it.",
    "My daughter loves it.",
    "Exactly what I was looking for.",
    "Shipping was quite fast. I'm really looking forward to trying this out :D",
    "It was a little bigger than I expected.",
    "Fitted perfectly.",
    "So fast.",
    "Wow!",
    "Sick.",
    "The screen size is just what I need.",
    "I like the colours.",
    "Not as large as I expected.",
    "The top is a lot brighter than in the pictures",
    "I didn't even know movies could look this good!",
    "Works a treat.",
    "No service quality issues.",
    "Great deal.",
    "Great service.",
    "Great features.",
    "Great service, great product and great price",
    "This is the best deal out there.",
    "So far everything has been great.",
    "As described.",
    "The product's great value for money.",
    "Had it installed yesterday.",
    "Always happy with this brand.",
    "Very happy with the switch so far.",
    "I love my product.",
    "Works well and well packaged.",
    "Arrived exactly as described.",
    "So cheap and exactly the same as more expensive brands.",
    "Same product at a fraction of the price :)",
    "As good as the original.",
    "I like it.",
    "Light.",
    "I have always liked physically owning one.",
    "Don't regret this purchase one single bit.",
    "I've read some users say they have trouble.",
    "Quite simple.",
    "I found it to be much clearer than my older one.",
    "Served me well for many years.",
    "Light as a feather.",
    "When I got them I was really pleased that there is a little light.",
    "Once my phone connected, it was pretty simple.",
    "Great product for the price.",
    "Battery life is good.",
    "Well made.",
    "Overpowering in some cases.",
    "These have been very comfortable in the past few days I've used them.",
    "My rating says it all!",
    "Couldn't believe it.",
    "So comfortable in my ears.",
    "Exellent value!",
    "I don't have an iPhone but it still works a treat.",
    "As a blind person, I find this product very handy.",
    "I regret not buying it sooner.",
    "Bit annoying to set up but otherwise great.",
    "This product is awesome but if you're considering buying this you already know that.",
    "The deal is legit.",
    "Both my kids love it.",
    "Good item.",
    "Am thinking about buying another.",
    "Already own quite a few of these.",
    "I already own quite a few of this model.",
    "It's hard to find a better one that this.",
    "I loved this so much I bought another one within a week as a present.",
    "Arrived really quickly.",
    "I'm new to these but I loved this one.",
    "This is my first proper one and I'm loving it.",
    "Turns on and off automatically.",
    "The 4GB's of memory provided the specs I needed.",
    "Prompt delivery, device worked prefectly...",
    "It's actually quite lightweight.",
    "No batteries included.",
    "Did the job.",
    "Great buy.",
    "Good range, about 10m.",
    "Unfortunately there's no detailed indicator.",
    "A great little item for use with my tv or computer.",
    "Really sleek and easy to use.",
    "Otherwise it works fine.",
    "Two minor things.",
    "One minor thing.",
    "If you really want a better experience you'll have to buy the larger model.",
    "Go and get it you won't regret it.",
    "So far very happy with the switch.",
    "Easy to operate.",
    "Exactly what I needed.",
    "Seems to work.",
    "Thanks!",
    "It's just awesome.",
    "Overall quality is great.",
    "I got the wrong size.",
    "Great size.",
    "Good picture in HD.",
    "Excellent for streaming.",
    "Just what I need.",
    "So far so good!",
)
