heat_template_version: ocata

description: >
  OpenStack Ceilometer Collector service configured with Puppet

parameters:
  ServiceNetMap:
    default: {}
    description: Mapping of service_name -> network name. Typically set
                 via parameter_defaults in the resource registry.  This
                 mapping overrides those in ServiceNetMapDefaults.
    type: json
  DefaultPasswords:
    default: {}
    type: json
  EndpointMap:
    default: {}
    description: Mapping of service endpoint -> protocol. Typically set
                 via parameter_defaults in the resource registry.
    type: json
  MonitoringSubscriptionCeilometerCollector:
    default: 'overcloud-ceilometer-collector'
    type: string
  CeilometerCollectorLoggingSource:
    type: json
    default:
      tag: openstack.ceilometer.collector
      path: /var/log/ceilometer/collector.log

resources:
  CeilometerServiceBase:
    type: ./ceilometer-base.yaml
    properties:
      ServiceNetMap: {get_param: ServiceNetMap}
      DefaultPasswords: {get_param: DefaultPasswords}
      EndpointMap: {get_param: EndpointMap}

  MongoDbBase:
    type: ./database/mongodb-base.yaml
    properties:
      ServiceNetMap: {get_param: ServiceNetMap}
      DefaultPasswords: {get_param: DefaultPasswords}
      EndpointMap: {get_param: EndpointMap}

outputs:
  role_data:
    description: Role data for the Ceilometer Collector role.
    value:
      service_name: ceilometer_collector
      monitoring_subscription: {get_param: MonitoringSubscriptionCeilometerCollector}
      logging_source: {get_param: CeilometerCollectorLoggingSource}
      logging_groups:
        - ceilometer
      config_settings:
        map_merge:
          - get_attr: [MongoDbBase, role_data, config_settings]
          - get_attr: [CeilometerServiceBase, role_data, config_settings]
      service_config_settings:
        get_attr: [CeilometerServiceBase, role_data, service_config_settings]
      step_config: |
        include ::tripleo::profile::base::ceilometer::collector
      upgrade_tasks:
        - name: Check if ceilometer_collector is deployed
          command: systemctl is-enabled openstack-ceilometer-collector
          tags: common
          ignore_errors: True
          register: ceilometer_collector_enabled
        - name: "PreUpgrade step0,validation: Check service openstack-ceilometer-collector is running"
          shell: /usr/bin/systemctl show 'openstack-ceilometer-collector' --property ActiveState | grep '\bactive\b'
          when: ceilometer_collector_enabled.rc == 0
          tags: step0,validation
        - name: Stop ceilometer_collector service
          tags: step1
          when: ceilometer_collector_enabled.rc == 0
          service: name=openstack-ceilometer-collector state=stopped
