heat_template_version: ocata

description: >
  Ceph MDS service.

parameters:
  ServiceNetMap:
    default: {}
    description: Mapping of service_name -> network name. Typically set
                 via parameter_defaults in the resource registry.  This
                 mapping overrides those in ServiceNetMapDefaults.
    type: json
  DefaultPasswords:
    default: {}
    type: json
  EndpointMap:
    default: {}
    description: Mapping of service endpoint -> protocol. Typically set
                 via parameter_defaults in the resource registry.
    type: json
  CephMdsKey:
    description: The cephx key for the MDS service. Can be created
                 with ceph-authtool --gen-print-key.
    type: string
    hidden: true

resources:
  CephBase:
    type: ./ceph-base.yaml
    properties:
      ServiceNetMap: {get_param: ServiceNetMap}
      DefaultPasswords: {get_param: DefaultPasswords}
      EndpointMap: {get_param: EndpointMap}

outputs:
  role_data:
    description: Role data for the Ceph MDS service.
    value:
      service_name: ceph_mds
      config_settings:
        map_merge:
          - get_attr: [CephBase, role_data, config_settings]
          - ceph::profile::params::mds_key: {get_param: CephMdsKey}
            tripleo.ceph_mds.firewall_rules:
              '112 ceph_mds':
                dport:
                  - '6800-7300'
      step_config: |
        include ::tripleo::profile::base::ceph::mds
