heat_template_version: ocata

description: >
  Gnocchi service configured with Puppet

parameters:
  ServiceNetMap:
    default: {}
    description: Mapping of service_name -> network name. Typically set
                 via parameter_defaults in the resource registry.  This
                 mapping overrides those in ServiceNetMapDefaults.
    type: json
  DefaultPasswords:
    default: {}
    type: json
  EndpointMap:
    default: {}
    description: Mapping of service endpoint -> protocol. Typically set
                 via parameter_defaults in the resource registry.
    type: json
  MonitoringSubscriptionGnocchiMetricd:
    default: 'overcloud-gnocchi-metricd'
    type: string
  GnocchiMetricdWorkers:
    default: '%{::os_workers}'
    description: Number of workers for Gnocchi MetricD
    type: string

resources:
  GnocchiServiceBase:
    type: ./gnocchi-base.yaml
    properties:
      ServiceNetMap: {get_param: ServiceNetMap}
      DefaultPasswords: {get_param: DefaultPasswords}
      EndpointMap: {get_param: EndpointMap}

outputs:
  role_data:
    description: Role data for the Gnocchi role.
    value:
      service_name: gnocchi_metricd
      monitoring_subscription: {get_param: MonitoringSubscriptionGnocchiMetricd}
      config_settings:
        map_merge:
          - get_attr: [GnocchiServiceBase, role_data, config_settings]
          - gnocchi::metricd::workers: {get_param: GnocchiMetricdWorkers}
      step_config: |
        include ::tripleo::profile::base::gnocchi::metricd
      upgrade_tasks:
        - name: Check if gnocchi_metricd is deployed
          command: systemctl is-enabled openstack-gnocchi-metricd
          tags: common
          ignore_errors: True
          register: gnocchi_metricd_enabled
        - name: "PreUpgrade step0,validation: Check service openstack-gnocchi-metricd is running"
          shell: /usr/bin/systemctl show 'openstack-gnocchi-metricd' --property ActiveState | grep '\bactive\b'
          when: gnocchi_metricd_enabled.rc == 0
          tags: step0,validation
        - name: Stop gnocchi_metricd service
          tags: step1
          when: gnocchi_metricd_enabled.rc == 0
          service: name=openstack-gnocchi-metricd state=stopped
