heat_template_version: ocata

description: >
  OpenStack Nova API service configured with Puppet

parameters:
  ServiceNetMap:
    default: {}
    description: Mapping of service_name -> network name. Typically set
                 via parameter_defaults in the resource registry.  This
                 mapping overrides those in ServiceNetMapDefaults.
    type: json
  DefaultPasswords:
    default: {}
    type: json
  EndpointMap:
    default: {}
    description: Mapping of service endpoint -> protocol. Typically set
                 via parameter_defaults in the resource registry.
    type: json
  NovaWorkers:
    default: 0
    description: Number of workers for Nova API service.
    type: number

conditions:
  nova_workers_zero: {equals : [{get_param: NovaWorkers}, 0]}

outputs:
  role_data:
    description: Role data for the Nova Metadata service.
    value:
      service_name: nova_metadata
      config_settings:
        map_merge:
        - nova::api::metadata_listen: {get_param: [ServiceNetMap, NovaMetadataNetwork]}
        -
          if:
          - nova_workers_zero
          - {}
          - nova::api::metadata_workers: {get_param: NovaWorkers}
      step_config: ""
