heat_template_version: ocata

description: >
  OVN databases configured with puppet

parameters:
  ServiceNetMap:
    default: {}
    description: Mapping of service_name -> network name. Typically set
                 via parameter_defaults in the resource registry.  This
                 mapping overrides those in ServiceNetMapDefaults.
    type: json
  DefaultPasswords:
    default: {}
    type: json
  EndpointMap:
    default: {}
    description: Mapping of service endpoint -> protocol. Typically set
                 via parameter_defaults in the resource registry.
    type: json
  OVNNorthboundServerPort:
    description: Port of the OVN Northbound DB server
    type: number
    default: 6641
  OVNSouthboundServerPort:
    description: Port of the OVN Southbound DB server
    type: number
    default: 6642

outputs:
  role_data:
    description: Role data for the OVN northd service
    value:
      service_name: ovn_dbs
      config_settings:
          ovn::northbound::port: {get_param: OVNNorthboundServerPort}
          ovn::southbound::port: {get_param: OVNSouthboundServerPort}
          ovn::northd::dbs_listen_ip: {get_param: [ServiceNetMap, OvnDbsNetwork]}
      step_config: |
        include ::tripleo::profile::base::neutron::ovn_northd
