# coding: utf-8

"""
    Dash API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: v1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import dash_api
from dash_api.api.activities_api import ActivitiesApi  # noqa: E501
from dash_api.rest import ApiException


class TestActivitiesApi(unittest.TestCase):
    """ActivitiesApi unit test stubs"""

    def setUp(self):
        self.api = dash_api.api.activities_api.ActivitiesApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_api_activities_by_id_get(self):
        """Test case for api_activities_by_id_get

        """
        pass

    def test_api_activities_get(self):
        """Test case for api_activities_get

        """
        pass

    def test_api_activities_post(self):
        """Test case for api_activities_post

        """
        pass

    def test_api_activities_structure_by_id_get(self):
        """Test case for api_activities_structure_by_id_get

        """
        pass

    def test_api_activities_top_most_get(self):
        """Test case for api_activities_top_most_get

        """
        pass

    def test_api_activities_types_by_id_get(self):
        """Test case for api_activities_types_by_id_get

        """
        pass

    def test_api_activities_types_get(self):
        """Test case for api_activities_types_get

        """
        pass

    def test_api_activities_types_post(self):
        """Test case for api_activities_types_post

        """
        pass


if __name__ == '__main__':
    unittest.main()
