- project:
    check:
      jobs:
        - networking-generic-switch-tempest-dsvm-dlm
        - ironic-tempest-dsvm-ipa-wholedisk-agent_ipmitool-tinyipa-multinode:
            irrelevant-files:
              - ^(test-|)requirements.txt$
              - ^setup.cfg$
        # Temporary mark multinode job as NV.
        # see https://bugs.launchpad.net/ironic/+bug/1744139
        - ironic-grenade-dsvm-multinode-multitenant:
            voting: false
        - openstack-tox-lower-constraints
    gate:
      jobs:
        - networking-generic-switch-tempest-dsvm-dlm
        - ironic-tempest-dsvm-ipa-wholedisk-agent_ipmitool-tinyipa-multinode:
            irrelevant-files:
              - ^(test-|)requirements.txt$
              - ^setup.cfg$
        # Temporary mark multinode job as NV.
        # see https://bugs.launchpad.net/ironic/+bug/1744139
        - ironic-grenade-dsvm-multinode-multitenant:
            voting: false
        - openstack-tox-lower-constraints
