# Generated by Django 2.0.7 on 2018-07-12 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qb', '0006_feature_order_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='feature',
            name='order_asc',
            field=models.BooleanField(default=False),
        ),
    ]
