
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2018-07-19T14:37:17-0700",
 "dirty": false,
 "error": null,
 "full-revisionid": "76b76bea2a651ff34ce1ace419fdab4857c41b33",
 "version": "0.2.1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
