language: python
sudo: required
dist: trusty
cache: pip

matrix:
  include:
    - python: 3.4
    - python: 3.5
    - python: 3.6

install:
  # setup conda
  # Used from https://conda.io/docs/user-guide/tasks/use-conda-with-travis-ci.html
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  - conda info -a

  # test-environment
  - conda create -q -n test-environment python=$TRAVIS_PYTHON_VERSION pytest
  - source activate test-environment
  - python --version
  - pip install --upgrade pip
  - pip --version

  # install the repository
  - pip install '.'

script:
  - PYTHONPATH=$PWD:$PYTHONPATH py.test tests/

