- project:
    check:
      jobs:
        - ironic-inspector-grenade-dsvm
        - ironic-inspector-tempest-dsvm-discovery
        - ironic-inspector-tempest-dsvm-python3
        - openstack-tox-functional
        - openstack-tox-functional-py35
        - ironic-tempest-dsvm-ironic-inspector
        - openstack-tox-lower-constraints
    gate:
      queue: ironic
      jobs:
        - ironic-inspector-grenade-dsvm
        - ironic-inspector-tempest-dsvm-discovery
        - ironic-inspector-tempest-dsvm-python3
        - openstack-tox-functional
        - openstack-tox-functional-py35
        - ironic-tempest-dsvm-ironic-inspector
        - openstack-tox-lower-constraints
