environment:
  matrix:
  # note: please use "tox --listenvs" to populate the build matrix
  - TOXENV: "py27-pytest33"
  - TOXENV: "py34-pytest33"
  - TOXENV: "py35-pytest33"
  - TOXENV: "py36-pytest33"
  - TOXENV: "py27-pytest33-pexpect"
  - TOXENV: "py36-pytest33-pexpect"
  - TOXENV: "flakes"
  - TOXENV: "readme"

install:
  - C:\Python35\python -m pip install -U tox setuptools_scm pip

build: false  # Not a C# project, build stuff at the test step instead.

test_script:
  - C:\Python35\python -m tox
