"""
generated by restae-admin

Area models and serializers
"""

from google.appengine.ext import ndb
from restae.serializers import ModelSerializer


class Area(ndb.Model):
    """
    Area models class
    """
    pass


class AreaSerializer(ModelSerializer):
    """
    Area serializer
    """
    class Meta:
        fields = '__all__'

