sudo: false
cache: pip
services:
- mysql
language: python
python: 3.6
env:
  global:
  - BIO2BEL_CONNECTION=mysql+pymysql://travis@localhost/bio2bel?charset=utf8'
matrix:
  include:
    - env: TOXENV=py
    - env: TOXENV=docs
    - env: TOXENV=manifest
    - env: TOXENV=rst-lint
    - env: TOXENV=flake8
  allow_failures:
    - env: TOXENV=flake8
before_install:
- pip install codecov
- pip install pymysql
- mysql -e 'CREATE DATABASE bio2bel CHARACTER SET utf8 COLLATE utf8_general_ci;'
- mysql -e "GRANT ALL PRIVILEGES ON bio2bel.* to 'travis'@'%' WITH GRANT OPTION;"
install:
- pip install tox
- pip install codecov
- pip install coverage
script:
- tox
after_success:
- tox -e coverage-report
- codecov
notifications:
  slack: pybel:n2KbWKBum3musnBg3L76gGwq
