{
  "branches": {
    "only": [
      "auto",
      "master",
      "/^.*-maintenance$/"
    ]
  },
  "cache": "pip",
  "dist": "trusty",
  "git": {
    "submodules": false
  },
  "install": [
    ". scripts/travis-install.sh",
    "pip install -U pip setuptools",
    "pip install wheel",
    "make -e install-dev",
    "make -e install-$BUILD"
  ],
  "language": "python",
  "matrix": {
    "include": [
      {
        "env": "BUILD=style",
        "python": "3.6"
      },
      {
        "env": "BUILD=test DAV_SERVER=radicale REQUIREMENTS=devel ",
        "python": "3.4"
      },
      {
        "env": "BUILD=test DAV_SERVER=xandikos REQUIREMENTS=devel ",
        "python": "3.4"
      },
      {
        "env": "BUILD=test DAV_SERVER=radicale REQUIREMENTS=release ",
        "python": "3.4"
      },
      {
        "env": "BUILD=test DAV_SERVER=xandikos REQUIREMENTS=release ",
        "python": "3.4"
      },
      {
        "env": "BUILD=test DAV_SERVER=radicale REQUIREMENTS=minimal ",
        "python": "3.4"
      },
      {
        "env": "BUILD=test DAV_SERVER=xandikos REQUIREMENTS=minimal ",
        "python": "3.4"
      },
      {
        "env": "BUILD=test DAV_SERVER=radicale REQUIREMENTS=devel ",
        "python": "3.5"
      },
      {
        "env": "BUILD=test DAV_SERVER=xandikos REQUIREMENTS=devel ",
        "python": "3.5"
      },
      {
        "env": "BUILD=test DAV_SERVER=radicale REQUIREMENTS=release ",
        "python": "3.5"
      },
      {
        "env": "BUILD=test DAV_SERVER=xandikos REQUIREMENTS=release ",
        "python": "3.5"
      },
      {
        "env": "BUILD=test DAV_SERVER=radicale REQUIREMENTS=minimal ",
        "python": "3.5"
      },
      {
        "env": "BUILD=test DAV_SERVER=xandikos REQUIREMENTS=minimal ",
        "python": "3.5"
      },
      {
        "env": "BUILD=test DAV_SERVER=radicale REQUIREMENTS=devel ",
        "python": "3.6"
      },
      {
        "env": "BUILD=test DAV_SERVER=xandikos REQUIREMENTS=devel ",
        "python": "3.6"
      },
      {
        "env": "BUILD=test DAV_SERVER=radicale REQUIREMENTS=release ",
        "python": "3.6"
      },
      {
        "env": "BUILD=test DAV_SERVER=xandikos REQUIREMENTS=release ",
        "python": "3.6"
      },
      {
        "env": "BUILD=test DAV_SERVER=fastmail REQUIREMENTS=release ",
        "if": "NOT (type IN (pull_request))",
        "python": "3.6"
      },
      {
        "env": "BUILD=test DAV_SERVER=radicale REQUIREMENTS=minimal ",
        "python": "3.6"
      },
      {
        "env": "BUILD=test DAV_SERVER=xandikos REQUIREMENTS=minimal ",
        "python": "3.6"
      },
      {
        "env": "BUILD=test ETESYNC_TESTS=true REQUIREMENTS=latest",
        "python": "3.6"
      },
      {
        "env": "BUILD=test",
        "language": "generic",
        "os": "osx"
      }
    ]
  },
  "script": [
    "make -e $BUILD"
  ],
  "sudo": true
}