
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2018-07-30T11:06:52+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "6d95295bf06666eff5b6d0799b93761d9af3c25e",
 "version": "18.1.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
