# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'qoob/gui_main.ui'
#
# Created by: PyQt5 UI code generator 5.11.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 620)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_4.setContentsMargins(10, 10, 10, 10)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.slider = QtWidgets.QSlider(self.centralwidget)
        self.slider.setOrientation(QtCore.Qt.Horizontal)
        self.slider.setObjectName("slider")
        self.gridLayout_4.addWidget(self.slider, 0, 0, 1, 2)
        self.shuffleButton = QtWidgets.QToolButton(self.centralwidget)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("icons/shuffle_off.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.shuffleButton.setIcon(icon)
        self.shuffleButton.setObjectName("shuffleButton")
        self.gridLayout_4.addWidget(self.shuffleButton, 0, 6, 1, 1)
        self.previousButton = QtWidgets.QToolButton(self.centralwidget)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("icons/previous.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.previousButton.setIcon(icon1)
        self.previousButton.setObjectName("previousButton")
        self.gridLayout_4.addWidget(self.previousButton, 0, 4, 1, 1)
        self.nextButton = QtWidgets.QToolButton(self.centralwidget)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("icons/next.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.nextButton.setIcon(icon2)
        self.nextButton.setObjectName("nextButton")
        self.gridLayout_4.addWidget(self.nextButton, 0, 5, 1, 1)
        self.stopButton = QtWidgets.QToolButton(self.centralwidget)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("icons/stop.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.stopButton.setIcon(icon3)
        self.stopButton.setObjectName("stopButton")
        self.gridLayout_4.addWidget(self.stopButton, 0, 2, 1, 1)
        self.playButton = QtWidgets.QToolButton(self.centralwidget)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("icons/play.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.playButton.setIcon(icon4)
        self.playButton.setObjectName("playButton")
        self.gridLayout_4.addWidget(self.playButton, 0, 3, 1, 1)
        self.viewTab = QtWidgets.QTabWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(3)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.viewTab.sizePolicy().hasHeightForWidth())
        self.viewTab.setSizePolicy(sizePolicy)
        self.viewTab.setStyleSheet("")
        self.viewTab.setDocumentMode(True)
        self.viewTab.setTabsClosable(True)
        self.viewTab.setMovable(True)
        self.viewTab.setObjectName("viewTab")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.viewLayout = QtWidgets.QGridLayout(self.tab_3)
        self.viewLayout.setObjectName("viewLayout")
        self.viewTab.addTab(self.tab_3, "")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.viewTab.addTab(self.tab_4, "")
        self.gridLayout_4.addWidget(self.viewTab, 1, 1, 1, 6)
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabWidget.sizePolicy().hasHeightForWidth())
        self.tabWidget.setSizePolicy(sizePolicy)
        self.tabWidget.setMinimumSize(QtCore.QSize(300, 0))
        self.tabWidget.setMaximumSize(QtCore.QSize(300, 16777215))
        self.tabWidget.setDocumentMode(True)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.tab)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label = QtWidgets.QLabel(self.tab)
        self.label.setMaximumSize(QtCore.QSize(70, 16777215))
        self.label.setObjectName("label")
        self.gridLayout_2.addWidget(self.label, 1, 0, 1, 1)
        self.libraryFilterLine = QtWidgets.QLineEdit(self.tab)
        self.libraryFilterLine.setObjectName("libraryFilterLine")
        self.gridLayout_2.addWidget(self.libraryFilterLine, 1, 1, 1, 1)
        self.libraryTree = QtWidgets.QTreeWidget(self.tab)
        self.libraryTree.setAlternatingRowColors(True)
        self.libraryTree.setSelectionMode(QtWidgets.QAbstractItemView.ExtendedSelection)
        self.libraryTree.setIndentation(10)
        self.libraryTree.setObjectName("libraryTree")
        self.libraryTree.headerItem().setText(0, "1")
        self.libraryTree.header().setVisible(False)
        self.gridLayout_2.addWidget(self.libraryTree, 0, 0, 1, 3)
        self.libraryFilterClearButton = QtWidgets.QPushButton(self.tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.libraryFilterClearButton.sizePolicy().hasHeightForWidth())
        self.libraryFilterClearButton.setSizePolicy(sizePolicy)
        self.libraryFilterClearButton.setMaximumSize(QtCore.QSize(16, 16))
        self.libraryFilterClearButton.setStyleSheet("")
        self.libraryFilterClearButton.setText("")
        self.libraryFilterClearButton.setObjectName("libraryFilterClearButton")
        self.gridLayout_2.addWidget(self.libraryFilterClearButton, 1, 2, 1, 1)
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.tab_2)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.groupBox_2 = QtWidgets.QGroupBox(self.tab_2)
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.groupBox_2)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.trayIconBox = QtWidgets.QCheckBox(self.groupBox_2)
        self.trayIconBox.setObjectName("trayIconBox")
        self.gridLayout_5.addWidget(self.trayIconBox, 0, 0, 1, 2)
        self.trayNotifyBox = QtWidgets.QCheckBox(self.groupBox_2)
        self.trayNotifyBox.setObjectName("trayNotifyBox")
        self.gridLayout_5.addWidget(self.trayNotifyBox, 1, 0, 1, 2)
        self.trayMinimizeBox = QtWidgets.QCheckBox(self.groupBox_2)
        self.trayMinimizeBox.setObjectName("trayMinimizeBox")
        self.gridLayout_5.addWidget(self.trayMinimizeBox, 2, 0, 1, 2)
        self.gridLayout_6.addWidget(self.groupBox_2, 5, 0, 1, 1)
        self.groupBox_3 = QtWidgets.QGroupBox(self.tab_2)
        self.groupBox_3.setObjectName("groupBox_3")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.groupBox_3)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.resumePlaybackBox = QtWidgets.QCheckBox(self.groupBox_3)
        self.resumePlaybackBox.setObjectName("resumePlaybackBox")
        self.gridLayout_7.addWidget(self.resumePlaybackBox, 0, 0, 1, 2)
        self.fileManagerLine = QtWidgets.QLineEdit(self.groupBox_3)
        self.fileManagerLine.setObjectName("fileManagerLine")
        self.gridLayout_7.addWidget(self.fileManagerLine, 7, 1, 1, 1)
        self.deleteConfirmBox = QtWidgets.QCheckBox(self.groupBox_3)
        self.deleteConfirmBox.setObjectName("deleteConfirmBox")
        self.gridLayout_7.addWidget(self.deleteConfirmBox, 2, 0, 1, 2)
        self.label_3 = QtWidgets.QLabel(self.groupBox_3)
        self.label_3.setObjectName("label_3")
        self.gridLayout_7.addWidget(self.label_3, 7, 0, 1, 1)
        self.cleanFolderBox = QtWidgets.QCheckBox(self.groupBox_3)
        self.cleanFolderBox.setObjectName("cleanFolderBox")
        self.gridLayout_7.addWidget(self.cleanFolderBox, 3, 0, 1, 2)
        self.sortByDefaultBox = QtWidgets.QCheckBox(self.groupBox_3)
        self.sortByDefaultBox.setObjectName("sortByDefaultBox")
        self.gridLayout_7.addWidget(self.sortByDefaultBox, 5, 0, 1, 2)
        self.expandLibraryBox = QtWidgets.QCheckBox(self.groupBox_3)
        self.expandLibraryBox.setObjectName("expandLibraryBox")
        self.gridLayout_7.addWidget(self.expandLibraryBox, 4, 0, 1, 2)
        self.gridLayout_6.addWidget(self.groupBox_3, 1, 0, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(0, 0, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_6.addItem(spacerItem, 6, 0, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(0, 0, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_6.addItem(spacerItem1, 4, 0, 1, 1)
        self.groupBox_5 = QtWidgets.QGroupBox(self.tab_2)
        self.groupBox_5.setObjectName("groupBox_5")
        self.gridLayout_9 = QtWidgets.QGridLayout(self.groupBox_5)
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.titleFormatLine = QtWidgets.QLineEdit(self.groupBox_5)
        self.titleFormatLine.setObjectName("titleFormatLine")
        self.gridLayout_9.addWidget(self.titleFormatLine, 1, 1, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.groupBox_5)
        self.label_5.setObjectName("label_5")
        self.gridLayout_9.addWidget(self.label_5, 3, 0, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.groupBox_5)
        self.label_7.setObjectName("label_7")
        self.gridLayout_9.addWidget(self.label_7, 1, 0, 1, 1)
        self.tooltipFormatLine = QtWidgets.QLineEdit(self.groupBox_5)
        self.tooltipFormatLine.setObjectName("tooltipFormatLine")
        self.gridLayout_9.addWidget(self.tooltipFormatLine, 3, 1, 1, 1)
        self.stripTitlesBox = QtWidgets.QCheckBox(self.groupBox_5)
        self.stripTitlesBox.setObjectName("stripTitlesBox")
        self.gridLayout_9.addWidget(self.stripTitlesBox, 0, 0, 1, 2)
        self.gridLayout_6.addWidget(self.groupBox_5, 3, 0, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(0, 0, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_6.addItem(spacerItem2, 2, 0, 1, 1)
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_5 = QtWidgets.QWidget()
        self.tab_5.setObjectName("tab_5")
        self.gridLayout = QtWidgets.QGridLayout(self.tab_5)
        self.gridLayout.setObjectName("gridLayout")
        self.groupBox_4 = QtWidgets.QGroupBox(self.tab_5)
        self.groupBox_4.setObjectName("groupBox_4")
        self.gridLayout_8 = QtWidgets.QGridLayout(self.groupBox_4)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.dbLine = QtWidgets.QLineEdit(self.groupBox_4)
        self.dbLine.setObjectName("dbLine")
        self.gridLayout_8.addWidget(self.dbLine, 2, 0, 1, 4)
        self.dbAddButton = QtWidgets.QPushButton(self.groupBox_4)
        self.dbAddButton.setObjectName("dbAddButton")
        self.gridLayout_8.addWidget(self.dbAddButton, 3, 0, 1, 1)
        self.dbDeleteButton = QtWidgets.QPushButton(self.groupBox_4)
        self.dbDeleteButton.setObjectName("dbDeleteButton")
        self.gridLayout_8.addWidget(self.dbDeleteButton, 3, 1, 1, 1)
        self.dbTree = QtWidgets.QTreeWidget(self.groupBox_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dbTree.sizePolicy().hasHeightForWidth())
        self.dbTree.setSizePolicy(sizePolicy)
        self.dbTree.setAlternatingRowColors(True)
        self.dbTree.setRootIsDecorated(False)
        self.dbTree.setObjectName("dbTree")
        self.dbTree.header().setDefaultSectionSize(155)
        self.dbTree.header().setStretchLastSection(True)
        self.gridLayout_8.addWidget(self.dbTree, 1, 0, 1, 5)
        self.refreshButton = QtWidgets.QToolButton(self.groupBox_4)
        self.refreshButton.setMinimumSize(QtCore.QSize(30, 0))
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap("icons/refresh.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.refreshButton.setIcon(icon5)
        self.refreshButton.setObjectName("refreshButton")
        self.gridLayout_8.addWidget(self.refreshButton, 3, 4, 1, 1)
        self.dbBrowseButton = QtWidgets.QToolButton(self.groupBox_4)
        self.dbBrowseButton.setObjectName("dbBrowseButton")
        self.gridLayout_8.addWidget(self.dbBrowseButton, 2, 4, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.groupBox_4)
        self.label_2.setObjectName("label_2")
        self.gridLayout_8.addWidget(self.label_2, 0, 0, 1, 2)
        self.monitorIntervalBox = QtWidgets.QSpinBox(self.groupBox_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.monitorIntervalBox.sizePolicy().hasHeightForWidth())
        self.monitorIntervalBox.setSizePolicy(sizePolicy)
        self.monitorIntervalBox.setMaximumSize(QtCore.QSize(50, 16777215))
        self.monitorIntervalBox.setMaximum(960)
        self.monitorIntervalBox.setSingleStep(5)
        self.monitorIntervalBox.setObjectName("monitorIntervalBox")
        self.gridLayout_8.addWidget(self.monitorIntervalBox, 0, 3, 1, 2)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_8.addItem(spacerItem3, 0, 2, 1, 1)
        self.gridLayout.addWidget(self.groupBox_4, 0, 0, 1, 1)
        spacerItem4 = QtWidgets.QSpacerItem(20, 35, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout.addItem(spacerItem4, 1, 0, 1, 1)
        self.groupBox = QtWidgets.QGroupBox(self.tab_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox.sizePolicy().hasHeightForWidth())
        self.groupBox.setSizePolicy(sizePolicy)
        self.groupBox.setMaximumSize(QtCore.QSize(16777215, 200))
        self.groupBox.setObjectName("groupBox")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.sortSelectedList = QtWidgets.QListWidget(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sortSelectedList.sizePolicy().hasHeightForWidth())
        self.sortSelectedList.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(7)
        self.sortSelectedList.setFont(font)
        self.sortSelectedList.setDragDropMode(QtWidgets.QAbstractItemView.InternalMove)
        self.sortSelectedList.setObjectName("sortSelectedList")
        self.gridLayout_3.addWidget(self.sortSelectedList, 1, 0, 3, 1)
        spacerItem5 = QtWidgets.QSpacerItem(21, 89, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_3.addItem(spacerItem5, 3, 1, 1, 1)
        self.sortRemoveButton = QtWidgets.QToolButton(self.groupBox)
        self.sortRemoveButton.setArrowType(QtCore.Qt.RightArrow)
        self.sortRemoveButton.setObjectName("sortRemoveButton")
        self.gridLayout_3.addWidget(self.sortRemoveButton, 1, 1, 1, 1)
        self.sortAddButton = QtWidgets.QToolButton(self.groupBox)
        self.sortAddButton.setArrowType(QtCore.Qt.LeftArrow)
        self.sortAddButton.setObjectName("sortAddButton")
        self.gridLayout_3.addWidget(self.sortAddButton, 2, 1, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.groupBox)
        self.label_6.setObjectName("label_6")
        self.gridLayout_3.addWidget(self.label_6, 0, 2, 1, 1)
        self.sortAvailableList = QtWidgets.QListWidget(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sortAvailableList.sizePolicy().hasHeightForWidth())
        self.sortAvailableList.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(7)
        self.sortAvailableList.setFont(font)
        self.sortAvailableList.setDragDropMode(QtWidgets.QAbstractItemView.InternalMove)
        self.sortAvailableList.setObjectName("sortAvailableList")
        self.gridLayout_3.addWidget(self.sortAvailableList, 1, 2, 3, 1)
        self.label_4 = QtWidgets.QLabel(self.groupBox)
        self.label_4.setObjectName("label_4")
        self.gridLayout_3.addWidget(self.label_4, 0, 0, 1, 1)
        self.gridLayout.addWidget(self.groupBox, 2, 0, 1, 1)
        self.tabWidget.addTab(self.tab_5, "")
        self.gridLayout_4.addWidget(self.tabWidget, 1, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 20))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.shuffleButton.setText(_translate("MainWindow", "..."))
        self.previousButton.setText(_translate("MainWindow", "..."))
        self.nextButton.setText(_translate("MainWindow", "..."))
        self.stopButton.setText(_translate("MainWindow", "..."))
        self.playButton.setText(_translate("MainWindow", "..."))
        self.viewTab.setTabText(self.viewTab.indexOf(self.tab_3), _translate("MainWindow", "Library viewer"))
        self.label.setText(_translate("MainWindow", "Filter"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Library"))
        self.groupBox_2.setTitle(_translate("MainWindow", "System tray icon"))
        self.trayIconBox.setText(_translate("MainWindow", "Show tray icon"))
        self.trayNotifyBox.setText(_translate("MainWindow", "Show notifications"))
        self.trayMinimizeBox.setText(_translate("MainWindow", "Minimize to tray"))
        self.groupBox_3.setTitle(_translate("MainWindow", "General"))
        self.resumePlaybackBox.setText(_translate("MainWindow", "Resume playback"))
        self.deleteConfirmBox.setText(_translate("MainWindow", "Confirm before deletion"))
        self.label_3.setText(_translate("MainWindow", "File manager"))
        self.cleanFolderBox.setText(_translate("MainWindow", "Remove empty folders"))
        self.sortByDefaultBox.setText(_translate("MainWindow", "Enable sorting by default"))
        self.expandLibraryBox.setText(_translate("MainWindow", "Auto expand library view"))
        self.groupBox_5.setTitle(_translate("MainWindow", "Format"))
        self.label_5.setText(_translate("MainWindow", "Tooltip format"))
        self.label_7.setText(_translate("MainWindow", "Title format"))
        self.stripTitlesBox.setText(_translate("MainWindow", "Strip redundancy from headerless titles"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Options"))
        self.groupBox_4.setTitle(_translate("MainWindow", "Library monitoring"))
        self.dbAddButton.setText(_translate("MainWindow", "Add"))
        self.dbDeleteButton.setText(_translate("MainWindow", "Delete"))
        self.dbTree.headerItem().setText(0, _translate("MainWindow", "Library paths"))
        self.dbTree.headerItem().setText(1, _translate("MainWindow", "Status"))
        self.refreshButton.setText(_translate("MainWindow", "..."))
        self.dbBrowseButton.setText(_translate("MainWindow", "..."))
        self.label_2.setText(_translate("MainWindow", "Scan interval (minutes)"))
        self.groupBox.setTitle(_translate("MainWindow", "Sorting routine"))
        self.label_6.setText(_translate("MainWindow", "Available"))
        self.label_4.setText(_translate("MainWindow", "Selected"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_5), _translate("MainWindow", "Advanced"))

