# coding: utf-8
# Generated by setup.py for PyCBC on 2018-07-17 11:24:40 +0000.

version = '1.11.3'
date = '2018-07-17 09:50:03 +0000'
release = True
last_release = '1.11.3'

git_hash = 'f9ea7321a8bdf9c236d98cb354bb1f362ed3909a'
git_branch = 'None'
git_tag = 'v1.11.3'
git_author = 'Ian Harry <ian.harry@ligo.org>'
git_committer = 'Ian Harry <ian.harry@ligo.org>'
git_status = 'CLEAN: All modifications committed'
git_builder = 'Travis CI User <travis@example.org>'
git_build_date = '2018-07-17 11:24:40 +0000'
git_verbose_msg = """Branch: None
Tag: v1.11.3
Id: f9ea7321a8bdf9c236d98cb354bb1f362ed3909a
Builder: Travis CI User <travis@example.org>
Build date: 2018-07-17 11:24:40 +0000
Repository status is CLEAN: All modifications committed"""
from pycbc._version import *
