# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-25 06:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ModelA",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=64, unique=True)),
                ("category", models.CharField(max_length=64)),
                ("blank", models.CharField(blank=True, max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name="ModelB",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=64, unique=True)),
                (
                    "nullable_a1",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="testapp.ModelA",
                    ),
                ),
                (
                    "nullable_a2",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="testapp.ModelA",
                    ),
                ),
                (
                    "required_a",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="testapp.ModelA"
                    ),
                ),
            ],
        ),
    ]
