
# This file was generated by 'versioneer.py' (0.15+dev) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json
import sys

version_json = '''
{
 "dirty": false,
 "error": null,
 "full-revisionid": "c7d726f6292e9bf7271f5b3947b53020d67834c7",
 "version": "0.1.post23"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
