language: python

python:
  - "2.7"

before_install:
  - pip install .
  - pip install twine

script:
  - python -m benchpress.testing

deploy:
  provider: script
  script: python setup.py sdist && ls dist/* && twine upload dist/*
  on:
    branch: master
