
# This file was generated by 'versioneer.py' (0.15) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json
import sys

version_json = '''
{
 "dirty": false,
 "error": null,
 "full-revisionid": "a562d028e53e740e4b40a7fb4a6600bfb410d521",
 "version": "1979"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
