# -*- coding: utf-8 -*-
#
# THIS FILE IS AUTOGENERATED FROM SETUP.PY. DO NOT EDIT.
#
public_version   = "0.0.11"
local_version    = "0.0.11+20180727T020735Z.315565b7b2df162c38d62abdb00ef1a52ca7a38e"
sem_version      = "0.0.11+buildtime.20180727T020735Z.git.315565b7b2df162c38d62abdb00ef1a52ca7a38e"

release_version  = "0.0.11"
__version__      = "0.0.11"
release          = True

vcs_tag          = "315565b7b2df162c38d62abdb00ef1a52ca7a38e"
vcs_clean        = True
build_time_posix = 1532657255
build_time_iso   = "20180727T020735Z"
