
# This file was generated by 'versioneer.py' (0.15) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json
import sys

version_json = '''
{
 "dirty": false,
 "error": null,
 "full-revisionid": "f8b7f04bb7baaa3e4faff19bde763cc831c2e086",
 "version": "v0.1.1-alpha.post.dev73"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
