# Generated by Django 2.0.7 on 2018-07-18 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tokenservice', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tokenapp',
            name='token',
            field=models.SlugField(editable=False, max_length=20, unique=True),
        ),
    ]
