# Generated by Django 2.0.7 on 2018-07-18 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tokenservice', '0002_auto_20180718_1111'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tokenapp',
            name='last_login',
        ),
        migrations.RemoveField(
            model_name='tokenapp',
            name='password',
        ),
    ]
