# coding: utf-8

"""
    Dash Auth API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: v1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six


class UserAddress(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'street_address': 'str',
        'locality': 'str',
        'region': 'str',
        'post_code': 'str'
    }

    attribute_map = {
        'street_address': 'streetAddress',
        'locality': 'locality',
        'region': 'region',
        'post_code': 'postCode'
    }

    def __init__(self, street_address=None, locality=None, region=None, post_code=None):  # noqa: E501
        """UserAddress - a model defined in Swagger"""  # noqa: E501

        self._street_address = None
        self._locality = None
        self._region = None
        self._post_code = None
        self.discriminator = None

        if street_address is not None:
            self.street_address = street_address
        if locality is not None:
            self.locality = locality
        if region is not None:
            self.region = region
        if post_code is not None:
            self.post_code = post_code

    @property
    def street_address(self):
        """Gets the street_address of this UserAddress.  # noqa: E501


        :return: The street_address of this UserAddress.  # noqa: E501
        :rtype: str
        """
        return self._street_address

    @street_address.setter
    def street_address(self, street_address):
        """Sets the street_address of this UserAddress.


        :param street_address: The street_address of this UserAddress.  # noqa: E501
        :type: str
        """

        self._street_address = street_address

    @property
    def locality(self):
        """Gets the locality of this UserAddress.  # noqa: E501


        :return: The locality of this UserAddress.  # noqa: E501
        :rtype: str
        """
        return self._locality

    @locality.setter
    def locality(self, locality):
        """Sets the locality of this UserAddress.


        :param locality: The locality of this UserAddress.  # noqa: E501
        :type: str
        """

        self._locality = locality

    @property
    def region(self):
        """Gets the region of this UserAddress.  # noqa: E501


        :return: The region of this UserAddress.  # noqa: E501
        :rtype: str
        """
        return self._region

    @region.setter
    def region(self, region):
        """Sets the region of this UserAddress.


        :param region: The region of this UserAddress.  # noqa: E501
        :type: str
        """

        self._region = region

    @property
    def post_code(self):
        """Gets the post_code of this UserAddress.  # noqa: E501


        :return: The post_code of this UserAddress.  # noqa: E501
        :rtype: str
        """
        return self._post_code

    @post_code.setter
    def post_code(self, post_code):
        """Sets the post_code of this UserAddress.


        :param post_code: The post_code of this UserAddress.  # noqa: E501
        :type: str
        """

        self._post_code = post_code

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, UserAddress):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
