
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2018-07-19T15:47:03+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "d6c1f571890d43b2817882642002b4deffe13da8",
 "version": "0.4a22"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
