---
- include: register.yml
  when: inventory_hostname in groups['murano-api']

- include: config.yml
  when: inventory_hostname in groups['murano-api'] or
        inventory_hostname in groups['murano-engine']

- include: clone.yml
  when:
    - murano_dev_mode | bool
    - inventory_hostname in groups['murano-api'] or
      inventory_hostname in groups['murano-engine']

- include: bootstrap.yml
  when: inventory_hostname in groups['murano-api']

- name: Flush handlers
  meta: flush_handlers

- include: import_library_packages.yml
