language: python

matrix:
  include:
    - python: "2.7"
      before_install:
        - pip install coveralls pylint
      env: COVERAGE="--with-coverage --cover-package=rebench"
      after_success:
        coveralls
    - python: "3.6"
      before_install:
        - pip install coveralls pylint
    # PyPy versions
    - python: pypy
      env: DO_LINT="echo On PyPy, we won't "
    - python: pypy3
      env: DO_LINT="echo On PyPy, we won't "

dist: trusty
sudo: false

addons:
  apt:
    packages:
      - time

install:
  - pip install .

# command to run tests
script:
 - nosetests ${COVERAGE}
 - (cd rebench && rebench -N ../rebench.conf e:TestRunner2)
 - ${DO_LINT} pylint rebench
