sudo: false

cache:
  directories:
    - $HOME/.cache/pip

language: python

matrix:
    include:
        - python: '3.4'
          env: TOXENV=py34
        - python: '3.5'
          env: TOXENV=py35
        - python: '3.6'
          env: TOXENV=py36
        - python: 'pypy3'
          env: TOXENV=pypy3
        - python: '3.6'
          env: TOXENV=py3,coverage
        - python: '3.6'
          env: TOXENV=lint

install:
  - travis_retry pip install tox

script:
  - travis_retry tox
