- project:
    check:
      jobs:
        - networking-baremetal-dsvm-multitenant-vlans
        - openstack-tox-lower-constraints
    gate:
      jobs:
        - networking-baremetal-dsvm-multitenant-vlans
        - openstack-tox-lower-constraints
