# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: matildapeak/chronicler/EventCategoryEnum.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='matildapeak/chronicler/EventCategoryEnum.proto',
  package='matildapeak.chronicler',
  syntax='proto3',
  serialized_pb=_b('\n.matildapeak/chronicler/EventCategoryEnum.proto\x12\x16matildapeak.chronicler*u\n\x11\x45ventCategoryEnum\x12 \n\x1c\x45VENT_CATEGORY_CUSTOMER_DATA\x10\x00\x12 \n\x1c\x45VENT_CATEGORY_END_OF_STREAM\x10\x01\x12\x1c\n\x18\x45VENT_CATEGORY_HEARTBEAT\x10\x02\x62\x06proto3')
)

_EVENTCATEGORYENUM = _descriptor.EnumDescriptor(
  name='EventCategoryEnum',
  full_name='matildapeak.chronicler.EventCategoryEnum',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='EVENT_CATEGORY_CUSTOMER_DATA', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='EVENT_CATEGORY_END_OF_STREAM', index=1, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='EVENT_CATEGORY_HEARTBEAT', index=2, number=2,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=74,
  serialized_end=191,
)
_sym_db.RegisterEnumDescriptor(_EVENTCATEGORYENUM)

EventCategoryEnum = enum_type_wrapper.EnumTypeWrapper(_EVENTCATEGORYENUM)
EVENT_CATEGORY_CUSTOMER_DATA = 0
EVENT_CATEGORY_END_OF_STREAM = 1
EVENT_CATEGORY_HEARTBEAT = 2


DESCRIPTOR.enum_types_by_name['EventCategoryEnum'] = _EVENTCATEGORYENUM
_sym_db.RegisterFileDescriptor(DESCRIPTOR)


# @@protoc_insertion_point(module_scope)
