
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2018-07-17T21:36:29-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "bc71a40e70abd14478a457cc08aacff6e317c1b2",
 "version": "0.0.1rc1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
