language: python
python:
- 2.7.3
- 2.7.9
- 2.7
- 3.4
- 3.5
- 3.6
install:
- pip install --upgrade pip
- pip install coveralls
- pip install -r requirements_dev.txt
- pip install . --no-deps
script:
- py.test
deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  user: BYPyPi
  password:
    secure: Tn5/u/57ChC0nJNARfb2ZCz2SKMEivIM5uT4rD3Wq8P/4JptuiGY7+/ZSoTCFPxyDFx2Hx2H7+4RzktqeUwAE8ybr4E6gR+z8FCGF92Yw6+2NzR40nTd/70ISsOPNHjV5sOVamUpyyVnDAX/dNEl4gwHLbsesZVHVAu5UOjeZBzTYruTbQcYn7Aw5FRwWm2tRzl7HrPEUB4qOqJzvHWeFydQnAup9q78EzJy6n9y4ZHNaf8Xg6YnUkStgm2vePO5Ufho8d7glZ2j4nS4Y2Jcv2lwFjHQDpk9Hq9hxIw6ohcZYdK6Xu09fsf2SlGR3v1P++6o9WAwfQ/K3W50bOS92ybpeiCOo/pBjekoUX6T96IOZw+eikxgv+F+3x9UMEQkzM96X7JDBe4GL35fLzQqp2NPexz5Lx9hlFaJJGcuMhQLXgQ54DIUAU7TC7Tpp5SiOYcBVb0P+0Y/hvU0ZfMfSJSM0a2T82MiS31AUmcdJrJaSXcWLG+LCYfaZumUsKcC4GxCTqgcVFo37yjjRI3snvMG3RghPf0VyUtR/j1MT5yxYeibWtxp794CC3qqiN2E53xtzDz0IJ5gUEIhJ5faBgWrqXelA6oIElm2a0uhJx45dYGGXUXAz+V7v87jaSNAP8q0CDGKhTFUBgeCWmjPSa+zWPJr5qqlJiIa5XTfNNw=
  on:
    tags: true
after_success:
- coveralls
