
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2018-07-23T05:51:53-0700",
 "dirty": false,
 "error": null,
 "full-revisionid": "6912ac9f549a61e8f4857c217a16dc0e8a23194e",
 "version": "1.6.45"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
