# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created: Fri May 25 00:08:23 2018
#      by: PyQt4 UI code generator 4.9.6
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(684, 643)
        MainWindow.setDocumentMode(False)
        MainWindow.setTabShape(QtGui.QTabWidget.Rounded)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.centralwidget)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.tabWidget = QtGui.QTabWidget(self.centralwidget)
        self.tabWidget.setMinimumSize(QtCore.QSize(650, 200))
        self.tabWidget.setMaximumSize(QtCore.QSize(650, 200))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.tabWidget.setFont(font)
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setObjectName(_fromUtf8("tab_2"))
        self.pushButton_Concrete_Check_and_save = QtGui.QPushButton(self.tab_2)
        self.pushButton_Concrete_Check_and_save.setGeometry(QtCore.QRect(120, 10, 161, 27))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.pushButton_Concrete_Check_and_save.setFont(font)
        self.pushButton_Concrete_Check_and_save.setObjectName(_fromUtf8("pushButton_Concrete_Check_and_save"))
        self.pushButton_Concrete_Show_dep_and_save = QtGui.QPushButton(self.tab_2)
        self.pushButton_Concrete_Show_dep_and_save.setGeometry(QtCore.QRect(10, 40, 271, 27))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.pushButton_Concrete_Show_dep_and_save.setFont(font)
        self.pushButton_Concrete_Show_dep_and_save.setObjectName(_fromUtf8("pushButton_Concrete_Show_dep_and_save"))
        self.pushButton_Concrete_Check = QtGui.QPushButton(self.tab_2)
        self.pushButton_Concrete_Check.setGeometry(QtCore.QRect(10, 10, 101, 27))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.pushButton_Concrete_Check.setFont(font)
        self.pushButton_Concrete_Check.setObjectName(_fromUtf8("pushButton_Concrete_Check"))
        self.pushButton_Concrete_Process = QtGui.QPushButton(self.tab_2)
        self.pushButton_Concrete_Process.setGeometry(QtCore.QRect(310, 10, 301, 27))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.pushButton_Concrete_Process.setFont(font)
        self.pushButton_Concrete_Process.setObjectName(_fromUtf8("pushButton_Concrete_Process"))
        self.pushButton_Concrete_Process_renum = QtGui.QPushButton(self.tab_2)
        self.pushButton_Concrete_Process_renum.setGeometry(QtCore.QRect(310, 40, 301, 27))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.pushButton_Concrete_Process_renum.setFont(font)
        self.pushButton_Concrete_Process_renum.setObjectName(_fromUtf8("pushButton_Concrete_Process_renum"))
        self.pushButton_Concrete_Process_renum_schedules = QtGui.QPushButton(self.tab_2)
        self.pushButton_Concrete_Process_renum_schedules.setGeometry(QtCore.QRect(310, 70, 301, 27))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.pushButton_Concrete_Process_renum_schedules.setFont(font)
        self.pushButton_Concrete_Process_renum_schedules.setObjectName(_fromUtf8("pushButton_Concrete_Process_renum_schedules"))
        self.pushButton_Concrete_help = QtGui.QPushButton(self.tab_2)
        self.pushButton_Concrete_help.setGeometry(QtCore.QRect(10, 140, 101, 27))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.pushButton_Concrete_help.setFont(font)
        self.pushButton_Concrete_help.setObjectName(_fromUtf8("pushButton_Concrete_help"))
        self.line = QtGui.QFrame(self.tab_2)
        self.line.setGeometry(QtCore.QRect(10, 110, 601, 20))
        font = QtGui.QFont()
        font.setPointSize(7)
        self.line.setFont(font)
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.pushButton_Concrete_check_for_quite_similare_bar_no = QtGui.QPushButton(self.tab_2)
        self.pushButton_Concrete_check_for_quite_similare_bar_no.setGeometry(QtCore.QRect(10, 70, 271, 27))
        self.pushButton_Concrete_check_for_quite_similare_bar_no.setObjectName(_fromUtf8("pushButton_Concrete_check_for_quite_similare_bar_no"))
        self.tabWidget.addTab(self.tab_2, _fromUtf8(""))
        self.tab = QtGui.QWidget()
        self.tab.setObjectName(_fromUtf8("tab"))
        self.pushButton_Steel_Check = QtGui.QPushButton(self.tab)
        self.pushButton_Steel_Check.setGeometry(QtCore.QRect(10, 10, 101, 27))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.pushButton_Steel_Check.setFont(font)
        self.pushButton_Steel_Check.setObjectName(_fromUtf8("pushButton_Steel_Check"))
        self.pushButton_Steel_Check_and_save = QtGui.QPushButton(self.tab)
        self.pushButton_Steel_Check_and_save.setGeometry(QtCore.QRect(120, 10, 161, 27))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.pushButton_Steel_Check_and_save.setFont(font)
        self.pushButton_Steel_Check_and_save.setObjectName(_fromUtf8("pushButton_Steel_Check_and_save"))
        self.pushButton_Steel_Show_dep_and_save = QtGui.QPushButton(self.tab)
        self.pushButton_Steel_Show_dep_and_save.setGeometry(QtCore.QRect(10, 40, 271, 27))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.pushButton_Steel_Show_dep_and_save.setFont(font)
        self.pushButton_Steel_Show_dep_and_save.setObjectName(_fromUtf8("pushButton_Steel_Show_dep_and_save"))
        self.pushButton_Steel_Process_renum = QtGui.QPushButton(self.tab)
        self.pushButton_Steel_Process_renum.setGeometry(QtCore.QRect(310, 40, 301, 27))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.pushButton_Steel_Process_renum.setFont(font)
        self.pushButton_Steel_Process_renum.setObjectName(_fromUtf8("pushButton_Steel_Process_renum"))
        self.pushButton_Steel_Process = QtGui.QPushButton(self.tab)
        self.pushButton_Steel_Process.setGeometry(QtCore.QRect(310, 10, 301, 27))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.pushButton_Steel_Process.setFont(font)
        self.pushButton_Steel_Process.setObjectName(_fromUtf8("pushButton_Steel_Process"))
        self.pushButton_Steel_Process_renum_schedules = QtGui.QPushButton(self.tab)
        self.pushButton_Steel_Process_renum_schedules.setGeometry(QtCore.QRect(310, 70, 301, 27))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.pushButton_Steel_Process_renum_schedules.setFont(font)
        self.pushButton_Steel_Process_renum_schedules.setObjectName(_fromUtf8("pushButton_Steel_Process_renum_schedules"))
        self.line_3 = QtGui.QFrame(self.tab)
        self.line_3.setGeometry(QtCore.QRect(10, 100, 591, 20))
        self.line_3.setFrameShape(QtGui.QFrame.HLine)
        self.line_3.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_3.setObjectName(_fromUtf8("line_3"))
        self.pushButton_Steel_help = QtGui.QPushButton(self.tab)
        self.pushButton_Steel_help.setGeometry(QtCore.QRect(10, 120, 101, 27))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.pushButton_Steel_help.setFont(font)
        self.pushButton_Steel_help.setObjectName(_fromUtf8("pushButton_Steel_help"))
        self.comboBox_Steel_sectgroup = QtGui.QComboBox(self.tab)
        self.comboBox_Steel_sectgroup.setGeometry(QtCore.QRect(310, 120, 171, 22))
        self.comboBox_Steel_sectgroup.setObjectName(_fromUtf8("comboBox_Steel_sectgroup"))
        self.label = QtGui.QLabel(self.tab)
        self.label.setGeometry(QtCore.QRect(150, 120, 151, 20))
        self.label.setObjectName(_fromUtf8("label"))
        self.comboBox_Steel_secttype = QtGui.QComboBox(self.tab)
        self.comboBox_Steel_secttype.setGeometry(QtCore.QRect(500, 120, 101, 22))
        self.comboBox_Steel_secttype.setObjectName(_fromUtf8("comboBox_Steel_secttype"))
        self.tabWidget.addTab(self.tab, _fromUtf8(""))
        self.tab_4 = QtGui.QWidget()
        self.tab_4.setObjectName(_fromUtf8("tab_4"))
        self.pushButton_Command_do_all = QtGui.QPushButton(self.tab_4)
        self.pushButton_Command_do_all.setGeometry(QtCore.QRect(10, 50, 221, 27))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.pushButton_Command_do_all.setFont(font)
        self.pushButton_Command_do_all.setObjectName(_fromUtf8("pushButton_Command_do_all"))
        self.pushButton_Command_show = QtGui.QPushButton(self.tab_4)
        self.pushButton_Command_show.setGeometry(QtCore.QRect(10, 20, 221, 27))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.pushButton_Command_show.setFont(font)
        self.pushButton_Command_show.setObjectName(_fromUtf8("pushButton_Command_show"))
        self.line_4 = QtGui.QFrame(self.tab_4)
        self.line_4.setGeometry(QtCore.QRect(10, 100, 591, 20))
        self.line_4.setFrameShape(QtGui.QFrame.HLine)
        self.line_4.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_4.setObjectName(_fromUtf8("line_4"))
        self.pushButton_Command_help = QtGui.QPushButton(self.tab_4)
        self.pushButton_Command_help.setGeometry(QtCore.QRect(10, 120, 101, 27))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.pushButton_Command_help.setFont(font)
        self.pushButton_Command_help.setObjectName(_fromUtf8("pushButton_Command_help"))
        self.tabWidget.addTab(self.tab_4, _fromUtf8(""))
        self.tab_3 = QtGui.QWidget()
        self.tab_3.setObjectName(_fromUtf8("tab_3"))
        self.pushButton_Inject_to_file = QtGui.QPushButton(self.tab_3)
        self.pushButton_Inject_to_file.setGeometry(QtCore.QRect(10, 10, 221, 27))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.pushButton_Inject_to_file.setFont(font)
        self.pushButton_Inject_to_file.setObjectName(_fromUtf8("pushButton_Inject_to_file"))
        self.line_5 = QtGui.QFrame(self.tab_3)
        self.line_5.setGeometry(QtCore.QRect(10, 100, 591, 20))
        self.line_5.setFrameShape(QtGui.QFrame.HLine)
        self.line_5.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_5.setObjectName(_fromUtf8("line_5"))
        self.pushButton_System_help = QtGui.QPushButton(self.tab_3)
        self.pushButton_System_help.setGeometry(QtCore.QRect(10, 120, 101, 27))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.pushButton_System_help.setFont(font)
        self.pushButton_System_help.setObjectName(_fromUtf8("pushButton_System_help"))
        self.groupBox = QtGui.QGroupBox(self.tab_3)
        self.groupBox.setGeometry(QtCore.QRect(490, 10, 120, 61))
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.comboBox_language = QtGui.QComboBox(self.groupBox)
        self.comboBox_language.setGeometry(QtCore.QRect(10, 30, 101, 22))
        self.comboBox_language.setObjectName(_fromUtf8("comboBox_language"))
        self.tabWidget.addTab(self.tab_3, _fromUtf8(""))
        self.horizontalLayout_2.addWidget(self.tabWidget)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.textBrowser = QtGui.QTextBrowser(self.centralwidget)
        self.textBrowser.setMinimumSize(QtCore.QSize(0, 350))
        self.textBrowser.setObjectName(_fromUtf8("textBrowser"))
        self.verticalLayout.addWidget(self.textBrowser)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        spacerItem2 = QtGui.QSpacerItem(88, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem2)
        self.progressBar = QtGui.QProgressBar(self.centralwidget)
        self.progressBar.setEnabled(True)
        self.progressBar.setMaximumSize(QtCore.QSize(120, 16777215))
        self.progressBar.setProperty("value", 24)
        self.progressBar.setTextVisible(True)
        self.progressBar.setObjectName(_fromUtf8("progressBar"))
        self.horizontalLayout.addWidget(self.progressBar)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.verticalLayout_2.addLayout(self.verticalLayout)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 684, 18))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menuFile = QtGui.QMenu(self.menubar)
        self.menuFile.setObjectName(_fromUtf8("menuFile"))
        self.menuInfo = QtGui.QMenu(self.menubar)
        self.menuInfo.setObjectName(_fromUtf8("menuInfo"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)
        self.actionLoad_dxf = QtGui.QAction(MainWindow)
        self.actionLoad_dxf.setObjectName(_fromUtf8("actionLoad_dxf"))
        self.actionAbout = QtGui.QAction(MainWindow)
        self.actionAbout.setObjectName(_fromUtf8("actionAbout"))
        self.actionHelp = QtGui.QAction(MainWindow)
        self.actionHelp.setObjectName(_fromUtf8("actionHelp"))
        self.actionLicence = QtGui.QAction(MainWindow)
        self.actionLicence.setObjectName(_fromUtf8("actionLicence"))
        self.actionSteel_section_list = QtGui.QAction(MainWindow)
        self.actionSteel_section_list.setObjectName(_fromUtf8("actionSteel_section_list"))
        self.menuFile.addAction(self.actionLoad_dxf)
        self.menuInfo.addAction(self.actionAbout)
        self.menuInfo.addAction(self.actionLicence)
        self.menuInfo.addSeparator()
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuInfo.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow", None))
        self.pushButton_Concrete_Check_and_save.setText(_translate("MainWindow", "Concrete_Check and save", None))
        self.pushButton_Concrete_Show_dep_and_save.setText(_translate("MainWindow", "Concrete_Show dependencies and save", None))
        self.pushButton_Concrete_Check.setText(_translate("MainWindow", "Concrete_Check", None))
        self.pushButton_Concrete_Process.setText(_translate("MainWindow", "Concrete_Process data and save", None))
        self.pushButton_Concrete_Process_renum.setText(_translate("MainWindow", "Concrete_Process data, renumerate and save", None))
        self.pushButton_Concrete_Process_renum_schedules.setText(_translate("MainWindow", "Concrete_Process data, renumerate, schedules and save", None))
        self.pushButton_Concrete_help.setText(_translate("MainWindow", "Concrete help", None))
        self.pushButton_Concrete_check_for_quite_similare_bar_no.setText(_translate("MainWindow", "(check for quite similare bar no.)", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Concrete Model", None))
        self.pushButton_Steel_Check.setText(_translate("MainWindow", "Steel_Check", None))
        self.pushButton_Steel_Check_and_save.setText(_translate("MainWindow", "Steel_Check and save", None))
        self.pushButton_Steel_Show_dep_and_save.setText(_translate("MainWindow", "Steel_Show dependencies and save", None))
        self.pushButton_Steel_Process_renum.setText(_translate("MainWindow", "Steel_Process data, renumerate and save", None))
        self.pushButton_Steel_Process.setText(_translate("MainWindow", "Steel_Process data and save", None))
        self.pushButton_Steel_Process_renum_schedules.setText(_translate("MainWindow", "Steel_Process data, renumerate, schedules and save", None))
        self.pushButton_Steel_help.setText(_translate("MainWindow", "Steel help", None))
        self.label.setText(_translate("MainWindow", "Show sectionbase profil list for", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Steel Model", None))
        self.pushButton_Command_do_all.setText(_translate("MainWindow", "Do all commands", None))
        self.pushButton_Command_show.setText(_translate("MainWindow", "Show commands", None))
        self.pushButton_Command_help.setText(_translate("MainWindow", "Command help", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), _translate("MainWindow", "Command", None))
        self.pushButton_Inject_to_file.setText(_translate("MainWindow", "Inject DS system to file", None))
        self.pushButton_System_help.setText(_translate("MainWindow", "Ds system help", None))
        self.groupBox.setTitle(_translate("MainWindow", "Set language", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("MainWindow", "DS system", None))
        self.menuFile.setTitle(_translate("MainWindow", "Fi&le", None))
        self.menuInfo.setTitle(_translate("MainWindow", "&Info", None))
        self.actionLoad_dxf.setText(_translate("MainWindow", "&Load dxf ", None))
        self.actionLoad_dxf.setShortcut(_translate("MainWindow", "Ctrl+O", None))
        self.actionAbout.setText(_translate("MainWindow", "&About", None))
        self.actionHelp.setText(_translate("MainWindow", "&Help", None))
        self.actionHelp.setShortcut(_translate("MainWindow", "F1", None))
        self.actionLicence.setText(_translate("MainWindow", "&License", None))
        self.actionSteel_section_list.setText(_translate("MainWindow", "&Steel section list", None))

