- project:
    check:
      jobs:
        - manilaclient-dsvm-neutron-functional
        - rally-dsvm-manila-multibackend:
            voting: false
        - rally-dsvm-manila-multibackend-no-ss:
            voting: false
        - openstack-tox-lower-constraints
    gate:
      jobs:
        - manilaclient-dsvm-neutron-functional

        - openstack-tox-lower-constraints
- job:
    name: manilaclient-dsvm-neutron-functional
    parent: legacy-dsvm-base
    run: playbooks/legacy/manilaclient-dsvm-neutron-functional/run.yaml
    post-run: playbooks/legacy/manilaclient-dsvm-neutron-functional/post.yaml
    timeout: 4800
    required-projects:
      - openstack-infra/devstack-gate
      - openstack/manila
      - openstack/neutron
      - openstack/python-manilaclient
      - openstack/manila-tempest-plugin
