[tool.poetry]
name = "checkstat"
version = "0.1.0"
description = ""
authors = ["Franccesco Orozco <franccesco.orozco@codingdose.info>"]

[tool.poetry.dependencies]
python = "*"
click = "^6.7"
colorama = "^0.3.9"
requests = "^2.19"

[tool.poetry.dev-dependencies]
pytest = "^3.0"

[tool.poetry.scripts]
checkstat = "checkstat.cli:main"
