---
# .. vim: foldmarker=[[[,]]]:foldmethod=marker

# debops.gunicorn default variables [[[
# =====================================

# .. contents:: Sections
#    :local:
#
# .. include:: ../../../includes/global.rst


# APT packages [[[
# ----------------

# .. envvar:: gunicorn__base_packages [[[
#
# The essential packages to install for gunicorn support.
gunicorn__base_packages: [ 'gunicorn', 'python-setproctitle' ]

                                                                   # ]]]
# .. envvar:: gunicorn__packages [[[
#
# Additional APT packages to install with gunicorn.
gunicorn__packages: []
                                                                   # ]]]
                                                                   # ]]]
# Default configuration [[[
# -------------------------

# .. envvar:: gunicorn__workers [[[
#
# The default number of worker threads used by Green Unicorn applications if
# not specified otherwise.
gunicorn__workers: '{{ ansible_processor_vcpus|int + 1 }}'

                                                                   # ]]]
# .. envvar:: gunicorn__user [[[
#
# The default UNIX account used by the Green Unicorn process if it's not
# specified in the configuration.
gunicorn__user: 'www-data'

                                                                   # ]]]
# .. envvar:: gunicorn__group [[[
#
# The default UNIX group used by the Green Unicorn process if it's not
# specified in the configuration.
gunicorn__group: 'www-data'

                                                                   # ]]]
# .. envvar:: gunicorn__systemd_timeout [[[
#
# Define the default timeout in :command:`systemd` for Green Unicorn services.
gunicorn__systemd_timeout: '90'
                                                                   # ]]]
                                                                   # ]]]
# Managed applications [[[
# ------------------------

# .. envvar:: gunicorn__applications [[[
#
# List of WSGI applications which are managed by the role, defined in the
# Ansible inventory. See :ref:`gunicorn__ref_applications` for more details.
gunicorn__applications: []

                                                                   # ]]]
# .. envvar:: gunicorn__dependent_applications [[[
#
# List of WSGI applications which are managed by the role, defined by other
# Ansible roles using dependent variables.
# See :ref:`gunicorn__ref_applications` for more details.
gunicorn__dependent_applications: []
                                                                   # ]]]
                                                                   # ]]]
# Configuration for other Ansible roles [[[
# -----------------------------------------

# .. envvar:: gunicorn__apt_preferences__dependent_list [[[
#
# Configuration for the :ref:`debops.apt_preferences` Ansible role.
gunicorn__apt_preferences__dependent_list:

  - packages: [ 'gunicorn', 'gunicorn-*' ]
    backports: [ 'jessie' ]
    reason: 'Feature parity with Debian Stretch'
    by_role: 'debops.gunicorn'

# .. envvar:: gunicorn__logrotate__dependent_config [[[
#
# Configuration for the :ref:`debops.logrotate` Ansible role.
gunicorn__logrotate__dependent_config:

  - filename: 'gunicorn'
    logs: [ '/var/log/gunicorn/*.log', '/var/log/gunicorn/*/*.log' ]
    divert: True
    options: |
      rotate 4
      compress
      delaycompress
      missingok
      notifempty
      weekly
      sharedscripts
    postrotate: |
      invoke-rc.d --quiet gunicorn reload >/dev/null
    comment: 'Log rotation for Green Unicorn logs'
                                                                   # ]]]
                                                                   # ]]]
                                                                   # ]]]
