
# This file was generated by 'versioneer.py' (0.13) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

version_version = '1.4.3'
version_full = '8da74d1a5c590699e92378d321e4926779b1712c'
def get_versions(default={}, verbose=False):
    return {'version': version_version, 'full': version_full}

