
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2018-07-18T14:33:52+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "f74c8e791b041781dfc075bb2d5792b31b560292",
 "version": "1.8.0.post1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
