
# This file was generated by 'versioneer.py' (0.17) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2018-07-23T19:36:16-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "7ee25ab0c87ca1c4b78a0833d6f3beeef3290427",
 "version": "3.6.3.post1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
