# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import moonshade_pb2 as moonshade__pb2


class documentStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.FindOne = channel.unary_unary(
        '/moonshade.document/FindOne',
        request_serializer=moonshade__pb2.FindOneRequest.SerializeToString,
        response_deserializer=moonshade__pb2.FindOneReply.FromString,
        )
    self.DeleteOne = channel.unary_unary(
        '/moonshade.document/DeleteOne',
        request_serializer=moonshade__pb2.DeleteOneRequest.SerializeToString,
        response_deserializer=moonshade__pb2.DeleteOneReply.FromString,
        )
    self.InsertOne = channel.unary_unary(
        '/moonshade.document/InsertOne',
        request_serializer=moonshade__pb2.InsertOneRequest.SerializeToString,
        response_deserializer=moonshade__pb2.InsertOneReply.FromString,
        )
    self.ReplaceOne = channel.unary_unary(
        '/moonshade.document/ReplaceOne',
        request_serializer=moonshade__pb2.ReplaceOneRequest.SerializeToString,
        response_deserializer=moonshade__pb2.ReplaceOneReply.FromString,
        )
    self.UpdateOne = channel.unary_unary(
        '/moonshade.document/UpdateOne',
        request_serializer=moonshade__pb2.UpdateOneRequest.SerializeToString,
        response_deserializer=moonshade__pb2.UpdateOneReply.FromString,
        )


class documentServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def FindOne(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def DeleteOne(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def InsertOne(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def ReplaceOne(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def UpdateOne(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_documentServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'FindOne': grpc.unary_unary_rpc_method_handler(
          servicer.FindOne,
          request_deserializer=moonshade__pb2.FindOneRequest.FromString,
          response_serializer=moonshade__pb2.FindOneReply.SerializeToString,
      ),
      'DeleteOne': grpc.unary_unary_rpc_method_handler(
          servicer.DeleteOne,
          request_deserializer=moonshade__pb2.DeleteOneRequest.FromString,
          response_serializer=moonshade__pb2.DeleteOneReply.SerializeToString,
      ),
      'InsertOne': grpc.unary_unary_rpc_method_handler(
          servicer.InsertOne,
          request_deserializer=moonshade__pb2.InsertOneRequest.FromString,
          response_serializer=moonshade__pb2.InsertOneReply.SerializeToString,
      ),
      'ReplaceOne': grpc.unary_unary_rpc_method_handler(
          servicer.ReplaceOne,
          request_deserializer=moonshade__pb2.ReplaceOneRequest.FromString,
          response_serializer=moonshade__pb2.ReplaceOneReply.SerializeToString,
      ),
      'UpdateOne': grpc.unary_unary_rpc_method_handler(
          servicer.UpdateOne,
          request_deserializer=moonshade__pb2.UpdateOneRequest.FromString,
          response_serializer=moonshade__pb2.UpdateOneReply.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'moonshade.document', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
